import Link from 'next/link';import {notFound} from 'next/navigation';import {copy,isLocale} from '@/lib/i18n';
export default async function Home({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!isLocale(locale))notFound();const c=copy[locale];return <main>
<section className="hero shell"><div><div className="eyebrow">{c.home.eyebrow}</div><h1>{c.home.title}</h1></div><div><p>{c.home.lead}</p><div className="actions"><Link className="button primary" href={`/${locale}/creators`}>{c.home.creator}</Link><Link className="button" href={`/${locale}/brands`}>{c.home.brand}</Link></div></div></section>
<section className="section shell"><div className="section-head"><div className="eyebrow">01 / WHY NATIVE</div><div><h2>{c.home.problemTitle}</h2><p className="section-lead">{c.home.problemLead}</p></div></div></section>
<div className="ticker">BERLIN ↔ SHANGHAI ↔ GUANGZHOU ↔ EUROPE ↔ CHINA</div>
<section className="section shell"><div className="section-head"><div className="eyebrow">02 / SERVICES</div><div><h2>{c.home.servicesTitle}</h2><p className="section-lead">{c.home.servicesLead}</p></div></div><div className="grid">{c.serviceCards.map((x,i)=><div className="card" key={x[0]}><div><div className="num">0{i+1}</div><h3>{x[0]}</h3></div><p>{x[1]}</p></div>)}</div></section>
<section className="section shell"><div className="split"><div className="big-card"><div className="eyebrow">CREATORS</div><h3>{c.creators.title}</h3><p>{c.creators.lead}</p><Link className="button" href={`/${locale}/creators`}>{c.home.creator}</Link></div><div className="big-card light"><div className="eyebrow">BRANDS</div><h3>{c.brands.title}</h3><p>{c.brands.lead}</p><Link className="button" href={`/${locale}/brands`}>{c.home.brand}</Link></div></div></section>
<section className="section shell"><div className="section-head"><div className="eyebrow">03 / MARKETS</div><div><h2>{c.home.marketsTitle}</h2><p className="section-lead">{c.home.marketsLead}</p></div></div></section>
</main>}
