import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {CaseCard} from '@/components/CaseCard';
import {casesCopy} from '@/lib/cases';
import {isLocale} from '@/lib/i18n';
type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale}=await params;if(!isLocale(locale))return {};const {seo}=casesCopy[locale];return {title:seo.title,description:seo.description,alternates:{canonical:`/${locale}/cases`,languages:{de:'/de/cases',en:'/en/cases','zh-CN':'/zh/cases','x-default':'/en/cases'}}};}
function Mark({number,label}:{number:string;label:string}){return <div className="creator-mark"><span>{number}</span><span>{label}</span></div>}
function List({items}:{items:readonly string[]}){return <ul className="creator-list">{items.map(x=><li key={x}>{x}</li>)}</ul>}
export default async function CasesPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();const c=casesCopy[locale];return <main className="cases-page" lang={locale}>
<section className="creator-hero cases-hero shell"><Mark number="01" label={c.hero.eyebrow}/><div className="creator-hero-copy"><h1>{c.hero.title}</h1><div className="creator-hero-support">{c.hero.paras.map(x=><p key={x}>{x}</p>)}<div className="creator-actions"><Link className="creator-button creator-button-solid" href={`/${locale}/contact`}>{c.hero.primary}<span>↗</span></Link><Link className="creator-button creator-button-line" href={`/${locale}/services`}>{c.hero.secondary}<span>↗</span></Link></div></div></div></section>
<section className="cases-categories creator-section shell"><Mark number="02" label="CASE CATEGORIES"/><h2>{c.categories.title}</h2><div className="cases-category-grid">{c.categories.items.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section className="cases-featured creator-section"><div className="shell"><Mark number="03" label={c.featured.eyebrow}/><div className="cases-featured-head"><h2>{c.featured.title}</h2><p>{c.featured.body}</p></div><div className="cases-featured-media" aria-label={c.featured.media}><span>{c.featured.media}</span><i aria-hidden="true"/></div><dl className="cases-featured-meta">{c.featured.meta.map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl></div></section>
{c.sections.map((s,i)=><section className={`cases-framework creator-section ${i===1?'cases-framework-muted':''}`} key={s.eyebrow}><div className="shell"><Mark number={`0${i+4}`} label={s.eyebrow}/><div className="cases-framework-head"><div><h2>{s.title}</h2><p>{s.body}</p></div><div><p className="creator-list-lead">{s.lead}</p><List items={s.items}/></div></div><p className="cases-format-lead">{s.formatLead}</p><div className="cases-format">{s.format.map((x,j)=><article key={x[0]}><span>{String(j+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>)}
<section className="cases-document creator-section"><div className="shell"><Mark number="07" label="CASE METHOD"/><div className="cases-document-head"><h2>{c.document.title}</h2><div><p>{c.document.body}</p><p className="creator-list-lead">{c.document.lead}</p></div></div><div className="cases-document-list">{c.document.items.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section className="cases-grid-section creator-section shell"><Mark number="08" label="FUTURE CASE GRID"/><h2>{c.grid.title}</h2><div className="cases-grid">{c.grid.slots.map(x=><CaseCard item={x} key={x.id}/>)}</div></section>
<section className="creator-final creator-section"><div className="shell"><Mark number="09" label="LET’S TALK"/><div className="creator-final-grid"><h2>{c.final.title}</h2><div><p>{c.final.body}</p><Link className="creator-button creator-button-light" href={`/${locale}/contact`}>{c.final.cta}<span>↗</span></Link></div></div></div></section>
</main>}
