import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {brandsCopy,type BrandBlock} from '@/lib/brands';
import {isLocale} from '@/lib/i18n';
type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale}=await params;if(!isLocale(locale))return {};const {seo}=brandsCopy[locale];return {title:seo.title,description:seo.description,alternates:{canonical:`/${locale}/brands`,languages:{de:'/de/brands',en:'/en/brands','zh-CN':'/zh/brands','x-default':'/en/brands'}}};}
function Mark({number,label}:{number:string;label:string}){return <div className="creator-mark"><span>{number}</span><span>{label}</span></div>}
function List({block}:{block:BrandBlock}){return <><p className="creator-list-lead">{block.lead}</p><ul className="creator-list">{block.items.map(x=><li key={x}>{x}</li>)}</ul><p className="creator-closing">{block.closing}</p></>}
function Detail({number,label,block,dark=false,media=false}:{number:string;label:string;block:BrandBlock;dark?:boolean;media?:boolean}){return <section className={`${dark?'creator-production':'creator-detail'} creator-section`}><div className="shell"><Mark number={number} label={label}/><div className="creator-detail-grid"><div><h2>{block.title}</h2><p>{block.body}</p></div><div><List block={block}/></div></div>{media&&<div className="brand-media-frame"><span>FUTURE PRODUCTION SHOWCASE</span><strong><i aria-hidden="true">▶</i><span>Reserved for future media</span></strong><span>CAMPAIGN FILMS · PRODUCT FILMS · CREATOR CAMPAIGNS · PHOTOGRAPHY · LOCAL PRODUCTIONS</span></div>}</div></section>}
export default async function BrandsPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();const c=brandsCopy[locale];return <main className="brands-page" lang={locale}>
<section className="creator-hero shell"><Mark number="01" label={c.hero.eyebrow}/><div className="creator-hero-copy"><h1>{c.hero.title}</h1><div className="creator-hero-support"><p>{c.hero.body}</p><div className="creator-actions"><Link className="creator-button creator-button-solid" href={`/${locale}/contact`}>{c.hero.primary}<span>↗</span></Link><a className="creator-button creator-button-line" href="#brand-services">{c.hero.secondary}<span>↓</span></a></div></div></div><div className="brand-hero-placeholder"><span>FUTURE BRAND SHOWREEL</span><strong><i>↗</i><span>Campaign films · Product photography<br/>Brand localization examples</span></strong><span>MEDIA CONTAINER — 16:9</span></div></section>
<section className="creator-problem creator-section shell"><Mark number="02" label="CONTEXT"/><div className="creator-problem-grid"><h2>{c.problem.title}</h2><div><p>{c.problem.body}</p><strong>{c.problem.closing}</strong></div></div></section>
<section id="brand-services" className="creator-pillars creator-section"><div className="shell"><Mark number="03" label="CAPABILITIES"/><h2>{c.pillars.title}</h2></div><div className="creator-pillar-list">{c.pillars.items.map(([title,body],i)=><article className="creator-pillar shell" key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p><span>↗</span></article>)}</div></section>
<section className="brand-positioning creator-section shell"><Mark number="04" label="POSITIONING & LOCALIZATION"/><div className="creator-content-grid">{[c.positioning.left,c.positioning.right].map((b,i)=><article className="creator-content-column" key={b.title}><span className="creator-column-index">{i?'LOCAL EXPERIENCE':'BRAND CORE'}</span><h2>{b.title}</h2><p>{b.body}</p><p className="creator-list-lead">{b.lead}</p><ul className="creator-list">{b.items.map(x=><li key={x}>{x}</li>)}</ul>{b.closing.includes('|')?<><p className="creator-list-lead">{b.closing.split('|')[0]}</p><ul className="creator-list">{b.closing.split('|').slice(1).map(x=><li key={x}>{x}</li>)}</ul></>:<p className="creator-closing">{b.closing}</p>}</article>)}</div></section>
<Detail number="05" label="CAMPAIGNS & CREATOR PARTNERSHIPS" block={c.campaigns}/><Detail number="06" label="PRODUCTION" block={c.production} dark media/><Detail number="07" label="MARKET ENTRY & PLATFORM STRATEGY" block={c.entry}/><Detail number="08" label="WORKING WITH EXISTING TEAMS" block={c.teams}/>
<section className="creator-markets creator-section"><div className="shell"><Mark number="09" label="EUROPE ↔ CHINA"/><div className="creator-market-intro"><h2>{c.markets.title}</h2><p>{c.markets.body}</p></div><div className="creator-market-track"><span>EUROPE</span><i>→</i><i>←</i><span>CHINA</span></div><div className="creator-market-directions"><article><span>01</span><h3>{c.markets.fromEurope}</h3><p>{c.markets.fromEuropeBody}</p></article><article><span>02</span><h3>{c.markets.fromChina}</h3><p>{c.markets.fromChinaBody}</p></article></div><p className="creator-market-line">{c.markets.line}</p></div></section>
<section className="creator-case creator-section shell"><Mark number="10" label={c.case.eyebrow}/><div className="creator-case-grid"><div><h2>{c.case.title}</h2><p>{c.case.body}</p></div><div className="creator-case-frame"><span>COMING SOON</span><strong>{c.case.label}</strong><span>FUTURE STRATEGY · PRODUCTION · EXECUTION</span></div></div></section>
<section className="creator-final creator-section"><div className="shell"><Mark number="11" label="LET’S TALK"/><div className="creator-final-grid"><h2>{c.final.title}</h2><div><p>{c.final.body}</p><Link className="creator-button creator-button-light" href={`/${locale}/contact`}>{c.final.cta}<span>↗</span></Link></div></div></div></section>
</main>}
