import type {Locale} from './i18n';
type Person={name:string;role:string;body:string;body2:string;lead:string;items:string[]};
type AboutCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};why:{title:string;body:string;lead:string;items:string[];closing:string;closing2:string};principle:{eyebrow:string;title:string;paras:string[];lead:string;items:string[];closing:string[]};disciplines:{title:string;left:{title:string;body:string;lead:string;items:string[]};right:{title:string;body:string;lead:string;items:string[]};line:string};founders:{eyebrow:string;title:string;people:Person[];line:string};network:{eyebrow:string;title:string;paras:string[];statement:string};knowledge:{title:string;paras:string[];lead:string;items:string[];closing:string};markets:{title:string;paras:string[];lead:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};direction:{eyebrow:string;title:string;paras:string[];closing:string[]};final:{title:string;body:string;cta:string}};
export const aboutCopy:Record<Locale,AboutCopy>={
en:{
seo:{title:'About NATIVE',description:'Why NATIVE connects cross-cultural strategy, localization, production and local expertise for creators and brands entering new markets.'},
hero:{eyebrow:'ABOUT NATIVE',title:'Built to bring markets closer together.',body:'NATIVE brings strategy, localization and production together to help creators and brands become relevant in new markets — without losing what made them recognizable in the first place.',primary:'Start a conversation',secondary:'Explore our services'},
why:{title:'Because translation is only the beginning.',body:'Creators and brands now reach people far beyond their home markets. But content does not become locally relevant simply because the language changes.',lead:'A new market can mean:',items:['different platforms','different cultural codes','different expectations','different storytelling','different visual language','different creator ecosystems','different buying behavior','different communication habits'],closing:'That is where NATIVE comes in.',closing2:'We connect strategy, localization, production and partnerships so content can enter a new market without feeling imported.'},
principle:{eyebrow:'OUR PRINCIPLE',title:'Make your brand feel local.',paras:['For NATIVE, “local” does not mean hiding where a brand or creator comes from.','It means understanding the market well enough for the communication to feel natural there.','The identity stays recognizable.','The way it is expressed can change.'],lead:'That can involve:',items:['language','tone','format','platform','creators','production','campaign ideas','storytelling','local partnerships'],closing:['The goal is not to make the brand look different.','The goal is to make sure it is understood in the new market.']},
disciplines:{title:'Strategy and execution belong together.',left:{title:'Strategy',body:'A new market does not start with content. It starts with the right questions.',lead:'That includes:',items:['positioning','market entry','platforms','audiences','partnerships','commercial opportunities','local context']},right:{title:'Execution',body:'A good strategy only matters when it is executed well.',lead:'That includes:',items:['creative direction','content','video','editing','production','localization','campaign execution']},line:'NATIVE brings both together from the start.'},
founders:{eyebrow:'FOUNDERS',title:'Two perspectives. One shared approach.',people:[{name:'Daniel Nonn',role:'Strategy & Partnerships',body:'Daniel leads strategy, business development, partnerships and cross-market positioning.',body2:'His focus is the business behind the content: Where are the real opportunities? How should a new market be approached? And which relationships can help creators and brands build lasting relevance there?',lead:'Areas:',items:['strategy','business development','partnerships','market entry','cross-market positioning','creator and brand relations']},{name:'Timm',role:'Creative & Production',body:'Timm leads creative direction, production, video and content execution.',body2:'His focus is turning strategy into content that actually works — from social-first formats to campaigns and full productions.',lead:'Areas:',items:['creative direction','production','video','content execution','editing','visual storytelling']}],line:'Clear responsibilities. Shared decisions where strategy and creative meet.'},
network:{eyebrow:'NETWORK & MARKET ACCESS',title:'Built on relationships that have grown over years.',paras:['NATIVE combines strategic and creative work with long-standing relationships, direct market access and real cross-market experience between Europe and China.','These connections are not assembled for individual projects. They are built through years of collaboration, direct exchange and hands-on experience in both markets.','Especially in China, language, platform culture, content, partnerships and market dynamics are not interpreted from the outside. They are developed and reviewed together with people who know the market from within.','That gives NATIVE access to context, perspectives and relationships that cannot be built overnight.'],statement:'NATIVE does not just connect markets. We work from relationships that already exist between them.'},
knowledge:{title:'Local understanding cannot be faked.',paras:['A translation can be grammatically correct and still feel wrong.','A campaign can look great and still miss the audience.','A platform strategy can make perfect sense on paper and still fail locally.','That is why local knowledge at NATIVE is not a final review step. It is part of the process from the beginning.'],lead:'Depending on the market, that can include:',items:['language','cultural review','platform behavior','trends','creator selection','community expectations','campaign ideas','final quality control'],closing:'Not just correct. Relevant.'},
markets:{title:'Between Europe and China. Built to go further.',paras:['Europe and China form the first major corridor for NATIVE.','The differences between the two markets go far beyond geography. Platforms, communication culture, content behavior, customer expectations and creator ecosystems can work in completely different ways.','That creates challenges — and opportunities.'],lead:'',fromEurope:'Europe → China',fromEuropeBody:'We help creators and brands access Chinese platforms, audiences and partnerships.',fromChina:'China → Europe',fromChinaBody:'We help Chinese creators and brands adapt communication, content and partnerships so they feel natural and relevant in Europe.',line:'This is our starting point, not our limit.'},
direction:{eyebrow:'DIRECTION',title:'From one corridor to a broader international network.',paras:['NATIVE starts between Europe and China, but the underlying challenge exists everywhere.','Creators want to reach new audiences. Brands want to enter new markets. Culture changes how both are understood.','Over time, NATIVE aims to connect strategy, creative execution and local market knowledge across more regions.'],closing:['Not by pretending every market is the same.','By building real local understanding wherever the work goes.']},
final:{title:'Different markets. One principle: stay relevant.',body:'If you are building something that needs to work across cultures, we should talk.',cta:'Start a conversation'}},
de:{
seo:{title:'Über NATIVE',description:'Warum NATIVE Strategie, Lokalisierung, Produktion und lokales Marktwissen für Creator und Marken verbindet.'},
hero:{eyebrow:'ÜBER NATIVE',title:'Entstanden, um Märkte näher zusammenzubringen.',body:'NATIVE verbindet Strategie, Lokalisierung und Produktion, damit Creator und Marken in neuen Märkten relevant werden – ohne zu verlieren, was sie ursprünglich ausmacht.',primary:'Gespräch starten',secondary:'Leistungen entdecken'},
why:{title:'Weil Übersetzung nur der Anfang ist.',body:'Marken und Creator erreichen heute Menschen weit über den eigenen Markt hinaus. Trotzdem wird Content nicht automatisch relevant, nur weil er in einer anderen Sprache erscheint.',lead:'Neue Märkte bringen neue Regeln mit:',items:['andere Plattformen','andere kulturelle Codes','andere Erwartungen','anderes Storytelling','andere Bildsprache','andere Creator-Ökosysteme','anderes Kaufverhalten','andere Kommunikationsgewohnheiten'],closing:'Genau an dieser Stelle setzt NATIVE an.',closing2:'Wir verbinden Strategie, Lokalisierung, Produktion und Partnerschaften so, dass Content im neuen Markt natürlich wirkt – statt wie eine importierte Version.'},
principle:{eyebrow:'UNSER PRINZIP',title:'Make your brand feel local.',paras:['Für NATIVE bedeutet „local“ nicht, die Herkunft einer Marke oder eines Creators zu verstecken.','Es bedeutet, den Markt so gut zu verstehen, dass Kommunikation dort natürlich funktioniert.','Die Identität bleibt erkennbar.','Die Art, wie sie ausgedrückt wird, darf sich verändern.'],lead:'Das kann betreffen:',items:['Sprache','Tonalität','Format','Plattform','Creator','Produktion','Kampagnenideen','Storytelling','lokale Partnerschaften'],closing:['Das Ziel ist nicht, anders zu wirken.','Das Ziel ist, im neuen Markt richtig verstanden zu werden.']},
disciplines:{title:'Strategie und Umsetzung gehören zusammen.',left:{title:'Strategie',body:'Ein neuer Markt beginnt nicht mit Content, sondern mit den richtigen Fragen.',lead:'Dazu gehören:',items:['Positionierung','Market Entry','Plattformen','Zielgruppen','Partnerschaften','kommerzielle Möglichkeiten','lokaler Kontext']},right:{title:'Umsetzung',body:'Eine gute Strategie wird erst dann relevant, wenn sie sauber umgesetzt wird.',lead:'Dazu gehören:',items:['Creative Direction','Content','Video','Editing','Produktion','Lokalisierung','Kampagnenumsetzung']},line:'NATIVE verbindet beides von Anfang an.'},
founders:{eyebrow:'GRÜNDER',title:'Zwei Perspektiven. Ein gemeinsamer Ansatz.',people:[{name:'Daniel Nonn',role:'Strategy & Partnerships',body:'Daniel verantwortet Strategie, Business Development, Partnerschaften und Cross-Market-Positionierung.',body2:'Sein Fokus liegt auf dem Geschäft hinter dem Content: Wo entstehen echte Chancen? Wie sollte ein neuer Markt erschlossen werden? Und welche Beziehungen helfen Creatorn und Marken dabei, dort nachhaltig relevant zu werden?',lead:'Schwerpunkte:',items:['Strategie','Business Development','Partnerschaften','Market Entry','Cross-Market-Positionierung','Creator- und Brand-Relations']},{name:'Timm',role:'Creative & Production',body:'Timm verantwortet Creative Direction, Produktion, Video und Content Execution.',body2:'Sein Fokus liegt darauf, Strategie in Content zu übersetzen, der tatsächlich funktioniert – von Social-first-Formaten bis zu Kampagnen und kompletten Produktionen.',lead:'Schwerpunkte:',items:['Creative Direction','Produktion','Video','Content Execution','Editing','Visual Storytelling']}],line:'Klare Verantwortlichkeiten. Gemeinsame Entscheidungen dort, wo Strategie und Kreativität zusammenkommen.'},
network:{eyebrow:'NETZWERK & MARKTZUGANG',title:'Über Jahre gewachsene Verbindungen. Lokales Verständnis aus erster Hand.',paras:['NATIVE verbindet strategische und kreative Arbeit mit gewachsenen Beziehungen, direktem Marktzugang und echter Cross-Market-Erfahrung zwischen Europa und China.','Diese Verbindungen entstehen nicht erst für einzelne Projekte. Sie basieren auf jahrelanger Zusammenarbeit, direktem Austausch und realer Erfahrung in beiden Märkten.','Gerade in China werden Sprache, Plattformkultur, Content, Partnerschaften und Marktmechaniken nicht von außen interpretiert, sondern gemeinsam mit Menschen entwickelt und geprüft, die den Markt aus eigener Erfahrung kennen.','So entsteht Zugang zu Kontext, Perspektiven und Beziehungen, die sich nicht kurzfristig aufbauen lassen.'],statement:'NATIVE verbindet nicht nur Märkte. Wir arbeiten aus bestehenden Beziehungen zwischen ihnen heraus.'},
knowledge:{title:'Lokales Verständnis lässt sich nicht vortäuschen.',paras:['Eine Übersetzung kann grammatikalisch korrekt sein und sich trotzdem falsch anfühlen.','Eine Kampagne kann hervorragend aussehen und trotzdem an der Zielgruppe vorbeigehen.','Eine Plattformstrategie kann auf dem Papier sinnvoll sein und lokal trotzdem scheitern.','Deshalb ist lokales Know-how bei NATIVE kein letzter Korrekturschritt, sondern Teil des gesamten Prozesses.'],lead:'Je nach Markt geht es dabei zum Beispiel um:',items:['Sprache','kulturelle Prüfung','Plattformverhalten','Trends','Creator-Auswahl','Community-Erwartungen','Kampagnenideen','finale Qualitätskontrolle'],closing:'Nicht nur korrekt. Relevant.'},
markets:{title:'Zwischen Europa und China. Von hier aus weiter gedacht.',paras:['Europa und China bilden den ersten großen Korridor für NATIVE.','Die Unterschiede zwischen beiden Märkten gehen weit über Geografie hinaus. Plattformen, Kommunikationskultur, Content-Verhalten, Kundenerwartungen und Creator-Ökosysteme funktionieren teilweise vollkommen unterschiedlich.','Daraus entstehen Herausforderungen – und Chancen.'],lead:'',fromEurope:'Europa → China',fromEuropeBody:'Wir helfen Creatorn und Marken dabei, Zugang zu chinesischen Plattformen, Zielgruppen und Partnerschaften zu finden.',fromChina:'China → Europa',fromChinaBody:'Wir helfen chinesischen Creatorn und Marken dabei, Kommunikation, Content und Partnerschaften so anzupassen, dass sie in Europa natürlich und relevant wirken.',line:'Das ist unser Ausgangspunkt – nicht unsere Grenze.'},
direction:{eyebrow:'AUSBLICK',title:'Von einem ersten Korridor zu einem internationalen Netzwerk.',paras:['NATIVE startet zwischen Europa und China. Die Herausforderung dahinter gibt es aber überall.','Creator möchten neue Zielgruppen erreichen. Marken möchten neue Märkte erschließen. Kultur verändert, wie beide verstanden werden.','Langfristig soll NATIVE Strategie, kreative Umsetzung und lokales Marktwissen über weitere Regionen hinweg verbinden.'],closing:['Nicht, indem wir so tun, als wären alle Märkte gleich.','Sondern indem dort echtes lokales Verständnis entsteht, wo es gebraucht wird.']},
final:{title:'Unterschiedliche Märkte. Ein Prinzip: relevant sein.',body:'Wenn du etwas aufbaust, das über kulturelle Grenzen hinweg funktionieren soll, sollten wir miteinander sprechen.',cta:'Gespräch starten'}},
zh:{
seo:{title:'关于 NATIVE',description:'了解 NATIVE 为什么将跨文化策略、本地化、内容制作与当地专业能力连接起来。'},
hero:{eyebrow:'关于 NATIVE',title:'让不同市场之间，更加靠近。',body:'NATIVE 把市场策略、本地化与内容制作连接在一起，帮助创作者和品牌进入新的市场，同时保留原本最有辨识度的部分。',primary:'联系我们',secondary:'了解我们的服务'},
why:{title:'因为翻译，只是开始。',body:'今天，品牌和创作者可以很容易触达本土市场之外的人群。但内容并不会因为换了一种语言，就自动变得适合当地。',lead:'进入新的市场，往往意味着：',items:['不同的平台','不同的文化语境','不同的受众期待','不同的叙事方式','不同的视觉表达','不同的创作者生态','不同的消费习惯','不同的沟通方式'],closing:'这正是 NATIVE 存在的原因。',closing2:'我们把策略、本地化、内容制作与合作资源连接起来，让内容进入新的市场时自然、可信，而不是像一个外来的版本。'},
principle:{eyebrow:'我们的原则',title:'Make your brand feel local.',paras:['对 NATIVE 来说，“local” 并不是隐藏品牌或创作者来自哪里。','真正重要的是理解当地市场，让沟通方式在那里自然成立。','品牌身份应该保持清晰。','表达方式则可以根据市场调整。'],lead:'这可能涉及：',items:['语言','语气','内容形式','平台','创作者','内容制作','品牌活动创意','叙事方式','当地合作关系'],closing:['目标不是让品牌变成另一个样子。','而是让它在新的市场真正被理解。']},
disciplines:{title:'策略与执行，本来就应该在一起。',left:{title:'策略',body:'进入新的市场，不应该从“先做什么内容”开始，而应该先问对问题。',lead:'包括：',items:['定位','Market Entry','平台','受众','合作关系','商业机会','当地语境']},right:{title:'执行',body:'好的策略，只有真正落地之后才有价值。',lead:'包括：',items:['Creative Direction','内容','视频','剪辑','制作','本地化','品牌活动执行']},line:'NATIVE 从一开始，就把两者放在一起。'},
founders:{eyebrow:'创始人',title:'两种视角，一个共同的方法。',people:[{name:'Daniel Nonn',role:'Strategy & Partnerships',body:'Daniel 负责 NATIVE 的市场策略、商务拓展、合作关系与跨市场定位。',body2:'他的重点，是理解内容背后的商业逻辑：真正的机会在哪里？新的市场应该怎么进入？哪些关系能够帮助品牌和创作者在当地建立长期价值？',lead:'主要领域：',items:['市场策略','商务拓展','合作关系','Market Entry','跨市场定位','创作者与品牌关系']},{name:'Timm',role:'Creative & Production',body:'Timm 负责创意指导、内容制作、视频与执行。',body2:'他的重点，是把策略变成真正有效的内容——从 Social-first 形式，到品牌活动和完整制作项目。',lead:'主要领域：',items:['Creative Direction','内容制作','视频','内容执行','剪辑','视觉叙事']}],line:'职责清晰。策略与创意交汇的地方，共同做决定。'},
network:{eyebrow:'关系网络与市场连接',title:'建立在多年积累的真实关系之上。',paras:['NATIVE 把策略与创意执行，与欧洲和中国之间长期积累的关系、直接市场连接和真实跨市场经验结合起来。','这些联系不是为了某一个项目临时建立的，而是来自多年合作、直接交流与持续的实际参与。','尤其在中国市场，语言、平台文化、内容、合作关系与市场逻辑，不是从外部猜测或简单判断，而是与真正了解当地市场的人一起完成。','这种长期积累，让 NATIVE 能够获得短时间内无法建立的市场语境、视角与关系资源。'],statement:'NATIVE 不只是连接市场，而是在已经存在的真实关系基础上开展工作。'},
knowledge:{title:'真正的本地理解，无法伪装。',paras:['一句话可以在语法上完全正确，却依然让当地人觉得不自然。','一场品牌活动可以做得很漂亮，却依然无法打动目标受众。','一个在纸面上完全合理的平台策略，也可能在当地市场失败。','所以，对 NATIVE 来说，本地知识不是最后一步的检查，而是从一开始就参与整个过程。'],lead:'根据市场不同，这可能包括：',items:['语言','文化审核','平台习惯','趋势','创作者选择','社区期待','品牌活动创意','最终质量检查'],closing:'不只是正确。还要真正相关。'},
markets:{title:'连接欧洲与中国，也为更多市场留出空间。',paras:['欧洲与中国，是 NATIVE 最初重点连接的两个市场。','两者之间的差异远不只是地理。平台、传播文化、内容习惯、消费者期待与创作者生态，都可能完全不同。','这些差异既带来挑战，也带来机会。'],lead:'',fromEurope:'欧洲 → 中国',fromEuropeBody:'我们帮助欧洲创作者与品牌进入中国的平台、受众与合作生态。',fromChina:'中国 → 欧洲',fromChinaBody:'我们帮助中国创作者与品牌调整沟通、内容与合作方式，让它们在欧洲更自然、更相关。',line:'这是我们的起点，不是边界。'},
direction:{eyebrow:'未来方向',title:'从欧洲与中国之间开始，走向更广泛的国际网络。',paras:['NATIVE 从欧洲与中国之间起步，但背后的问题存在于全球。','创作者希望接触新的受众。\n品牌希望进入新的市场。\n文化会改变人们理解两者的方式。','长期来看，NATIVE 希望把市场策略、创意执行与真正的本地知识连接到更多地区。'],closing:['不是假设每个市场都一样。','而是在项目真正进入哪里，就在那里建立正确的本地理解。']},
final:{title:'不同的市场，同一个原则：真正理解当地。',body:'如果你正在做一个需要跨文化沟通的品牌、内容或项目，我们可以聊聊。',cta:'联系我们'}}};
