import type {Locale} from './i18n';
type Person={name:string;role:string;body:string;body2:string;lead:string;items:string[]};
type AboutCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};why:{title:string;body:string;lead:string;items:string[];closing:string;closing2:string};principle:{eyebrow:string;title:string;paras:string[];lead:string;items:string[];closing:string[]};disciplines:{title:string;left:{title:string;body:string;lead:string;items:string[]};right:{title:string;body:string;lead:string;items:string[]};line:string};founders:{eyebrow:string;title:string;people:Person[];line:string};network:{eyebrow:string;title:string;paras:string[];statement:string};knowledge:{title:string;paras:string[];lead:string;items:string[];closing:string};markets:{title:string;paras:string[];lead:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};direction:{eyebrow:string;title:string;paras:string[];closing:string[]};final:{title:string;body:string;cta:string}};
export const aboutCopy:Record<Locale,AboutCopy>={
en:{
seo:{title:'About NATIVE',description:'Why NATIVE connects cross-cultural strategy, localization, production and local expertise for creators and brands entering new markets.'},
hero:{eyebrow:'ABOUT NATIVE',title:'Built to make distance feel smaller.',body:'NATIVE is a cross-cultural media, localization and production company helping creators and brands enter new markets without losing the identity that made them relevant in the first place.',primary:'Start a conversation',secondary:'Explore our services'},
why:{title:'Because translation is only the beginning.',body:'Brands and creators increasingly communicate across borders, but content does not become locally relevant just because the language changes.',lead:'A new market can mean:',items:['different platforms','different cultural references','different expectations','different storytelling','different visual language','different creators','different buying behavior','different communication habits'],closing:'NATIVE exists to connect these differences.',closing2:'We combine strategy, localization, production and partnerships so that content can enter a new market without feeling foreign.'},
principle:{eyebrow:'OUR PRINCIPLE',title:'Make your brand feel local.',paras:['For NATIVE, "local" does not mean pretending a brand or creator comes from somewhere else.','It means understanding how people in that market communicate, watch, buy, react and connect.','The identity should remain recognizable.','The expression around it can change.'],lead:'That can mean adapting:',items:['language','tone','format','platform','creators','production','campaign concepts','storytelling','local partnerships'],closing:['The goal is not to erase where a brand comes from.','The goal is to make sure the audience understands why it belongs there.']},
disciplines:{title:'Strategy and craft should not live in separate rooms.',left:{title:'Strategy',body:'Entering a new market starts with understanding the market itself.',lead:'That includes:',items:['positioning','market-entry strategy','platforms','audiences','partnerships','commercial opportunities','local context']},right:{title:'Craft',body:'The strategy only becomes visible through execution.',lead:'That includes:',items:['creative direction','content','video','editing','production','localization','campaign execution']},line:'NATIVE brings both together from the beginning.'},
founders:{eyebrow:'FOUNDERS',title:'Two perspectives. One operating model.',people:[{name:'Daniel Nonn',role:'Strategy & Partnerships',body:'Daniel focuses on strategy, business development, partnerships and cross-market positioning.',body2:'His role is to understand the business behind the content: where opportunities exist, how a new market should be approached and which relationships can help creators or brands build a meaningful local presence.',lead:'Areas:',items:['strategy','business development','partnerships','market entry','cross-market positioning','creator and brand relations']},{name:'Timm',role:'Creative & Production',body:'Timm focuses on creative direction, production, video and content execution.',body2:'His role is to turn strategy into content that people actually want to watch — from social-first formats to campaign and production work.',lead:'Areas:',items:['creative direction','production','video','content execution','editing','visual storytelling']}],line:'Different responsibilities. Shared decisions where strategy and creative meet.'},
network:{eyebrow:'NETWORK & MARKET ACCESS',title:'Built on relationships, not just research.',paras:['NATIVE combines strategy and creative work with long-standing relationships, direct market access and real cross-market experience across Europe and China.','These connections are not assembled project by project. They are built through years of collaboration, exchange and hands-on experience across both markets.','Especially in China, language, platform culture, content, partnerships and market dynamics are not interpreted from the outside. They are shaped and reviewed together with people who understand the market from within.','This gives NATIVE access to context, perspectives and relationships that cannot be built overnight.'],statement:'NATIVE does not only connect markets. It works from existing relationships between them.'},
knowledge:{title:'Local knowledge cannot be faked.',paras:['A translation can be grammatically correct and still feel wrong.','A campaign can look beautiful and still miss the audience.','A platform strategy can make sense globally and still fail locally.','That is why NATIVE treats native-language and local-market knowledge as part of the operating model, not as a final proofreading step.'],lead:'Depending on the market, local specialists can be involved in:',items:['language','cultural review','platform behavior','trends','creator selection','community expectations','campaign concepts','final quality control'],closing:'The goal is simple: Not only correct. Relevant.'},
markets:{title:'Built between Europe and China. Designed to travel further.',paras:['Europe and China are the first major corridor for NATIVE because the distance between the two markets goes far beyond geography.','Platforms, communication culture, content behavior, brand expectations and creator ecosystems differ significantly.','That creates challenges — and opportunity.'],lead:'NATIVE is built to work in both directions:',fromEurope:'Europe → China',fromEuropeBody:'Helping creators and brands enter Chinese platforms, audiences and partnerships.',fromChina:'China → Europe',fromChinaBody:'Helping Chinese creators and brands adapt communication, content and partnerships for European markets.',line:'This is the starting point, not the boundary.'},
direction:{eyebrow:'DIRECTION',title:'A cross-market company built beyond one corridor.',paras:['NATIVE starts with Europe and China, but the underlying challenge exists everywhere.','Creators want to reach new audiences. Brands want to enter new markets. Culture changes how both are understood.','The long-term direction is to build NATIVE into a network that connects strategy, creative work and local market knowledge across multiple regions.'],closing:['Not by pretending every market is the same.','By building the right local capability wherever the work goes.']},
final:{title:'Different markets. One principle: relevance.',body:'If you are building something that needs to work across cultures, we should talk.',cta:'Start a conversation'}},
de:{
seo:{title:'Über NATIVE',description:'Warum NATIVE Strategie, Lokalisierung, Produktion und lokales Marktwissen für Creator und Marken verbindet.'},
hero:{eyebrow:'ÜBER NATIVE',title:'Entstanden, um Distanz kleiner zu machen.',body:'NATIVE ist ein Cross-Cultural-Media-, Localization- und Production-Unternehmen, das Creatorn und Marken hilft, neue Märkte zu erschließen, ohne die Identität zu verlieren, die sie ursprünglich relevant gemacht hat.',primary:'Gespräch starten',secondary:'Leistungen entdecken'},
why:{title:'Weil Übersetzung nur der Anfang ist.',body:'Marken und Creator kommunizieren immer häufiger über Ländergrenzen hinweg. Doch Content wird nicht automatisch lokal relevant, nur weil sich die Sprache ändert.',lead:'Ein neuer Markt kann bedeuten:',items:['andere Plattformen','andere kulturelle Referenzen','andere Erwartungen','anderes Storytelling','andere Bildsprache','andere Creator','anderes Kaufverhalten','andere Kommunikationsgewohnheiten'],closing:'NATIVE verbindet diese Unterschiede.',closing2:'Wir kombinieren Strategie, Lokalisierung, Produktion und Partnerschaften, damit Content in einen neuen Markt gelangen kann, ohne dort fremd zu wirken.'},
principle:{eyebrow:'UNSER PRINZIP',title:'Make your brand feel local.',paras:['„Local“ bedeutet für NATIVE nicht, so zu tun, als würde eine Marke oder ein Creator aus einem anderen Markt stammen.','Es bedeutet zu verstehen, wie Menschen dort kommunizieren, Content konsumieren, kaufen, reagieren und Beziehungen zu Marken oder Creatorn aufbauen.','Die Identität soll erkennbar bleiben.','Die Art, wie sie ausgedrückt wird, darf sich verändern.'],lead:'Das kann bedeuten, Folgendes anzupassen:',items:['Sprache','Tonalität','Format','Plattform','Creator','Produktion','Kampagnenideen','Storytelling','lokale Partnerschaften'],closing:['Das Ziel ist nicht, die Herkunft einer Marke zu verstecken.','Das Ziel ist, dass die Zielgruppe versteht, warum sie in diesen Markt passt.']},
disciplines:{title:'Strategie und Umsetzung gehören an einen Tisch.',left:{title:'Strategie',body:'Der Eintritt in einen neuen Markt beginnt mit dem Verständnis für den Markt selbst.',lead:'Dazu gehören:',items:['Positionierung','Markteintrittsstrategie','Plattformen','Zielgruppen','Partnerschaften','kommerzielle Möglichkeiten','lokaler Kontext']},right:{title:'Umsetzung',body:'Sichtbar wird die Strategie erst durch die Umsetzung.',lead:'Dazu gehören:',items:['Creative Direction','Content','Video','Editing','Produktion','Lokalisierung','Kampagnenumsetzung']},line:'NATIVE verbindet beides von Anfang an.'},
founders:{eyebrow:'GRÜNDER',title:'Zwei Perspektiven. Ein gemeinsamer Ansatz.',people:[{name:'Daniel Nonn',role:'Strategy & Partnerships',body:'Daniel verantwortet den strategischen Teil von NATIVE mit Fokus auf Business Development, Partnerschaften und Cross-Market-Positionierung.',body2:'Seine Aufgabe ist es, das Geschäft hinter dem Content zu verstehen: Wo entstehen Chancen? Wie sollte ein neuer Markt erschlossen werden? Und welche Beziehungen helfen Creatorn oder Marken dabei, dort eine relevante Präsenz aufzubauen?',lead:'Schwerpunkte:',items:['Strategie','Business Development','Partnerschaften','Market Entry','Cross-Market-Positionierung','Creator- und Brand-Relations']},{name:'Timm',role:'Creative & Production',body:'Timm verantwortet Creative Direction, Produktion, Video und Content Execution.',body2:'Seine Aufgabe ist es, Strategie in Content zu übersetzen, den Menschen tatsächlich sehen wollen – von Social-first-Formaten bis zu Kampagnen und Produktionen.',lead:'Schwerpunkte:',items:['Creative Direction','Produktion','Video','Content Execution','Editing','Visual Storytelling']}],line:'Klare Verantwortlichkeiten. Gemeinsame Entscheidungen dort, wo Strategie und Kreativität zusammenkommen.'},
network:{eyebrow:'NETZWERK & MARKTZUGANG',title:'Über Jahre gewachsene Verbindungen. Lokales Verständnis aus erster Hand.',paras:['NATIVE verbindet strategische und kreative Arbeit mit gewachsenen Beziehungen, direktem Marktzugang und echter Cross-Market-Erfahrung zwischen Europa und China.','Diese Verbindungen entstehen nicht erst für einzelne Projekte. Sie basieren auf jahrelanger Zusammenarbeit, direktem Austausch und echter Erfahrung in beiden Märkten.','Gerade in China werden Sprache, Plattformkultur, Content, Partnerschaften und Marktmechaniken nicht von außen interpretiert, sondern gemeinsam mit Menschen entwickelt und geprüft, die den Markt aus eigener Erfahrung kennen.','So entsteht Zugang zu Kontext, Perspektiven und Beziehungen, die sich nicht kurzfristig aufbauen lassen.'],statement:'NATIVE verbindet nicht nur Märkte. Wir arbeiten aus bestehenden Beziehungen zwischen ihnen heraus.'},
knowledge:{title:'Lokales Verständnis lässt sich nicht vortäuschen.',paras:['Eine Übersetzung kann grammatikalisch korrekt sein und sich trotzdem falsch anfühlen.','Eine Kampagne kann hervorragend aussehen und trotzdem an der Zielgruppe vorbeigehen.','Eine Plattformstrategie kann global sinnvoll wirken und lokal trotzdem scheitern.','Deshalb behandelt NATIVE Native-Language- und Local-Market-Know-how nicht als letzten Korrekturschritt, sondern als Teil des gesamten Prozesses.'],lead:'Je nach Markt können lokale Spezialisten eingebunden werden bei:',items:['Sprache','kultureller Prüfung','Plattformverhalten','Trends','Creator-Auswahl','Community-Erwartungen','Kampagnenideen','finaler Qualitätskontrolle'],closing:'Das Ziel ist einfach: Nicht nur korrekt. Relevant.'},
markets:{title:'Zwischen Europa und China aufgebaut. Für weitere Märkte gedacht.',paras:['Europa und China bilden den ersten großen Korridor für NATIVE, weil die Distanz zwischen beiden Märkten weit über Geografie hinausgeht.','Plattformen, Kommunikationskultur, Content-Verhalten, Markenerwartungen und Creator-Ökosysteme unterscheiden sich deutlich.','Daraus entstehen Herausforderungen – und Chancen.'],lead:'NATIVE arbeitet in beide Richtungen:',fromEurope:'Europa → China',fromEuropeBody:'Wir helfen Creatorn und Marken beim Zugang zu chinesischen Plattformen, Zielgruppen und Partnerschaften.',fromChina:'China → Europa',fromChinaBody:'Wir helfen chinesischen Creatorn und Marken dabei, Kommunikation, Content und Partnerschaften an europäische Märkte anzupassen.',line:'Das ist der Ausgangspunkt – nicht die Grenze.'},
direction:{eyebrow:'AUSBLICK',title:'Ein Cross-Market-Unternehmen über einen einzelnen Korridor hinaus.',paras:['NATIVE startet zwischen Europa und China, doch die zugrunde liegende Herausforderung existiert weltweit.','Creator möchten neue Zielgruppen erreichen. Marken möchten neue Märkte erschließen. Kultur verändert, wie beide verstanden werden.','Langfristig soll NATIVE zu einem Netzwerk wachsen, das Strategie, kreative Umsetzung und lokales Marktwissen über verschiedene Regionen hinweg verbindet.'],closing:['Nicht, indem wir so tun, als wären alle Märkte gleich.','Sondern indem dort lokale Kompetenz aufgebaut wird, wo sie benötigt wird.']},
final:{title:'Unterschiedliche Märkte. Ein Prinzip: Relevanz.',body:'Wenn du etwas aufbaust, das über kulturelle Grenzen hinweg funktionieren soll, sollten wir miteinander sprechen.',cta:'Gespräch starten'}},
zh:{
seo:{title:'关于 NATIVE',description:'了解 NATIVE 为什么将跨文化策略、本地化、内容制作与当地专业能力连接起来。'},
hero:{eyebrow:'关于 NATIVE',title:'让市场之间的距离，变得更小。',body:'NATIVE 是一家专注于跨文化媒体、本地化与内容制作的公司，帮助创作者与品牌进入新的市场，同时保留原本让他们具有辨识度与价值的核心身份。',primary:'联系我们',secondary:'了解我们的服务'},
why:{title:'因为翻译，只是开始。',body:'品牌与创作者越来越频繁地跨市场沟通，但内容并不会因为换了一种语言，就自动具有本地相关性。',lead:'进入新的市场，可能意味着：',items:['不同的平台','不同的文化语境','不同的受众期待','不同的叙事方式','不同的视觉语言','不同的创作者生态','不同的消费行为','不同的沟通习惯'],closing:'NATIVE 的存在，就是为了连接这些差异。',closing2:'我们把策略、本地化、内容制作与合作资源结合起来，让内容进入新的市场时，不会显得像一个外来的版本。'},
principle:{eyebrow:'我们的原则',title:'Make your brand feel local.',paras:['对于 NATIVE 来说，“本地化”并不是让品牌或创作者假装来自另一个市场。','真正的本地化，是理解当地的人如何沟通、观看内容、做出购买决定、产生反应并建立信任。','品牌身份应该保持清晰。','表达方式则可以根据市场进行调整。'],lead:'这可能包括：',items:['语言','语气','内容形式','平台','创作者','内容制作','品牌活动创意','叙事方式','当地合作伙伴'],closing:['目标不是隐藏品牌来自哪里。','而是让当地受众理解，为什么这个品牌适合出现在这里。']},
disciplines:{title:'策略与执行，不应该存在于两个不同的世界。',left:{title:'策略',body:'进入新的市场，首先需要真正理解这个市场。',lead:'包括：',items:['定位','市场进入策略','平台','受众','合作资源','商业机会','当地语境']},right:{title:'创意与执行',body:'策略只有通过真正的执行，才会变得可见。',lead:'包括：',items:['创意指导','内容','视频','剪辑','制作','本地化','品牌活动执行']},line:'NATIVE 从一开始，就把两者放在一起。'},
founders:{eyebrow:'创始人',title:'两种视角，同一个工作方式。',people:[{name:'Daniel Nonn',role:'Strategy & Partnerships',body:'Daniel 负责 NATIVE 的市场策略、商务拓展、合作关系与跨市场定位。',body2:'他的重点，是理解内容背后的商业逻辑：机会在哪里？应该如何进入新的市场？哪些合作关系能够帮助品牌或创作者建立真正有价值的本地影响力？',lead:'主要领域：',items:['市场策略','商务拓展','合作伙伴关系','市场进入','跨市场定位','创作者与品牌关系']},{name:'Timm',role:'Creative & Production',body:'Timm 负责创意指导、内容制作、视频与执行。',body2:'他的重点，是把策略转化为真正值得观看的内容，从 Social-first 内容形式到品牌活动与完整制作项目。',lead:'主要领域：',items:['创意指导','内容制作','视频','内容执行','剪辑','视觉叙事']}],line:'明确的职责分工。在策略与创意交汇的地方，共同做决定。'},
network:{eyebrow:'关系网络与市场连接',title:'建立在真实关系之上，而不只是市场研究。',paras:['NATIVE 将策略与创意执行，与长期积累的欧洲和中国市场关系、直接市场连接以及真实的跨市场经验结合在一起。','这些联系并不是为了某一个项目临时建立的，而是来自多年合作、直接交流与真实的跨市场实践。','尤其在中国市场，语言、平台文化、内容、合作关系与市场逻辑，都不是从外部进行判断，而是与真正了解当地市场的人共同完成。','这种长期积累，让 NATIVE 能够获得短时间内无法建立的市场语境、视角与关系资源。'],statement:'NATIVE 不只是连接不同市场，而是在已经存在的真实关系基础上开展工作。'},
knowledge:{title:'真正的本地理解，无法伪装。',paras:['一句话可以在语法上完全正确，却依然让当地人觉得不自然。','一个品牌活动可以非常漂亮，却依然无法打动当地受众。','一个全球层面合理的平台策略，也可能在本地市场失败。','因此，NATIVE 不把母语与当地市场知识当作最后一步的校对，而是把它们放进整个工作流程。'],lead:'根据市场情况，当地专家可以参与：',items:['语言','文化审核','平台使用习惯','趋势','创作者选择','社区期待','活动创意','最终质量检查'],closing:'目标很简单：不只是正确，而是真正相关。'},
markets:{title:'从欧洲与中国之间出发，为更多市场而设计。',paras:['欧洲与中国，是 NATIVE 最初重点连接的两个市场。','因为两个市场之间的距离，远不只是地理上的距离。','平台、传播文化、内容消费方式、品牌期待与创作者生态都有明显差异。','这些差异既带来挑战，也带来机会。'],lead:'NATIVE 从一开始就为双向合作而设计：',fromEurope:'欧洲 → 中国',fromEuropeBody:'帮助欧洲创作者与品牌进入中国的平台、受众与合作生态。',fromChina:'中国 → 欧洲',fromChinaBody:'帮助中国创作者与品牌调整沟通、内容与合作方式，更自然地进入欧洲市场。',line:'这是起点，而不是边界。'},
direction:{eyebrow:'未来方向',title:'从一条跨市场连接，发展为更广泛的国际网络。',paras:['NATIVE 从欧洲与中国之间开始，但背后的问题存在于全球。','创作者希望接触新的受众。品牌希望进入新的市场。文化会改变人们理解两者的方式。','长期方向，是把 NATIVE 建立成一个连接市场策略、创意执行与本地专业知识的跨区域网络。'],closing:['不是假设每一个市场都一样。','而是在项目真正进入哪里，就在那里建立正确的本地能力。']},
final:{title:'不同的市场，同一个原则：真正的相关性。',body:'如果你正在打造一个需要跨文化沟通的品牌、内容或项目，我们可以聊聊。',cta:'联系我们'}}};
