import type {Locale} from './i18n';

export type BrandBlock={title:string;body:string;lead:string;items:string[];closing:string};
type BrandsCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};problem:{title:string;body:string;closing:string};pillars:{title:string;items:Array<[string,string]>};positioning:{left:BrandBlock;right:BrandBlock};campaigns:BrandBlock;production:BrandBlock;entry:BrandBlock;teams:BrandBlock;markets:{title:string;body:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};case:{eyebrow:string;title:string;body:string;label:string};final:{title:string;body:string;cta:string}};

export const brandsCopy:Record<Locale,BrandsCopy>={
en:{
seo:{title:'For Brands | NATIVE',description:'Enter new markets with locally relevant positioning, content, campaigns, production and partnerships while preserving your brand identity.'},
hero:{eyebrow:'FOR BRANDS',title:'Enter new markets without feeling foreign.',body:'NATIVE helps brands become relevant in new markets by adapting positioning, content, campaigns and partnerships to the local context — without losing what made the brand recognizable in the first place.',primary:'Start a conversation',secondary:'Explore our services'},
problem:{title:'Successful marketing cannot simply be carried into a new market.',body:'What works in one place can quickly feel distant, translated or simply out of place somewhere else.\n\nLanguage is only part of it. Visual language, platforms, creators, storytelling, campaign formats and audience expectations all change from market to market.',closing:'That is why NATIVE adapts the full communication context, not just the words.'},
pillars:{title:'From strategy to execution.',items:[['Market Entry','We assess the market, audience and platforms, sharpen the positioning and build the right way in.'],['Localization','We adapt language, messaging, visual language, storytelling and content to the local market.'],['Platform Management','We support account setup, publishing, optimization, reporting and the ongoing development of the local presence.'],['Production','We develop and produce content, campaigns and formats specifically for the market.'],['Talent & Partnerships','We connect brands with the right creators, talent, partners and local relationships.']]},
positioning:{left:{title:'Keep the brand. Change the context.',body:'Localization does not mean reinventing the brand.',lead:'We first define what needs to stay consistent:',items:['brand identity','core values','product strengths','tone','visual recognition'],closing:'Then we adapt what needs to change:|language|cultural references|campaign ideas|visual language|creators|platforms|storytelling|local expectations'},right:{title:'The brand should feel familiar, not foreign.',body:'Good localization should not feel like a translated campaign.',lead:'It should feel as though the brand understands the market.\n\nThat can mean changing:',items:['the campaign hook','the creator','the location','the format','the visual language','the platform strategy','the story around the product'],closing:'The product can stay the same. The way people experience it may need to change.'}},
campaigns:{title:'Local relevance often comes from the right people.',body:'Creators, hosts, experts and local partners can give a brand more credibility and proximity in a new market.',lead:'NATIVE can support:',items:['creator selection','campaign matching','collaboration concepts','outreach and coordination','briefing and production','local campaign execution','cross-market creator partnerships','long-term brand relationships'],closing:'The goal is not simply to buy reach. It is to build credible relevance in the market.'},
production:{title:'Some campaigns should not be adapted. They should be rethought locally.',body:'When existing global assets are not enough, NATIVE develops and produces content specifically for the target market.',lead:'Possible formats:',items:['social-first video','short-form campaigns','product films','creator campaigns','interviews','event content','local brand films','launch content','UGC-style productions','campaign photography'],closing:'Creative direction, casting, location, production and storytelling are built around the local audience.'},
entry:{title:'A good market entry does not start with maximum visibility.',body:'Before a brand launches, we first look at where the real potential is and what kind of entry makes sense.',lead:'That can include questions such as:',items:['Which platform fits the brand?','Which audience should come first?','Which products should lead?','What needs to be localized?','What can be reused from existing content?','Should the brand launch directly or test first?','Which creators or partners can build trust?','Which formats should be produced locally?'],closing:'The goal is a focused market entry, not being everywhere at once.'},
teams:{title:'NATIVE does not need to replace your existing agency.',body:'Many brands already have strong internal teams, global agencies or local marketing partners.\n\nNATIVE can step in where cross-market expertise, localization, production or local market knowledge is missing.',lead:'Possible roles:',items:['strategy partner','localization partner','production partner','creator partnership partner','platform specialist','local market coordinator','cross-cultural advisor'],closing:'The right role depends on what is already working inside the brand.'},
markets:{title:'Between Europe and China. Built to go further.',body:'Our first focus connects two markets that differ significantly in platforms, communication culture and audience expectations.',fromEurope:'Europe → China',fromEuropeBody:'We help European brands adapt positioning, content, platforms and partnerships for Chinese audiences.',fromChina:'China → Europe',fromChinaBody:'We help Chinese brands turn strong products and existing marketing into communication that feels natural and relevant to European customers.',line:'The principle applies wherever culture changes the way a brand is understood.'},
case:{eyebrow:'BRAND CASES',title:'Real work first. Case study second.',body:'Our first cross-market brand cases are currently being developed. This is where we will show how strategy, localization, production, partnerships and market execution work together in real projects.',label:'First brand case coming soon.'},
final:{title:'A new market is an opportunity, not a translation exercise.',body:'If your brand is considering a new market, we start with what is already there: positioning, content, structures and existing opportunities.',cta:'Start a conversation'}},
de:{
seo:{title:'Für Marken | NATIVE',description:'Erschließe neue Märkte mit lokal relevanter Positionierung, Content, Kampagnen, Produktion und Partnerschaften – ohne die Markenidentität zu verlieren.'},
hero:{eyebrow:'FÜR MARKEN',title:'Erschließe neue Märkte, ohne fremd zu wirken.',body:'NATIVE hilft Marken dabei, in neuen Märkten relevant zu werden. Wir passen Positionierung, Content, Kampagnen und Partnerschaften an den jeweiligen Markt an – ohne zu verlieren, was die Marke ursprünglich ausmacht.',primary:'Gespräch starten',secondary:'Leistungen entdecken'},
problem:{title:'Erfolgreiches Marketing lässt sich nicht einfach in einen neuen Markt übertragen.',body:'Was an einem Ort funktioniert, kann anderswo schnell fremd, übersetzt oder schlicht unpassend wirken.\n\nSprache ist dabei nur ein Teil. Bildsprache, Plattformen, Creator, Storytelling, Kampagnenformate und die Erwartungen der Zielgruppe verändern sich von Markt zu Markt.',closing:'NATIVE passt deshalb nicht nur Texte an, sondern den gesamten Kontext der Kommunikation.'},
pillars:{title:'Von der Strategie bis zur Umsetzung.',items:[['Market Entry','Wir prüfen Markt, Zielgruppe und Plattformen, schärfen die Positionierung und entwickeln einen sinnvollen Markteintritt.'],['Localization','Wir passen Sprache, Botschaften, Bildsprache, Storytelling und Content an den jeweiligen Markt an.'],['Platform Management','Wir unterstützen bei Accountaufbau, Publishing, Optimierung, Reporting und der laufenden Weiterentwicklung der lokalen Präsenz.'],['Production','Wir entwickeln und produzieren Content, Kampagnen und Formate gezielt für den jeweiligen Markt.'],['Talent & Partnerships','Wir verbinden Marken mit passenden Creatorn, Talents, Partnern und relevanten Kontakten vor Ort.']]},
positioning:{left:{title:'Die Marke bleibt. Der Kontext verändert sich.',body:'Lokalisierung bedeutet nicht, eine Marke neu zu erfinden.',lead:'Wir definieren zuerst, was erhalten bleiben muss:',items:['Markenidentität','Kernwerte','Produktstärken','Tonalität','Wiedererkennbarkeit'],closing:'Danach passen wir an, was sich verändern sollte:|Sprache|kulturelle Referenzen|Kampagnenideen|Bildsprache|Creator|Plattformen|Storytelling|lokale Erwartungen'},right:{title:'Die Marke soll vertraut wirken, nicht fremd.',body:'Gute Lokalisierung fühlt sich nicht wie eine übersetzte Kampagne an.',lead:'Sie vermittelt, dass die Marke den Markt versteht.\n\nDas kann bedeuten, Folgendes zu verändern:',items:['Kampagnen-Hook','Creator','Location','Format','Bildsprache','Plattformstrategie','Story rund um das Produkt'],closing:'Das Produkt kann gleich bleiben. Wie Menschen es erleben, muss sich vielleicht verändern.'}},
campaigns:{title:'Lokale Relevanz entsteht oft durch die richtigen Menschen.',body:'Creator, Hosts, Experten und lokale Partner können einer Marke in einem neuen Markt Glaubwürdigkeit und Nähe geben.',lead:'NATIVE unterstützt bei:',items:['Creator-Auswahl','Kampagnen-Matching','Kooperationskonzepten','Ansprache und Koordination','Briefing und Produktion','lokaler Kampagnenumsetzung','Cross-Market-Creator-Partnerschaften','langfristigen Markenbeziehungen'],closing:'Das Ziel ist nicht einfach Reichweite einzukaufen, sondern glaubwürdige Relevanz vor Ort aufzubauen.'},
production:{title:'Manche Kampagnen sollten nicht angepasst, sondern vor Ort neu gedacht werden.',body:'Wenn bestehende globale Assets nicht ausreichen, entwickelt und produziert NATIVE Content gezielt für den jeweiligen Markt.',lead:'Mögliche Formate:',items:['Social-first Video','Short-Form-Kampagnen','Produktfilme','Creator-Kampagnen','Interviews','Event Content','lokale Brand-Filme','Launch Content','UGC-orientierte Produktionen','Kampagnenfotografie'],closing:'Creative Direction, Casting, Location, Produktion und Storytelling orientieren sich dabei an der Zielgruppe vor Ort.'},
entry:{title:'Ein guter Markteintritt beginnt nicht mit maximaler Sichtbarkeit.',body:'Bevor eine Marke startet, schauen wir zuerst darauf, wo tatsächlich Potenzial liegt und welche Form des Einstiegs sinnvoll ist.',lead:'Dabei geht es zum Beispiel um Fragen wie:',items:['Welche Plattform passt zur Marke?','Welche Zielgruppe sollte zuerst angesprochen werden?','Welche Produkte sollten im Mittelpunkt stehen?','Was muss lokalisiert werden?','Was kann aus bestehendem Content weitergenutzt werden?','Sollte die Marke direkt starten oder zunächst testen?','Welche Creator oder Partner können Vertrauen schaffen?','Welche Formate sollten vor Ort produziert werden?'],closing:'Ziel ist ein fokussierter Markteintritt – nicht gleichzeitig überall präsent zu sein.'},
teams:{title:'NATIVE muss deine bestehende Agentur nicht ersetzen.',body:'Viele Marken haben bereits starke interne Teams, globale Agenturen oder lokale Marketingpartner.\n\nNATIVE kann genau dort ergänzen, wo Cross-Market-Know-how, Lokalisierung, Produktion oder lokale Marktkenntnis fehlen.',lead:'Mögliche Rollen:',items:['Strategiepartner','Localization-Partner','Produktionspartner','Creator-Partnership-Partner','Plattform-Spezialist','lokaler Marktkoordinator','Cross-Cultural Advisor'],closing:'Welche Rolle sinnvoll ist, hängt davon ab, was innerhalb der Marke bereits gut funktioniert.'},
markets:{title:'Zwischen Europa und China. Von hier aus weiter gedacht.',body:'Unser erster Fokus verbindet zwei Märkte, die sich bei Plattformen, Kommunikationskultur und Kundenerwartungen deutlich unterscheiden.',fromEurope:'Europa → China',fromEuropeBody:'Wir helfen europäischen Marken dabei, Positionierung, Content, Plattformen und Partnerschaften an chinesische Zielgruppen anzupassen.',fromChina:'China → Europa',fromChinaBody:'Wir helfen chinesischen Marken dabei, starke Produkte und bestehendes Marketing so weiterzuentwickeln, dass die Kommunikation für europäische Kunden natürlich und relevant wirkt.',line:'Das Prinzip funktioniert überall dort, wo Kultur verändert, wie eine Marke wahrgenommen wird.'},
case:{eyebrow:'BRAND CASES',title:'Erst echte Arbeit. Dann die Case Study.',body:'Unsere ersten Cross-Market-Brand-Cases entstehen aktuell. Künftig zeigen wir hier, wie Strategie, Lokalisierung, Produktion, Partnerschaften und Marktumsetzung in realen Projekten zusammenwirken.',label:'Erster Brand Case folgt.'},
final:{title:'Ein neuer Markt ist eine Chance – keine Übersetzungsaufgabe.',body:'Wenn deine Marke über einen neuen Markt nachdenkt, starten wir mit dem, was bereits da ist: Positionierung, Content, Strukturen und vorhandene Chancen.',cta:'Gespräch starten'}},
zh:{
seo:{title:'面向品牌 | NATIVE',description:'通过本地品牌定位、内容、传播活动、制作与合作，帮助品牌进入新市场，同时保留原有身份。'},
hero:{eyebrow:'面向品牌',title:'进入新的市场，也让品牌自然融入当地。',body:'NATIVE 帮助品牌根据不同市场调整定位、内容、品牌活动与合作方式，让品牌在当地被真正理解，同时保留原本最有辨识度的部分。',primary:'联系我们',secondary:'了解我们的服务'},
problem:{title:'一个市场有效的营销方式，到了另一个市场未必依然成立。',body:'品牌进入新的市场时，真正需要调整的往往不只是语言。\n\n视觉表达、平台选择、创作者、叙事方式、品牌活动形式以及受众期待，都可能发生变化。',closing:'所以，NATIVE 不只是翻译内容，而是重新理解整个传播语境。'},
pillars:{title:'从策略到落地，一起完成。',items:[['Market Entry','我们分析市场、受众与平台，明确品牌定位，并规划合适的进入方式。'],['Localization','我们根据当地市场调整语言、品牌信息、视觉表达、叙事方式与内容。'],['Platform Management','我们支持账号搭建、内容发布、优化、数据分析以及当地平台的持续运营。'],['Production','我们针对目标市场开发并制作内容、品牌活动与本地化素材。'],['Talent & Partnerships','我们连接品牌与合适的创作者、人才、合作伙伴以及当地资源。']]},
positioning:{left:{title:'品牌不需要改变自己，只需要换一种适合当地的表达方式。',body:'本地化不是重新定义品牌。',lead:'我们先明确哪些部分必须保留：',items:['品牌身份','核心价值','产品优势','品牌语气','视觉识别'],closing:'再调整真正需要变化的部分：|语言表达|文化语境|品牌活动创意|视觉语言|创作者选择|平台策略|叙事方式|当地受众期待'},right:{title:'让品牌看起来自然，而不是像一个外来的版本。',body:'好的本地化，不应该让人感觉这是一场被翻译过来的海外品牌活动。',lead:'而应该让受众觉得，这个品牌真正理解当地市场。\n\n这可能意味着调整：',items:['核心创意','创作者','拍摄地点','内容形式','视觉语言','平台策略','产品故事'],closing:'产品本身可以不变，但受众感知它的方式可能需要改变。'}},
campaigns:{title:'真正的本地相关性，往往来自合适的人。',body:'当地创作者、主持人、专家与合作伙伴，可以帮助品牌更快建立信任与真实感。',lead:'NATIVE 可以支持：',items:['创作者筛选','品牌与创作者匹配','合作创意','商务沟通与协调','Briefing 与内容制作','当地品牌活动执行','跨市场创作者合作','长期品牌合作关系'],closing:'目标不是单纯购买曝光，而是在当地建立真正可信的品牌相关性。'},
production:{title:'有些内容不应该只是改编，而应该直接为当地市场重新创作。',body:'当现有的全球素材不足以支撑当地市场时，NATIVE 会针对目标受众开发并制作新的内容。',lead:'可能包括：',items:['Social-first 视频','短视频品牌活动','产品影片','创作者合作内容','采访','活动内容','本地品牌影片','新品发布内容','UGC 风格内容','品牌活动摄影'],closing:'创意方向、选角、场地、制作与叙事方式都会围绕当地受众进行设计。'},
entry:{title:'好的市场进入，不是先追求最大曝光。',body:'在正式进入市场之前，我们会先判断品牌真正具备潜力的方向，以及什么样的进入方式最合理。',lead:'可能包括：',items:['哪个平台最适合品牌？','哪类受众应该优先？','哪些产品应该率先进入？','哪些内容需要本地化？','哪些现有素材可以继续利用？','应该直接正式上线，还是先做测试？','哪些创作者或合作伙伴可以帮助品牌更快建立信任？','哪些内容应该在当地重新制作？'],closing:'目标是有重点地进入市场，而不是一开始就在所有渠道同时出现。'},
teams:{title:'NATIVE 不需要取代你现有的代理商或市场团队。',body:'很多品牌已经拥有成熟的内部团队、全球代理商或当地营销伙伴。\n\nNATIVE 可以补充现有团队中缺少的跨市场经验、本地化能力、内容制作或当地市场理解。',lead:'可能的角色包括：',items:['市场策略伙伴','Localization Partner','Production Partner','Creator Partnership Partner','平台专家','当地市场协调者','Cross-Cultural Advisor'],closing:'具体角色取决于品牌已经具备的能力，以及真正缺少的部分。'},
markets:{title:'连接欧洲与中国，也为更多市场留出空间。',body:'我们的第一个重点，是连接两个在平台、传播文化与消费者期待上差异明显的市场。',fromEurope:'欧洲 → 中国',fromEuropeBody:'我们帮助欧洲品牌调整定位、内容、平台策略与合作方式，更自然地进入中国市场。',fromChina:'中国 → 欧洲',fromChinaBody:'我们帮助中国品牌把优秀的产品与现有营销，转化为更符合欧洲消费者习惯的品牌表达。',line:'只要文化会影响品牌被理解的方式，这套方法就可以延伸到更多市场。'},
case:{eyebrow:'品牌案例',title:'先做真实项目，再谈成功案例。',body:'我们的第一批跨市场品牌案例正在推进中。未来这里会展示策略、本地化、内容制作、合作关系与市场执行如何在真实项目中共同发挥作用。',label:'首个品牌案例即将上线'},
final:{title:'进入新的市场，应该是机会，而不是翻译任务。',body:'如果你的品牌正在考虑进入新的市场，我们可以先从现有定位、内容、资源与机会开始。',cta:'联系我们'}}};
