import type {Locale} from './i18n';

export type BrandBlock={title:string;body:string;lead:string;items:string[];closing:string};
type BrandsCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};problem:{title:string;body:string;closing:string};pillars:{title:string;items:Array<[string,string]>};positioning:{left:BrandBlock;right:BrandBlock};campaigns:BrandBlock;production:BrandBlock;entry:BrandBlock;teams:BrandBlock;markets:{title:string;body:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};case:{eyebrow:string;title:string;body:string;label:string};final:{title:string;body:string;cta:string}};

export const brandsCopy:Record<Locale,BrandsCopy>={
en:{
seo:{title:'For Brands | NATIVE',description:'Enter new markets with locally relevant positioning, content, campaigns, production and partnerships while preserving your brand identity.'},
hero:{eyebrow:'FOR BRANDS',title:'Enter new markets without looking imported.',body:'NATIVE helps brands adapt positioning, content, campaigns and partnerships for new markets. We make sure your brand feels relevant locally without losing the identity that made it recognizable in the first place.',primary:'Start a conversation',secondary:'Explore our services'},
problem:{title:'A successful brand cannot simply export its marketing.',body:'What works in one market can feel distant, overly translated or culturally misplaced in another. Brand language, visual codes, creators, platforms, storytelling, campaign formats and customer expectations all change.',closing:'NATIVE helps brands adapt the full communication context — not just the words.'},
pillars:{title:'One partner for strategy, adaptation and execution.',items:[['Market Entry','Market assessment, positioning, platform strategy and launch planning.'],['Localization','We adapt language, messaging, visual codes, storytelling and content to the local market.'],['Platform Management','We support local account setup, publishing, optimization, reporting and ongoing development.'],['Production','We develop and produce local content, campaigns, social assets and brand formats.'],['Talent & Partnerships','Creator partnerships, local collaborators, campaign talent and cross-market connections.']]},
positioning:{left:{title:'Keep the brand. Change the context.',body:'Localization is not about making a brand look different for the sake of it.',lead:'We first identify what should remain consistent:',items:['brand identity','core values','product strengths','tone and personality','visual recognition'],closing:'Then we adapt what needs to change:|wording|cultural references|campaign ideas|visual codes|creators|platforms|storytelling|local expectations'},right:{title:'Make the brand feel expected, not foreign.',body:'The strongest local execution does not feel like a translated foreign campaign.',lead:'It feels like the brand understands the market. That can mean changing:',items:['the campaign hook','the creator','the location','the format','the visual language','the platform strategy','the story around the product'],closing:'The product can stay the same. The way people experience it may need to change.'}},
campaigns:{title:'Local relevance often needs local people.',body:'Creators, hosts, experts and local partners can make a brand more credible in a new market.',lead:'NATIVE can support:',items:['creator identification','campaign matching','collaboration concepts','outreach and coordination','briefing and production','local campaign execution','cross-market creator partnerships','long-term brand relationships'],closing:'The goal is not simply to buy reach. The goal is to create credible local relevance.'},
production:{title:'Some campaigns should not be adapted. They should be made locally.',body:'When existing global assets are not enough, NATIVE develops and produces content specifically for the target market.',lead:'Possible formats:',items:['social-first video','short-form campaigns','product films','creator campaigns','interviews','event content','local brand films','launch content','UGC-style productions','campaign photography'],closing:'Creative direction, casting, location, production and storytelling are developed around the target audience.'},
entry:{title:'The right market entry is not always the loudest one.',body:'Before launching, we look at where the brand actually has potential and what type of entry makes sense.',lead:'Possible questions include:',items:['Which platform fits the brand?','Which audience should be prioritized?','Which products should lead?','What should be localized first?','Should the brand launch directly or test with selected content?','Which creators or partners can accelerate trust?','Which formats should be produced locally?','What can be reused from the existing brand library?'],closing:'The goal is a focused, realistic market-entry plan instead of launching everywhere at once.'},
teams:{title:'NATIVE does not need to replace your existing agency.',body:'Many brands already have strong internal teams, global agencies or local marketing partners. NATIVE can work as a specialized cross-market layer between them.',lead:'Possible roles:',items:['local strategy partner','localization partner','production partner','creator partnership partner','platform specialist','local market coordinator','cross-cultural advisor'],closing:'The exact role depends on what is already working inside the brand.'},
markets:{title:'Built between Europe and China. Designed to travel further.',body:'Our initial focus connects two markets with very different communication cultures, platforms and consumer expectations.',fromEurope:'Europe → China',fromEuropeBody:'We help European brands adapt positioning, content, platforms and partnerships for Chinese audiences.',fromChina:'China → Europe',fromChinaBody:'We help Chinese brands turn strong products and existing marketing into communication that feels natural to European customers.',line:'The principle extends beyond these markets wherever culture changes the way a brand is understood.'},
case:{eyebrow:'BRAND CASES',title:'Real work before case-study claims.',body:'Our first cross-market brand cases are being developed. Future case studies will document strategy, localization, production, partnerships and market execution based on real projects.',label:'First brand case coming soon.'},
final:{title:'A new market should feel like an opportunity, not a translation exercise.',body:'If your brand is considering entering a new market, we can start with positioning, existing content and the opportunities that already exist.',cta:'Start a conversation'}},
de:{
seo:{title:'Für Marken | NATIVE',description:'Erschließe neue Märkte mit lokal relevanter Positionierung, Content, Kampagnen, Produktion und Partnerschaften – ohne die Markenidentität zu verlieren.'},
hero:{eyebrow:'FÜR MARKEN',title:'Erschließe neue Märkte, ohne fremd zu wirken.',body:'NATIVE hilft Marken dabei, Positionierung, Content, Kampagnen und Partnerschaften an neue Märkte anzupassen. Dabei sorgen wir dafür, dass die Marke lokal relevant wird, ohne ihre ursprüngliche Identität zu verlieren.',primary:'Gespräch starten',secondary:'Leistungen entdecken'},
problem:{title:'Erfolgreiches Marketing lässt sich nicht einfach exportieren.',body:'Was in einem Markt funktioniert, kann in einem anderen distanziert, übersetzt oder kulturell unpassend wirken. Sprache, Bildwelt, Creator, Plattformen, Storytelling, Kampagnenformate und Erwartungen der Zielgruppe verändern sich.',closing:'NATIVE passt den gesamten Kommunikationskontext an – nicht nur die Sprache.'},
pillars:{title:'Ein Partner für Strategie, Anpassung und Umsetzung.',items:[['Market Entry','Marktanalyse, Positionierung, Plattformstrategie und Launch-Planung.'],['Localization','Wir passen Sprache, Botschaften, Bildsprache, Storytelling und Content an den lokalen Markt an.'],['Platform Management','Wir unterstützen bei lokalem Accountaufbau, Publishing, Optimierung, Reporting und laufender Weiterentwicklung.'],['Production','Wir entwickeln und produzieren lokale Inhalte, Kampagnen, Social Assets und Brand-Formate.'],['Talent & Partnerships','Creator-Partnerschaften, lokale Kooperationspartner, Kampagnen-Talents und Cross-Market-Verbindungen.']]},
positioning:{left:{title:'Die Marke bleibt. Der Kontext verändert sich.',body:'Lokalisierung bedeutet nicht, eine Marke unnötig zu verändern.',lead:'Wir definieren zuerst, was erhalten bleiben soll:',items:['Markenidentität','Kernwerte','Produktstärken','Tonalität und Persönlichkeit','visuelle Wiedererkennbarkeit'],closing:'Danach passen wir an, was sich verändern muss:|Sprache|kulturelle Referenzen|Kampagnenideen|Bildsprache|Creator|Plattformen|Storytelling|lokale Erwartungen'},right:{title:'Die Marke soll vertraut wirken, nicht fremd.',body:'Die stärkste lokale Umsetzung fühlt sich nicht wie eine übersetzte ausländische Kampagne an.',lead:'Sie vermittelt, dass die Marke den Markt versteht. Das kann bedeuten, Folgendes zu verändern:',items:['Kampagnen-Hook','Creator','Location','Format','Bildsprache','Plattformstrategie','Story rund um das Produkt'],closing:'Das Produkt kann gleich bleiben. Die Art, wie Menschen es erleben, muss sich vielleicht verändern.'}},
campaigns:{title:'Lokale Relevanz braucht oft lokale Menschen.',body:'Creator, Hosts, Experten und lokale Partner können einer Marke in einem neuen Markt deutlich mehr Glaubwürdigkeit geben.',lead:'NATIVE kann unterstützen bei:',items:['Creator-Auswahl','Kampagnen-Matching','Kooperationskonzepten','Ansprache und Koordination','Briefing und Produktion','lokaler Kampagnenumsetzung','Cross-Market-Creator-Partnerschaften','langfristigen Markenbeziehungen'],closing:'Das Ziel ist nicht einfach Reichweite zu kaufen. Das Ziel ist glaubwürdige lokale Relevanz.'},
production:{title:'Manche Kampagnen sollten nicht angepasst, sondern lokal neu produziert werden.',body:'Wenn bestehende globale Assets nicht ausreichen, entwickelt und produziert NATIVE Content gezielt für den jeweiligen Zielmarkt.',lead:'Mögliche Formate:',items:['Social-first Video','Short-Form-Kampagnen','Produktfilme','Creator-Kampagnen','Interviews','Event-Content','lokale Brand-Filme','Launch-Content','UGC-orientierte Produktionen','Kampagnenfotografie'],closing:'Creative Direction, Casting, Location, Produktion und Storytelling orientieren sich dabei am Zielmarkt.'},
entry:{title:'Der richtige Markteintritt ist nicht immer der lauteste.',body:'Vor dem Launch prüfen wir, wo die Marke tatsächlich Potenzial hat und welche Form des Markteintritts sinnvoll ist.',lead:'Mögliche Fragen:',items:['Welche Plattform passt zur Marke?','Welche Zielgruppe sollte priorisiert werden?','Welche Produkte sollten im Mittelpunkt stehen?','Was muss zuerst lokalisiert werden?','Sollte die Marke direkt launchen oder zunächst mit ausgewählten Inhalten testen?','Welche Creator oder Partner können Vertrauen beschleunigen?','Welche Formate sollten lokal produziert werden?','Was kann aus bestehendem Brand-Content weitergenutzt werden?'],closing:'Ziel ist ein fokussierter, realistischer Markteintritt statt gleichzeitig überall zu starten.'},
teams:{title:'NATIVE muss deine bestehende Agentur nicht ersetzen.',body:'Viele Marken haben bereits starke interne Teams, globale Agenturen oder lokale Marketingpartner. NATIVE kann als spezialisierte Cross-Market-Schnittstelle dazwischen arbeiten.',lead:'Mögliche Rollen:',items:['lokaler Strategiepartner','Localization-Partner','Produktionspartner','Creator-Partnership-Partner','Plattform-Spezialist','lokaler Marktkoordinator','Cross-Cultural Advisor'],closing:'Welche Rolle sinnvoll ist, hängt davon ab, was innerhalb der Marke bereits gut funktioniert.'},
markets:{title:'Zwischen Europa und China aufgebaut. Für weitere Märkte gedacht.',body:'Unser erster Fokus verbindet zwei Märkte mit sehr unterschiedlichen Kommunikationskulturen, Plattformen und Kundenerwartungen.',fromEurope:'Europa → China',fromEuropeBody:'Wir helfen europäischen Marken dabei, Positionierung, Content, Plattformen und Partnerschaften an chinesische Zielgruppen anzupassen.',fromChina:'China → Europa',fromChinaBody:'Wir helfen chinesischen Marken dabei, starke Produkte und bestehendes Marketing in eine Kommunikation zu übersetzen, die sich für europäische Kunden natürlich anfühlt.',line:'Das Prinzip lässt sich auf weitere Märkte übertragen – überall dort, wo Kultur verändert, wie eine Marke wahrgenommen wird.'},
case:{eyebrow:'BRAND CASES',title:'Erst echte Arbeit. Dann die Case Study.',body:'Unsere ersten Cross-Market-Brand-Cases entstehen aktuell. Künftige Case Studies zeigen Strategie, Lokalisierung, Produktion, Partnerschaften und Marktumsetzung anhand realer Projekte.',label:'Erster Brand Case folgt.'},
final:{title:'Ein neuer Markt sollte sich wie eine Chance anfühlen – nicht wie eine Übersetzungsaufgabe.',body:'Wenn deine Marke über einen neuen Markt nachdenkt, können wir mit Positionierung, bestehendem Content und den bereits vorhandenen Chancen starten.',cta:'Gespräch starten'}},
zh:{
seo:{title:'面向品牌 | NATIVE',description:'通过本地品牌定位、内容、传播活动、制作与合作，帮助品牌进入新市场，同时保留原有身份。'},
hero:{eyebrow:'面向品牌',title:'进入新的市场，同时让品牌自然融入当地。',body:'NATIVE 帮助品牌根据新的市场调整定位、内容、传播活动与合作方式。我们的目标，是让品牌真正融入当地，同时保留原本最具识别度的品牌身份。',primary:'联系我们',secondary:'了解我们的服务'},
problem:{title:'成功的品牌营销，不能简单地复制到另一个市场。',body:'在一个市场有效的传播方式，到了另一个市场可能会显得疏离、翻译感过强，甚至不符合当地文化。品牌语言、视觉表达、创作者选择、平台逻辑、叙事方式与消费者期待都会发生变化。',closing:'NATIVE 调整的是完整的传播语境，而不只是语言本身。'},
pillars:{title:'从策略到本地化，再到执行，由一个团队完成。',items:[['Market Entry','市场评估、品牌定位、平台策略与市场进入规划。'],['Localization','我们根据当地市场调整语言、品牌信息、视觉表达、叙事方式与内容。'],['Platform Management','我们支持本地账号搭建、内容发布、优化、数据分析与持续运营。'],['Production','我们开发并制作本地内容、品牌活动、社交媒体素材与品牌内容形式。'],['Talent & Partnerships','创作者合作、本地合作伙伴、品牌活动人才与跨市场资源对接。']]},
positioning:{left:{title:'保留品牌本身，调整它所处的语境。',body:'本地化并不是为了改变品牌而改变。',lead:'我们首先明确哪些核心必须保持一致：',items:['品牌身份','核心价值','产品优势','品牌语气与个性','视觉识别'],closing:'然后调整真正需要变化的部分：|语言表达|文化语境|活动创意|视觉风格|创作者选择|平台策略|叙事方式|当地受众期待'},right:{title:'让品牌显得自然，而不是像一个外来的品牌。',body:'真正优秀的本地传播，不应该像一场被翻译过来的海外广告。',lead:'它应该让受众感觉，这个品牌真正理解当地市场。这可能意味着调整：',items:['活动核心创意','创作者','拍摄地点','内容形式','视觉语言','平台策略','产品故事'],closing:'产品本身可以不变，但受众感知它的方式可能需要改变。'}},
campaigns:{title:'真正的本地相关性，往往需要本地的人来参与。',body:'当地创作者、主持人、专家与合作伙伴，可以显著提升品牌在新市场中的可信度。',lead:'NATIVE 可以支持：',items:['创作者筛选','品牌与创作者匹配','合作创意','商务沟通与协调','Briefing 与内容制作','本地活动执行','跨市场创作者合作','长期品牌关系建立'],closing:'目标不只是购买曝光，而是建立真正可信的本地相关性。'},
production:{title:'有些品牌活动不应该只是被改编，而应该直接在当地重新制作。',body:'当现有的全球素材不足以支撑当地市场时，NATIVE 会针对目标市场开发并制作新的内容。',lead:'可能包括：',items:['社交媒体视频','短视频品牌活动','产品影片','创作者合作内容','采访','活动内容','本地品牌影片','新品发布内容','UGC 风格内容','品牌活动摄影'],closing:'创意方向、选角、场地、制作与叙事方式都会围绕当地受众进行设计。'},
entry:{title:'正确的市场进入方式，并不一定是最声势浩大的那一个。',body:'在正式进入市场之前，我们会先判断品牌真正具备潜力的渠道与方式。',lead:'可能包括：',items:['哪个平台最适合品牌？','哪类受众应该优先？','哪些产品应该率先进入？','哪些内容需要最先本地化？','是否应该直接正式上线，还是先通过部分内容进行测试？','哪些创作者或合作伙伴可以帮助品牌更快建立信任？','哪些内容形式应该在当地制作？','哪些现有品牌素材仍然可以继续利用？'],closing:'目标是制定一个聚焦、现实的市场进入方案，而不是一次性在所有渠道同时铺开。'},
teams:{title:'NATIVE 不需要取代你现有的代理商或市场团队。',body:'很多品牌已经拥有成熟的内部团队、全球代理商或当地市场合作伙伴。 NATIVE 可以作为一个专注于跨市场沟通与执行的专业层，与现有团队协作。',lead:'可能的角色包括：',items:['当地市场策略伙伴','本地化合作伙伴','内容制作伙伴','创作者合作伙伴','平台专家','当地市场协调者','跨文化顾问'],closing:'具体角色取决于品牌内部已经具备的能力。'},
markets:{title:'从欧洲与中国之间出发，为更多市场而设计。',body:'我们的初始重点，是连接两个在传播文化、平台逻辑与消费者期待上非常不同的市场。',fromEurope:'欧洲 → 中国',fromEuropeBody:'我们帮助欧洲品牌调整定位、内容、平台策略与合作方式，更好地进入中国市场。',fromChina:'中国 → 欧洲',fromChinaBody:'我们帮助中国品牌把优秀的产品和现有营销转化为更符合欧洲消费者习惯的品牌表达。',line:'只要文化会影响品牌被理解的方式，这套方法就可以扩展到更多市场。'},
case:{eyebrow:'品牌案例',title:'先有真实项目，再谈成功案例。',body:'我们的第一批跨市场品牌项目正在推进中。未来的案例将基于真实项目展示市场策略、本地化、内容制作、合作伙伴关系与市场执行。',label:'首个品牌案例即将上线。'},
final:{title:'进入新的市场，应该是一次增长机会，而不是一次翻译任务。',body:'如果你的品牌正在考虑进入新的市场，我们可以从品牌定位、现有内容与已经存在的市场机会开始分析。',cta:'联系我们'}}};
