import type {Locale} from './i18n';

type Block={title:string;body:string;lead?:string;items:string[]};
type CreatorsCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};problem:{title:string;body:string;closing:string};pillars:{title:string;items:Array<[string,string]>};content:{existing:Block;fresh:Block};journey:{title:string;items:Array<[string,string]>};platform:Block;production:Block;talent:Block;markets:{title:string;body:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};case:{eyebrow:string;title:string;body:string;label:string};final:{title:string;body:string;cta:string}};

export const creatorsCopy:Record<Locale,CreatorsCopy>={
en:{
seo:{title:'For Creators | NATIVE',description:'Build a credible creator presence in new markets through strategy, localization, platform management, production and partnerships.'},
hero:{eyebrow:'FOR CREATORS',title:'Take your content into new markets — without losing your voice.',body:'NATIVE helps creators build a presence in new markets through strategy, localization, platform management, production and partnerships. We adapt what already works, develop what is missing and make sure your content feels natural to the audience watching it.',primary:'Start a conversation',secondary:'Explore our services'},
problem:{title:'A strong creator identity should travel. The content around it needs to adapt.',body:'What works on Instagram, YouTube or TikTok in one market may not work the same way on Douyin, RED, Bilibili or another local platform. The audience, platform culture, storytelling, pacing, captions, visual language and even the role of the creator can change.',closing:'NATIVE helps translate the identity — not just the words.'},
pillars:{title:'Everything you need to enter a new market.',items:[['Market Entry','We assess the market, audience and platforms, define the right positioning and create a realistic launch strategy.'],['Localization','We adapt language, hooks, captions, storytelling, editing and context so your content makes sense locally.'],['Platform Management','We support account setup, publishing, optimization, reporting and the ongoing development of your local presence.'],['Production','When existing content is not enough, we develop and produce new formats built specifically for the target market.'],['Talent & Partnerships','As your local presence grows, NATIVE can help develop commercial partnerships, market-specific representation and relevant local connections.']]},
content:{existing:{title:'Start with what already works.',body:'Entering a new market does not mean producing everything again from zero.',lead:'We first look at your existing content:',items:['Which formats can travel?','Which topics are relevant locally?','Which videos only need linguistic adaptation?','Which ones need a different hook, edit or context?','Which content should not be used at all?','The goal is to use your existing library intelligently.']},fresh:{title:'Produce what the market actually needs.',body:'Some opportunities require new content.',lead:'That can mean:',items:['new platform-native formats','local collaborations','interviews','travel or event content','local brand campaigns','dedicated productions','new voiceover or storytelling formats','NATIVE can develop and produce these formats together with the creator.']}},
journey:{title:'From first market test to long-term presence.',items:[['Market Assessment','We assess whether the creator, content and audience have realistic potential in the target market.'],['Strategy & Setup','Platform selection, positioning, account setup and the initial content plan.'],['Localization & Launch','Existing content is adapted and the first local publishing phase begins.'],['Learn & Optimize','Performance is analyzed and content strategy evolves based on real audience behavior.'],['Growth & Partnerships','Successful creator presence can evolve into collaborations, campaigns and long-term market representation.']]},
platform:{title:'You create. We help operate the market around it.',body:'NATIVE can take responsibility for the operational side of the local platform presence — from account setup and publishing to optimization and reporting.',lead:'Possible responsibilities:',items:['account setup','localized profiles and bios','publishing','captions and titles','upload planning','platform optimization','performance reporting','content recommendations','coordination with local partners','The exact scope depends on the creator, platform and market.']},
production:{title:'Not everything should be localized. Some things should be created locally.',body:'When a market needs its own content, NATIVE combines strategy and production.',lead:'Possible formats include:',items:['social-first video','short-form content','creator collaborations','interviews','event coverage','travel content','brand integrations','campaign production','Creative direction and production are developed around the target audience rather than copied from another market.']},
talent:{title:'From audience growth to real opportunities.',body:'When a creator becomes relevant in a new market, NATIVE can go beyond platform management.',lead:'Depending on the creator and market, this can include:',items:['local brand introductions','campaign opportunities','creator collaborations','event and media opportunities','commercial negotiations','local representation','market-specific talent management','NATIVE can complement an existing European or international management team rather than replace it.','For example, a creator may keep their existing management in Europe while NATIVE acts as their specialized partner for Greater China.']},
markets:{title:'Built between Europe and China. Designed to travel further.',body:'Our initial focus connects two very different creator ecosystems.',fromEurope:'Europe → China',fromEuropeBody:'We help European creators enter platforms such as Douyin, RED and Bilibili with content designed for local audiences.',fromChina:'China → Europe',fromChinaBody:'We help Chinese creators adapt their content, positioning and partnerships for European platforms and audiences.',line:'The model is not limited to these markets. The same principle can expand wherever culture changes the way content is understood.'},
case:{eyebrow:'CREATOR CASES',title:'Built through real market experience.',body:'Our first cross-market creator cases are currently being developed. This space will document strategy, localization, platform growth and commercial opportunities based on real work.',label:'First creator case coming soon.'},
final:{title:'Your next audience may already be waiting.',body:'If you are considering entering a new market, we can start by looking at your existing content, platforms and potential.',cta:'Start a conversation'}},
de:{
seo:{title:'Für Creator | NATIVE',description:'Baue mit Strategie, Lokalisierung, Plattformmanagement, Produktion und Partnerschaften eine glaubwürdige Präsenz in neuen Märkten auf.'},
hero:{eyebrow:'FÜR CREATOR',title:'Bring deinen Content in neue Märkte – ohne zu verlieren, was dich ausmacht.',body:'NATIVE hilft Creatorn dabei, in neuen Märkten eine echte Präsenz aufzubauen – mit Strategie, Lokalisierung, Plattformmanagement, Produktion und Partnerschaften. Wir passen an, was bereits funktioniert, entwickeln weiter, was fehlt, und sorgen dafür, dass sich dein Content für die jeweilige Zielgruppe natürlich anfühlt.',primary:'Gespräch starten',secondary:'Leistungen entdecken'},
problem:{title:'Eine starke Creator-Identität darf mitreisen. Der Content darum muss sich anpassen.',body:'Was auf Instagram, YouTube oder TikTok in einem Markt funktioniert, funktioniert auf Douyin, RED, Bilibili oder anderen lokalen Plattformen nicht automatisch genauso. Zielgruppe, Plattformkultur, Storytelling, Tempo, Captions, Bildsprache und sogar die Rolle des Creators können sich verändern.',closing:'NATIVE überträgt die Identität – nicht nur die Sprache.'},
pillars:{title:'Alles, was du für den Eintritt in einen neuen Markt brauchst.',items:[['Market Entry','Wir analysieren Markt, Zielgruppe und Plattformen, definieren die passende Positionierung und entwickeln eine realistische Launch-Strategie.'],['Localization','Wir passen Sprache, Hooks, Captions, Storytelling, Schnitt und Kontext so an, dass dein Content im Zielmarkt wirklich funktioniert.'],['Platform Management','Wir unterstützen bei Accountaufbau, Publishing, Optimierung, Reporting und der laufenden Weiterentwicklung deiner lokalen Präsenz.'],['Production','Wenn bestehender Content nicht ausreicht, entwickeln und produzieren wir neue Formate gezielt für den jeweiligen Markt.'],['Talent & Partnerships','Wenn deine Präsenz wächst, kann NATIVE bei kommerziellen Partnerschaften, marktspezifischem Management und relevanten lokalen Kontakten unterstützen.']]},
content:{existing:{title:'Nutze zuerst, was bereits funktioniert.',body:'Der Eintritt in einen neuen Markt bedeutet nicht, dass du deinen gesamten Content neu produzieren musst.',lead:'Wir schauen zuerst auf deine bestehenden Inhalte:',items:['Welche Formate lassen sich übertragen?','Welche Themen sind lokal relevant?','Welche Videos brauchen nur eine sprachliche Anpassung?','Wo müssen Hook, Schnitt oder Kontext verändert werden?','Welche Inhalte sollten wir bewusst nicht verwenden?','Ziel ist es, deine bestehende Content-Bibliothek intelligent zu nutzen.']},fresh:{title:'Produziere neu, was der Markt wirklich braucht.',body:'Manche Chancen benötigen neuen Content.',lead:'Das können zum Beispiel sein:',items:['neue plattformspezifische Formate','lokale Collaborations','Interviews','Travel- oder Event-Content','lokale Brand-Kampagnen','gezielte Produktionen','neue Voiceover- oder Storytelling-Formate','NATIVE kann diese Formate gemeinsam mit dem Creator entwickeln und produzieren.']}},
journey:{title:'Vom ersten Markttest bis zur langfristigen Präsenz.',items:[['Marktanalyse','Wir prüfen, welches realistische Potenzial Creator, Content und Zielgruppe im gewünschten Markt haben.'],['Strategie & Setup','Plattformauswahl, Positionierung, Accountaufbau und erster Content-Plan.'],['Lokalisierung & Launch','Bestehender Content wird angepasst und die erste lokale Publishing-Phase startet.'],['Analyse & Optimierung','Wir analysieren die Performance und entwickeln die Content-Strategie anhand realer Nutzerreaktionen weiter.'],['Wachstum & Partnerschaften','Aus einer erfolgreichen Creator-Präsenz können Kooperationen, Kampagnen und langfristiges Management im Markt entstehen.']]},
platform:{title:'Du erstellst den Content. Wir kümmern uns um deine Präsenz im neuen Markt.',body:'NATIVE kann die operative Betreuung deiner lokalen Plattformpräsenz übernehmen – vom Accountaufbau und Publishing bis zu Optimierung und Reporting.',lead:'Mögliche Leistungen:',items:['Accountaufbau','lokalisierte Profile und Bios','Publishing','Captions und Titel','Upload-Planung','Plattformoptimierung','Performance-Reporting','Content-Empfehlungen','Koordination lokaler Partner','Der genaue Umfang richtet sich nach Creator, Plattform und Zielmarkt.']},
production:{title:'Nicht alles sollte lokalisiert werden. Manches sollte vor Ort neu entstehen.',body:'Wenn ein Markt eigenen Content benötigt, verbindet NATIVE Strategie und Produktion.',lead:'Mögliche Formate:',items:['Social-first Video','Short-Form Content','Creator Collaborations','Interviews','Event Coverage','Travel Content','Brand Integrations','Kampagnenproduktionen','Creative Direction und Produktion orientieren sich dabei an der Zielgruppe – nicht einfach an der Vorlage aus einem anderen Markt.']},
talent:{title:'Aus Reichweite können echte Chancen entstehen.',body:'Wenn ein Creator in einem neuen Markt relevant wird, kann NATIVE über die reine Plattformbetreuung hinausgehen.',lead:'Je nach Creator und Markt kann das umfassen:',items:['Kontakte zu lokalen Marken','Kampagnenmöglichkeiten','Creator-Kooperationen','Event- und Medienmöglichkeiten','kommerzielle Verhandlungen','lokale Repräsentation','marktspezifisches Talent Management','NATIVE kann ein bestehendes europäisches oder internationales Management ergänzen, statt es zu ersetzen.','Ein Creator kann beispielsweise sein bestehendes Management in Europa behalten, während NATIVE als spezialisierter Partner für Greater China auftritt.']},
markets:{title:'Zwischen Europa und China aufgebaut. Für weitere Märkte gedacht.',body:'Unser erster Fokus verbindet zwei sehr unterschiedliche Creator-Ökosysteme.',fromEurope:'Europa → China',fromEuropeBody:'Wir unterstützen europäische Creator dabei, Plattformen wie Douyin, RED und Bilibili mit lokal angepasstem Content zu erschließen.',fromChina:'China → Europa',fromChinaBody:'Wir helfen chinesischen Creatorn dabei, Content, Positionierung und Partnerschaften an europäische Plattformen und Zielgruppen anzupassen.',line:'Das Modell ist nicht auf diese Märkte begrenzt. Das gleiche Prinzip funktioniert überall dort, wo Kultur verändert, wie Content verstanden wird.'},
case:{eyebrow:'CREATOR CASES',title:'Aufgebaut durch echte Markterfahrung.',body:'Unsere ersten Cross-Market-Creator-Cases entstehen aktuell. Hier zeigen wir künftig Strategie, Lokalisierung, Plattformentwicklung und kommerzielle Möglichkeiten anhand echter Projekte.',label:'Erster Creator Case folgt.'},
final:{title:'Deine nächste Zielgruppe wartet vielleicht schon.',body:'Wenn du über einen neuen Markt nachdenkst, können wir mit deinem bestehenden Content, deinen Plattformen und deinem Potenzial starten.',cta:'Gespräch starten'}},
zh:{
seo:{title:'面向创作者 | NATIVE',description:'通过策略、本地化、平台运营、内容制作与商业合作，帮助创作者在新的市场建立真实而可信的影响力。'},
hero:{eyebrow:'面向创作者',title:'让你的内容进入新的市场，同时保留属于你的表达方式。',body:'NATIVE 帮助创作者通过策略、本地化、平台运营、内容制作与商业合作进入新的市场。我们保留原本有效的内容，针对当地受众进行调整，并在需要时开发新的内容形式，让你的表达在新的市场依然自然、真实。',primary:'联系我们',secondary:'了解我们的服务'},
problem:{title:'创作者的个人风格可以跨越市场，但内容表达需要适应当地环境。',body:'在一个市场中适用于 Instagram、YouTube 或 TikTok 的内容，并不会自动适用于抖音、小红书、哔哩哔哩或其他本地平台。受众习惯、平台文化、叙事方式、节奏、文案、视觉语言，甚至创作者本身的表达角色都可能发生变化。',closing:'NATIVE 要做的，不只是翻译语言，而是让你的个人风格真正进入新的文化语境。'},
pillars:{title:'进入新市场所需要的关键能力，集中在一个团队中。',items:[['Market Entry','我们分析目标市场、受众与平台，明确合适的定位，并制定可执行的市场进入策略.'],['Localization','我们根据当地市场调整语言、开场、文案、叙事方式、剪辑节奏与文化语境，让内容真正适合当地受众。'],['Platform Management','我们支持账号搭建、内容发布、优化、数据分析以及账号在当地市场的持续发展。'],['Production','当现有内容不足以支撑市场拓展时，我们会针对目标市场开发并制作新的内容形式。'],['Talent & Partnerships','随着你在当地市场的影响力增长，NATIVE 可以进一步支持品牌合作、当地市场的艺人管理以及商业资源对接。']]},
content:{existing:{title:'先利用已经有效的内容。',body:'进入一个新的市场，并不意味着所有内容都要从零开始重新制作。',lead:'我们首先分析你已有的内容：',items:['哪些内容形式可以进入新的市场？','哪些主题对当地受众同样具有吸引力？','哪些视频只需要语言上的调整？','哪些内容需要重新设计开场、剪辑或背景信息？','哪些内容并不适合目标市场？','我们的目标，是更聪明地利用你已经拥有的内容资产。']},fresh:{title:'只为真正需要的新内容进行制作。',body:'有些机会确实需要新的内容。',lead:'例如：',items:['针对本地平台开发的新形式','当地创作者合作','采访内容','旅行或活动内容','当地品牌合作','专门策划的拍摄','新的配音或叙事形式','NATIVE 可以与创作者一起开发并完成这些内容。']}},
journey:{title:'从第一次市场测试，到长期的本地影响力。',items:[['市场评估','我们评估创作者、内容与受众在目标市场中的实际潜力。'],['策略与账号搭建','平台选择、定位、账号搭建以及首阶段内容规划。'],['本地化与上线','我们对现有内容进行本地化，并启动第一阶段的内容发布。'],['分析与优化','我们根据真实的数据与受众反馈持续调整内容策略。'],['增长与商业合作','当创作者在当地建立影响力后，可以进一步发展品牌合作、商业项目以及长期的市场管理。']]},
platform:{title:'你专注于创作，我们负责你在新市场的平台运营。',body:'NATIVE 可以承担当地平台运营中的执行工作，从账号搭建和内容发布，到持续优化与数据分析。',lead:'可能包括：',items:['账号搭建','本地化个人资料与简介','内容发布','标题与文案','发布计划','平台优化','数据报告','内容建议','当地合作伙伴协调','具体服务范围会根据创作者、平台和目标市场进行调整。']},
production:{title:'并不是所有内容都应该被本地化。有些内容，更适合直接在当地重新创作。',body:'当一个市场需要真正属于自己的内容时，NATIVE 会把市场策略与内容制作结合起来。',lead:'可能包括：',items:['社交媒体视频','短视频内容','创作者合作','采访','活动内容','旅行内容','品牌植入','品牌活动制作','创意方向与制作方式会围绕当地受众设计，而不是简单复制另一个市场的内容模式。']},
talent:{title:'从受众增长，到真正的商业机会。',body:'当创作者在新的市场中建立影响力后，NATIVE 可以提供超越平台运营的进一步支持。',lead:'根据创作者与市场情况，可以包括：',items:['当地品牌资源','商业活动机会','创作者合作','活动与媒体机会','商务谈判','当地市场代表','特定市场的艺人管理','NATIVE 可以与创作者现有的欧洲或国际管理团队合作，而不是取代他们。','例如，创作者可以继续保留欧洲现有的管理团队，同时由 NATIVE 作为其大中华区的专业合作伙伴。']},
markets:{title:'从欧洲与中国之间出发，为更多市场而设计。',body:'我们的初始重点，是连接两个非常不同的创作者生态。',fromEurope:'欧洲 → 中国',fromEuropeBody:'我们帮助欧洲创作者通过真正本地化的内容进入抖音、小红书、哔哩哔哩等平台。',fromChina:'中国 → 欧洲',fromChinaBody:'我们帮助中国创作者调整内容、定位与合作方式，更好地进入欧洲的平台与受众。',line:'NATIVE 的模式并不局限于欧洲和中国。只要文化会影响内容的理解方式，这套方法就可以扩展到更多市场。'},
case:{eyebrow:'创作者案例',title:'真正的经验，来自真实的市场实践。',body:'我们的第一批跨市场创作者案例正在推进中。未来这里将通过真实项目展示市场策略、本地化、平台增长以及商业机会。',label:'首个创作者案例即将上线。'},
final:{title:'你的下一批受众，也许已经在那里等你。',body:'如果你正在考虑进入一个新的市场，我们可以先从你的现有内容、平台与市场潜力开始分析。',cta:'联系我们'}}};
