import type {Locale} from './i18n';

type Block={title:string;body:string;lead?:string;items:string[]};
type CreatorsCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};problem:{title:string;body:string;closing:string};pillars:{title:string;items:Array<[string,string]>};content:{existing:Block;fresh:Block};journey:{title:string;items:Array<[string,string]>};platform:Block;production:Block;talent:Block;markets:{title:string;body:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};case:{eyebrow:string;title:string;body:string;label:string};final:{title:string;body:string;cta:string}};

export const creatorsCopy:Record<Locale,CreatorsCopy>={
en:{
seo:{title:'For Creators | NATIVE',description:'Build a credible creator presence in new markets through strategy, localization, platform management, production and partnerships.'},
hero:{eyebrow:'FOR CREATORS',title:'Take your content into new markets without losing what makes it yours.',body:'NATIVE helps creators build a real presence in new markets. We develop what already works, adapt content to local platforms and audiences, and create new formats when the market calls for them.',primary:'Start a conversation',secondary:'Explore our services'},
problem:{title:'What works today will not automatically work in the next market.',body:'Instagram, TikTok and YouTube play by different rules than Douyin, RED or Bilibili. Platform culture, storytelling, pacing, visual language and audience expectations all change.',closing:'That is why we do not simply move content from one platform to another.\n\nWe keep your identity recognizable while making the content work in the new market.'},
pillars:{title:'Everything you need to enter the next market.',items:[['Market Entry','We assess the market, audience and platforms, define the right positioning and build a realistic way in.'],['Localization','We adapt language, hooks, storytelling, editing, context and platform logic so the content works locally.'],['Platform Management','We support account setup, publishing, optimization, reporting and the ongoing development of your local presence.'],['Production','When existing content is not enough, we develop and produce new formats specifically for the market.'],['Talent & Partnerships','As your presence grows, we help with brand opportunities, local relationships, partnerships and market-specific representation.']]},
content:{existing:{title:'Start with what already works.',body:'Entering a new market does not mean starting from zero.',lead:'We begin with the content you already have:',items:['Which formats can travel?','Which topics still work locally?','Which videos only need language adaptation?','Where do the hook, edit or context need to change?','Which content should we deliberately leave behind?','The goal is to use your existing content library intelligently.']},fresh:{title:'Create what the market actually needs.',body:'Some opportunities need new formats.',lead:'That might include:',items:['platform-native content','local creator collaborations','interviews','travel or event content','brand integrations','dedicated productions','new voiceover or storytelling formats','NATIVE develops and produces these formats with you.']}},
journey:{title:'From first test to long-term presence.',items:[['Market Check','We assess where your content, audience and positioning have realistic potential.'],['Strategy & Setup','Platform selection, positioning, account setup and the first content plan.'],['Localization & Launch','We adapt existing content and begin the first publishing phase in the new market.'],['Learn & Optimize','We look at real performance and audience behavior and keep refining the strategy.'],['Growth & Partnerships','A successful local presence can lead to partnerships, campaigns and long-term market support.']]},
platform:{title:'You create the content. We help run your presence in the new market.',body:'NATIVE can handle the operational side of your local platforms — from account setup and publishing to optimization and reporting.',lead:'Possible responsibilities:',items:['account setup','localized profiles and bios','publishing','titles and captions','upload planning','platform optimization','performance reporting','content recommendations','coordination with local partners','The exact scope depends on the platform, market and what you need.']},
production:{title:'Not everything should be localized. Some things should be made locally.',body:'When a market needs its own content, we bring strategy and production together.',lead:'Possible formats:',items:['social-first video','short-form content','creator collaborations','interviews','event content','travel content','brand integrations','campaign production','Creative direction and production are built around the target market, not copied from another one.']},
talent:{title:'Reach can turn into real opportunities.',body:'When you become relevant in a new market, NATIVE can go beyond platform management.',lead:'Depending on the creator and market, that can include:',items:['local brand introductions','campaign opportunities','creator collaborations','event and media opportunities','commercial negotiations','local representation','market-specific talent management','NATIVE can complement an existing European or international management team rather than replace it.','For example:\nYou keep your existing management in Europe while NATIVE acts as your specialized partner for Greater China.']},
markets:{title:'Between Europe and China. Built to go further.',body:'Our first focus connects two very different creator ecosystems.',fromEurope:'Europe → China',fromEuropeBody:'We help European creators enter platforms such as Douyin, RED and Bilibili with content adapted to local audiences.',fromChina:'China → Europe',fromChinaBody:'We help Chinese creators adapt content, positioning and partnerships for European platforms and audiences.',line:'The model is not limited to these markets. What matters is how content needs to change when the cultural context changes.'},
case:{eyebrow:'CREATOR CASES',title:'Market experience is built through real projects.',body:'Our first cross-market creator cases are currently being developed. This is where we will show how strategy, localization, platform growth and partnerships work together in real projects.',label:'First creator case coming soon.'},
final:{title:'Your next audience may already be waiting.',body:'If you are considering a new market, we start with what already exists: your content, your platforms and your potential.',cta:'Start a conversation'}},
de:{
seo:{title:'Für Creator | NATIVE',description:'Baue mit Strategie, Lokalisierung, Plattformmanagement, Produktion und Partnerschaften eine glaubwürdige Präsenz in neuen Märkten auf.'},
hero:{eyebrow:'FÜR CREATOR',title:'Bring deinen Content in neue Märkte – ohne zu verlieren, was dich ausmacht.',body:'NATIVE hilft dir dabei, in neuen Märkten eine echte Präsenz aufzubauen. Wir entwickeln weiter, was bereits funktioniert, passen Content an lokale Plattformen und Zielgruppen an und produzieren neu, wenn es der Markt verlangt.',primary:'Gespräch starten',secondary:'Leistungen entdecken'},
problem:{title:'Was heute funktioniert, funktioniert nicht automatisch im nächsten Markt.',body:'Instagram, TikTok oder YouTube folgen anderen Regeln als Douyin, RED oder Bilibili. Plattformkultur, Storytelling, Tempo, Bildsprache und die Erwartungen der Zielgruppe verändern sich.',closing:'Deshalb übertragen wir nicht einfach Content.\n\nWir sorgen dafür, dass deine Handschrift erkennbar bleibt und trotzdem im neuen Markt funktioniert.'},
pillars:{title:'Alles, was du für den Einstieg in einen neuen Markt brauchst.',items:[['Market Entry','Wir prüfen Markt, Zielgruppe und Plattformen, definieren eine sinnvolle Positionierung und entwickeln einen realistischen Einstieg.'],['Localization','Wir passen Sprache, Hooks, Storytelling, Schnitt, Kontext und Plattformlogik so an, dass dein Content vor Ort funktioniert.'],['Platform Management','Wir unterstützen bei Accountaufbau, Publishing, Optimierung, Reporting und der laufenden Weiterentwicklung deiner lokalen Präsenz.'],['Production','Wenn bestehender Content nicht reicht, entwickeln und produzieren wir neue Formate gezielt für den jeweiligen Markt.'],['Talent & Partnerships','Wenn deine Präsenz wächst, helfen wir bei Markenkooperationen, lokalen Kontakten, Partnerschaften und marktspezifischem Management.']]},
content:{existing:{title:'Nutze zuerst, was bereits funktioniert.',body:'Ein neuer Markt bedeutet nicht, dass du bei null anfangen musst.',lead:'Wir schauen zuerst auf deinen bestehenden Content:',items:['Welche Formate lassen sich übertragen?','Welche Themen funktionieren auch lokal?','Welche Videos brauchen nur eine sprachliche Anpassung?','Wo müssen Hook, Schnitt oder Kontext verändert werden?','Welche Inhalte sollten wir bewusst nicht einsetzen?','Das Ziel ist, vorhandenen Content intelligent weiterzuverwenden.']},fresh:{title:'Produziere neu, was der Markt wirklich braucht.',body:'Manche Chancen brauchen neue Formate.',lead:'Das können zum Beispiel sein:',items:['plattformspezifischer Content','lokale Creator-Kooperationen','Interviews','Travel- oder Event-Content','Markenintegrationen','gezielte Produktionen','neue Voiceover- oder Storytelling-Formate','NATIVE entwickelt und produziert diese Inhalte gemeinsam mit dir.']}},
journey:{title:'Vom ersten Test bis zur langfristigen Präsenz.',items:[['Marktcheck','Wir prüfen, wo dein Content, deine Zielgruppe und deine Positionierung realistisches Potenzial haben.'],['Strategie & Setup','Plattformauswahl, Positionierung, Accountaufbau und erster Content-Plan.'],['Localization & Launch','Wir passen bestehenden Content an und starten die erste Publishing-Phase im neuen Markt.'],['Analyse & Optimierung','Wir schauen auf echte Performance und Nutzerreaktionen und entwickeln die Strategie laufend weiter.'],['Wachstum & Partnerschaften','Aus einer erfolgreichen Präsenz können Kooperationen, Kampagnen und langfristige Marktbetreuung entstehen.']]},
platform:{title:'Du erstellst den Content. Wir kümmern uns um deine Präsenz im neuen Markt.',body:'NATIVE kann die operative Betreuung deiner lokalen Plattformen übernehmen – vom Accountaufbau über Publishing bis zu Optimierung und Reporting.',lead:'Mögliche Leistungen:',items:['Accountaufbau','lokalisierte Profile und Bios','Publishing','Titel und Captions','Upload-Planung','Plattformoptimierung','Performance-Reporting','Content-Empfehlungen','Koordination lokaler Partner','Der genaue Umfang richtet sich nach Plattform, Markt und deinem Bedarf.']},
production:{title:'Nicht alles sollte lokalisiert werden. Manches sollte vor Ort neu entstehen.',body:'Wenn ein Markt eigenen Content braucht, verbinden wir Strategie und Produktion.',lead:'Mögliche Formate:',items:['Social-first Video','Short-Form Content','Creator Collaborations','Interviews','Event Content','Travel Content','Brand Integrations','Kampagnenproduktionen','Creative Direction und Produktion orientieren sich dabei am Zielmarkt – nicht an einer Vorlage aus einem anderen Markt.']},
talent:{title:'Aus Reichweite können echte Chancen entstehen.',body:'Wenn du in einem neuen Markt relevant wirst, kann NATIVE über Plattformmanagement hinausgehen.',lead:'Je nach Markt und Creator kann das umfassen:',items:['Kontakte zu lokalen Marken','Kampagnenmöglichkeiten','Creator-Kooperationen','Event- und Medienmöglichkeiten','kommerzielle Verhandlungen','lokale Repräsentation','marktspezifisches Talent Management','NATIVE kann ein bestehendes europäisches oder internationales Management ergänzen, statt es zu ersetzen.','Zum Beispiel:\nDu behältst dein bestehendes Management in Europa, während NATIVE als spezialisierter Partner für Greater China arbeitet.']},
markets:{title:'Zwischen Europa und China. Von hier aus weiter gedacht.',body:'Unser erster Fokus verbindet zwei sehr unterschiedliche Creator-Ökosysteme.',fromEurope:'Europa → China',fromEuropeBody:'Wir helfen europäischen Creatorn dabei, Plattformen wie Douyin, RED und Bilibili mit lokal angepasstem Content zu erschließen.',fromChina:'China → Europa',fromChinaBody:'Wir helfen chinesischen Creatorn dabei, Content, Positionierung und Partnerschaften an europäische Plattformen und Zielgruppen anzupassen.',line:'Das Modell ist nicht auf diese Märkte begrenzt. Entscheidend ist immer, wie sich Content an den kulturellen Kontext eines neuen Marktes anpasst.'},
case:{eyebrow:'CREATOR CASES',title:'Echte Markterfahrung entsteht durch echte Projekte.',body:'Unsere ersten Cross-Market-Creator-Cases entstehen aktuell. Hier zeigen wir künftig, wie Strategie, Lokalisierung, Plattformentwicklung und Partnerschaften in realen Projekten zusammenwirken.',label:'Erster Creator Case folgt.'},
final:{title:'Deine nächste Zielgruppe wartet vielleicht schon.',body:'Wenn du über einen neuen Markt nachdenkst, starten wir mit dem, was bereits da ist: deinem Content, deinen Plattformen und deinem Potenzial.',cta:'Gespräch starten'}},
zh:{
seo:{title:'面向创作者 | NATIVE',description:'通过策略、本地化、平台运营、内容制作与商业合作，帮助创作者在新的市场建立真实而可信的影响力。'},
hero:{eyebrow:'面向创作者',title:'进入新的市场，也保留你自己的表达。',body:'NATIVE 帮助创作者在新的市场建立真正的存在感。我们延续已经有效的内容，根据当地平台与受众进行调整，并在需要时开发新的内容形式。',primary:'联系我们',secondary:'了解我们的服务'},
problem:{title:'现在有效的内容，到了下一个市场未必依然有效。',body:'Instagram、TikTok、YouTube 和抖音、小红书、哔哩哔哩之间，平台逻辑并不相同。平台文化、叙事方式、节奏、视觉表达以及受众期待都会发生变化。',closing:'所以，我们不会简单地把内容从一个平台搬到另一个平台。\n\n我们保留你的个人风格，同时让内容真正适应新的市场。'},
pillars:{title:'进入新的市场，你需要的不只是一个服务。',items:[['Market Entry','我们分析市场、受众与平台，明确合适的定位，并制定现实可行的进入方式。'],['Localization','我们根据当地市场调整语言、开场、叙事、剪辑、文化语境与平台逻辑，让内容真正适合当地受众。'],['Platform Management','我们支持账号搭建、内容发布、优化、数据分析以及当地平台的持续运营。'],['Production','当现有内容不足时，我们会针对目标市场开发并制作新的内容形式。'],['Talent & Partnerships','随着你的影响力增长，我们可以进一步支持品牌合作、当地资源、商业机会与特定市场的管理。']]},
content:{existing:{title:'先利用已经有效的内容。',body:'进入新的市场，并不意味着从零开始。',lead:'我们先看你已经拥有的内容：',items:['哪些形式可以继续使用？','哪些主题在当地依然有吸引力？','哪些视频只需要语言调整？','哪些内容需要重新设计开场、剪辑或背景信息？','哪些内容其实不适合目标市场？','目标是更聪明地利用你已经拥有的内容资产。']},fresh:{title:'只为市场真正需要的内容重新制作。',body:'有些机会确实需要新的内容形式。',lead:'例如：',items:['平台原生内容','当地创作者合作','采访','旅行或活动内容','品牌植入','专门策划的拍摄','新的配音或叙事形式','NATIVE 可以与你一起开发并完成这些内容。']}},
journey:{title:'从第一次市场测试，到长期建立影响力。',items:[['市场评估','我们判断你的内容、受众和定位在哪些市场具有现实潜力。'],['策略与账号搭建','平台选择、定位、账号搭建以及第一阶段内容规划。'],['本地化与上线','我们调整现有内容，并启动第一阶段的当地发布。'],['分析与优化','我们根据真实表现与受众反馈，持续调整内容策略。'],['增长与合作','当本地影响力逐渐形成后，可以进一步发展品牌合作、商业项目与长期市场支持。']]},
platform:{title:'你专注于创作，我们负责你在新市场的平台运营。',body:'NATIVE 可以负责当地平台的日常运营，从账号搭建、内容发布到持续优化与数据分析。',lead:'可能包括：',items:['账号搭建','本地化个人资料与简介','内容发布','标题与文案','发布计划','平台优化','数据报告','内容建议','当地合作伙伴协调','具体范围会根据平台、市场和你的实际需求来调整。']},
production:{title:'并不是所有内容都应该本地化。有些内容更适合在当地重新创作。',body:'当一个市场需要属于自己的内容时，我们会把策略与制作结合起来。',lead:'可能包括：',items:['Social-first 视频','短视频内容','创作者合作','采访','活动内容','旅行内容','品牌植入','品牌活动制作','创意方向与制作方式会围绕目标市场设计，而不是照搬另一个市场的内容。']},
talent:{title:'影响力可以进一步转化为真正的机会。',body:'当你在新的市场建立起影响力后，NATIVE 可以提供超越平台运营的进一步支持。',lead:'根据创作者和市场情况，可以包括：',items:['当地品牌资源','商业活动机会','创作者合作','活动与媒体机会','商务谈判','当地市场代表','特定市场的艺人管理','NATIVE 可以与现有的欧洲或国际管理团队合作，而不是取代他们。','例如：\n你可以继续保留欧洲现有的管理团队，同时由 NATIVE 作为你在大中华区的专业合作伙伴。']},
markets:{title:'连接欧洲与中国，也为更多市场留出空间。',body:'我们的第一个重点，是连接两个非常不同的创作者生态。',fromEurope:'欧洲 → 中国',fromEuropeBody:'我们帮助欧洲创作者进入抖音、小红书、哔哩哔哩等平台，并根据当地受众调整内容。',fromChina:'中国 → 欧洲',fromChinaBody:'我们帮助中国创作者调整内容、定位与合作方式，更自然地进入欧洲的平台与受众。',line:'这套方法并不局限于欧洲和中国。关键始终是：当文化语境改变时，内容应该如何随之变化。'},
case:{eyebrow:'创作者案例',title:'真正的市场经验，来自实际项目。',body:'我们的第一批跨市场创作者案例正在推进中。未来这里会展示策略、本地化、平台增长与合作关系如何在真实项目中共同发挥作用。',label:'首个创作者案例即将上线'},
final:{title:'你的下一批受众，也许已经在那里等你。',body:'如果你正在考虑进入新的市场，我们可以先从你已经拥有的内容、平台与潜力开始。',cta:'联系我们'}}};
