import type {Locale} from './i18n';

type HomeCopy = {
  label: string; claim: string; intro: string; creatorCta: string; brandCta: string; marketNote: string;
  why: {label: string; title: string; body: string; details: string[]};
  audiences: {label: string; creator: Audience; brand: Audience};
  services: {label: string; title: string; intro: string; items: Array<[string, string]>};
  markets: {label: string; title: string; europeChina: Market; chinaEurope: Market; expansion: string};
  work: {label: string; title: string; body: string; placeholders: string[]; status: string; schema: string[]};
  about: {label: string; title: string; intro: string; people: Array<{name: string; focus: string}>};
  final: {eyebrow: string; title: string; cta: string};
};
type Audience = {kicker: string; title: string; body: string; items: string[]; cta: string};
type Market = {direction: string; title: string; body: string};

export const homeCopy: Record<Locale, HomeCopy> = {
  en: {
    label: 'Cross-cultural media · localization · production', claim: 'Make your brand feel local.', intro: 'NATIVE helps creators and brands become relevant in new markets through strategy, localization, production, platform management and the right partnerships — without losing what made them recognizable in the first place.', creatorCta: "I'm a Creator", brandCta: "I'm a Brand", marketNote: 'Europe ↔ China · built to go further',
    why: {label: 'Why NATIVE', title: 'What works in one market will not automatically work in the next.', body: 'Language is only part of it. Platforms, cultural codes, storytelling, visual language and audience expectations change from market to market.\n\nThat is why simply translating and reposting content is rarely enough.', details: ['Language & Tone', 'Platform Culture', 'Storytelling & Editing', 'Creators & Audiences']},
    audiences: {label: 'Two perspectives. One local standard.', creator: {kicker: 'For creators', title: 'Your content. Your voice. A new market.', body: 'We help creators adapt what already works, build a local platform presence and develop new formats and partnerships — without losing the identity behind the content.', items: ['Content Localization', 'Platform Management', 'Production', 'Partnerships & Talent'], cta: 'For Creators'}, brand: {kicker: 'For brands', title: 'New markets need more than translation.', body: 'We adapt positioning, campaigns and content so your brand feels understood and relevant locally — without losing its character.', items: ['Local Positioning', 'Campaigns', 'Creator Partnerships', 'Production', 'Market Entry'], cta: 'For Brands'}},
    services: {label: 'What we do', title: 'From first thought to execution.', intro: 'NATIVE connects five areas that can work independently or together depending on the project.', items: [['Market Entry', 'Understand the market, identify real potential and plan the right way in.'], ['Localization', 'Adapt language, storytelling, platform logic and cultural context to the target market.'], ['Platform Management', 'Build accounts, publish content, optimize performance and keep the local presence moving forward.'], ['Production', 'Develop and produce new content and campaigns when existing assets are not enough.'], ['Talent & Partnerships', 'Connect creators, brands and the right relationships in the relevant market.']]},
    markets: {label: 'Europe ↔ China', title: 'Between Europe and China. In both directions.', europeChina: {direction: 'Europe → China', title: 'Enter new platforms with real local understanding.', body: 'We help creators and brands build relevance on Chinese platforms and with Chinese audiences.'}, chinaEurope: {direction: 'China → Europe', title: 'Adapt the communication. Keep the identity.', body: 'We help Chinese creators and brands show up in Europe in a way that feels natural, not imported.'}, expansion: 'This is where we start. It does not have to be where we stop.'},
    work: {label: 'Selected work', title: 'In the end, the work matters.', body: 'Our first cross-market cases are currently being developed. As soon as we can show real projects and meaningful results, you will find them here.', placeholders: ['Case study coming soon', 'Cross-market production', 'Creator localization'], status: 'First case coming soon', schema: ['Media', 'Case description', 'Metrics']},
    about: {label: 'Founder-led', title: 'Strategy and execution belong together.', intro: 'NATIVE combines strategic thinking with hands-on creative execution.', people: [{name: 'Daniel Nonn', focus: 'Strategy · Business Development · Partnerships · Cross-Market'}, {name: 'Timm', focus: 'Creative Direction · Production · Video · Content'}]},
    final: {eyebrow: 'Where next?', title: 'New market. Same identity. Relevant where it matters.', cta: 'Start a conversation'},
  },
  de: {
    label: 'Cross-cultural Media · Lokalisierung · Produktion', claim: 'Make your brand feel local.', intro: 'NATIVE hilft Creatorn und Marken dabei, in neuen Märkten relevant zu werden. Mit Strategie, Lokalisierung, Produktion, Plattformmanagement und den richtigen Partnerschaften – ohne zu verlieren, was sie ursprünglich ausmacht.', creatorCta: 'Ich bin Creator', brandCta: 'Ich bin eine Marke', marketNote: 'Europa ↔ China · von hier aus weiter gedacht',
    why: {label: 'Warum NATIVE', title: 'Was in einem Markt funktioniert, funktioniert nicht automatisch im nächsten.', body: 'Sprache ist dabei nur ein Teil. Plattformen, kulturelle Codes, Storytelling, Bildsprache und die Erwartungen der Zielgruppe unterscheiden sich von Markt zu Markt.\n\nDeshalb reicht es nicht, Content einfach zu übersetzen und erneut zu veröffentlichen.', details: ['Sprache & Tonalität', 'Plattformkultur', 'Storytelling & Schnitt', 'Creator & Zielgruppen']},
    audiences: {label: 'Zwei Perspektiven. Ein lokaler Anspruch.', creator: {kicker: 'Für Creator', title: 'Dein Content. Deine Handschrift. Ein neuer Markt.', body: 'Wir helfen dir, bestehende Inhalte für neue Zielgruppen weiterzuentwickeln, lokale Plattformen aufzubauen und neue Formate und Partnerschaften zu erschließen – ohne dass dein Content seine eigene Identität verliert.', items: ['Content Localization', 'Platform Management', 'Production', 'Partnerships & Talent'], cta: 'Mehr für Creator'}, brand: {kicker: 'Für Marken', title: 'Neue Märkte brauchen mehr als eine Übersetzung.', body: 'Wir passen Positionierung, Kampagnen und Content so an, dass deine Marke vor Ort verstanden wird und relevant wirkt – ohne ihren Charakter zu verlieren.', items: ['Lokale Positionierung', 'Kampagnen', 'Creator Partnerships', 'Produktion', 'Market Entry'], cta: 'Mehr für Marken'}},
    services: {label: 'Was wir tun', title: 'Vom ersten Gedanken bis zur Umsetzung.', intro: 'NATIVE verbindet fünf Bereiche, die je nach Projekt einzeln oder gemeinsam zum Einsatz kommen.', items: [['Market Entry', 'Den richtigen Markt verstehen, Potenziale erkennen und den Einstieg sinnvoll planen.'], ['Localization', 'Sprache, Storytelling, Plattformlogik und kulturellen Kontext an den Zielmarkt anpassen.'], ['Platform Management', 'Accounts aufbauen, Inhalte veröffentlichen, weiterentwickeln und Performance auswerten.'], ['Production', 'Content und Kampagnen entwickeln und produzieren, wenn bestehendes Material nicht ausreicht.'], ['Talent & Partnerships', 'Creator, Marken und relevante Kontakte im jeweiligen Markt miteinander verbinden.']]},
    markets: {label: 'Europa ↔ China', title: 'Zwischen Europa und China. In beide Richtungen.', europeChina: {direction: 'Europa → China', title: 'In neue Plattformen eintauchen – mit echtem lokalem Verständnis.', body: 'Wir unterstützen Creator und Marken dabei, sich auf chinesischen Plattformen und bei chinesischen Zielgruppen relevant zu positionieren.'}, chinaEurope: {direction: 'China → Europa', title: 'Die Kommunikation anpassen. Die Identität bewahren.', body: 'Wir helfen chinesischen Creatorn und Marken dabei, in Europa so aufzutreten, dass sich ihr Marketing nicht wie importiert anfühlt.'}, expansion: 'Hier starten wir. Dabei muss es nicht bleiben.'},
    work: {label: 'Selected Work', title: 'Am Ende zählt die Arbeit.', body: 'Unsere ersten Cross-Market-Cases entstehen gerade. Sobald wir echte Projekte und belastbare Ergebnisse zeigen können, findest du sie hier.', placeholders: ['Case Study folgt', 'Cross-Market Produktion', 'Creator-Lokalisierung'], status: 'Erster Case folgt', schema: ['Media', 'Case-Beschreibung', 'Kennzahlen']},
    about: {label: 'Founder-led', title: 'Strategie und Umsetzung gehören zusammen.', intro: 'NATIVE verbindet strategisches Denken mit direkter kreativer Umsetzung.', people: [{name: 'Daniel Nonn', focus: 'Strategie · Business Development · Partnerschaften · Cross-Market'}, {name: 'Timm', focus: 'Creative Direction · Produktion · Video · Content'}]},
    final: {eyebrow: 'Wohin als Nächstes?', title: 'Neuer Markt. Gleiche Identität. Vor Ort relevant.', cta: 'Gespräch starten'},
  },
  zh: {
    label: '跨文化媒体 · 本地化 · 内容制作', claim: 'Make your brand feel local.', intro: 'NATIVE 帮助创作者与品牌进入新的市场，通过策略、本地化、内容制作、平台运营与合适的合作关系，建立真正的本地相关性，同时保留原本最有辨识度的部分。', creatorCta: '我是创作者', brandCta: '我是品牌方', marketNote: '欧洲 ↔ 中国 · 从这里出发，走向更多市场',
    why: {label: '为什么选择 NATIVE', title: '在一个市场有效的内容，到了下一个市场未必依然有效。', body: '语言只是其中一部分。平台习惯、文化语境、叙事方式、视觉表达以及受众期待，都会随着市场而改变。\n\n所以，真正的市场进入从来不只是翻译后重新发布。', details: ['语言与语气', '平台文化', '叙事与剪辑', '创作者与受众']},
    audiences: {label: '双向视角，同一本地标准。', creator: {kicker: '创作者', title: '你的内容。你的表达。一个新的市场。', body: '我们帮助创作者延续已经有效的内容，同时根据当地平台与受众进行调整，并开发新的内容形式与合作机会，让你的个人风格在新的市场依然清晰可见。', items: ['Content Localization', 'Platform Management', 'Production', 'Partnerships & Talent'], cta: '创作者服务'}, brand: {kicker: '品牌', title: '进入新的市场，不能只靠翻译。', body: '我们根据当地市场调整品牌定位、内容与传播方式，让品牌被真正理解、自然融入当地，同时保留原本的品牌个性。', items: ['本地定位', '品牌活动', 'Creator Partnerships', 'Production', 'Market Entry'], cta: '品牌服务'}},
    services: {label: '我们的工作', title: '从第一步判断，到真正落地。', intro: 'NATIVE 将五个核心能力连接起来，可以根据项目单独使用，也可以组合成完整的跨市场执行体系。', items: [['Market Entry', '理解市场、判断真实机会，并规划最合适的进入方式。'], ['Localization', '根据目标市场调整语言、叙事、平台逻辑与文化语境。'], ['Platform Management', '搭建账号、发布内容、持续优化，并根据真实表现不断调整。'], ['Production', '当现有素材不足时，为当地市场开发并制作新的内容与品牌活动。'], ['Talent & Partnerships', '连接创作者、品牌与当地真正有价值的合作关系。']]},
    markets: {label: '欧洲 ↔ 中国', title: '连接欧洲与中国，而且是双向的。', europeChina: {direction: '欧洲 → 中国', title: '真正理解当地，再进入新的平台。', body: '我们帮助欧洲创作者与品牌进入中国平台和受众，并建立符合当地语境的内容与合作方式。'}, chinaEurope: {direction: '中国 → 欧洲', title: '调整表达方式，保留原有身份。', body: '我们帮助中国创作者与品牌进入欧洲，让传播方式更符合当地习惯，而不是让内容看起来像直接从另一个市场搬过来。'}, expansion: '这里是我们的起点，不是边界。'},
    work: {label: '精选案例', title: '最终，还是要让作品本身说话。', body: '我们的第一批跨市场案例正在推进中。等到项目与结果足够真实、足够完整时，我们会在这里展示。', placeholders: ['案例即将上线', '跨市场制作', '创作者本地化'], status: '首个案例即将上线', schema: ['影像', '案例说明', '数据指标']},
    about: {label: '创始人主导', title: '策略与执行，本来就应该在一起。', intro: 'NATIVE 把市场判断、商业思维与一线创意执行放在同一个体系里。', people: [{name: 'Daniel Nonn', focus: '市场策略 · 商务拓展 · 合作伙伴关系 · Cross-Market'}, {name: 'Timm', focus: '创意指导 · 内容制作 · 视频 · Content'}]},
    final: {eyebrow: '下一站？', title: '进入新的市场，保留原有身份，真正融入当地。', cta: '联系我们'},
  },
};
