import type {Locale} from './i18n';

type HomeCopy = {
  label: string; claim: string; intro: string; creatorCta: string; brandCta: string; marketNote: string;
  why: {label: string; title: string; body: string; details: string[]};
  audiences: {label: string; creator: Audience; brand: Audience};
  services: {label: string; title: string; intro: string; items: Array<[string, string]>};
  markets: {label: string; title: string; europeChina: Market; chinaEurope: Market; expansion: string};
  work: {label: string; title: string; body: string; placeholders: string[]; status: string; schema: string[]};
  about: {label: string; title: string; intro: string; people: Array<{name: string; focus: string}>};
  final: {eyebrow: string; title: string; cta: string};
};
type Audience = {kicker: string; title: string; body: string; items: string[]; cta: string};
type Market = {direction: string; title: string; body: string};

export const homeCopy: Record<Locale, HomeCopy> = {
  en: {
    label: 'Cross-cultural media · localization · production', claim: 'Make your brand feel local.', intro: 'NATIVE helps creators and brands enter new markets through strategy, localization, production, platform management and partnerships — without losing what makes them recognizable.', creatorCta: "I'm a Creator", brandCta: "I'm a Brand", marketNote: 'Europe ↔ China · built to travel further',
    why: {label: 'Why NATIVE', title: "Content travels. Relevance doesn’t automatically.", body: 'A successful piece of content cannot simply be translated and reposted. Language, platform culture, storytelling, editing and audience expectations change from market to market.', details: ['Language & tone', 'Platform culture', 'Story & editing', 'Creators & audiences']},
    audiences: {label: 'Two perspectives. One local standard.', creator: {kicker: 'For creators', title: 'Your voice, understood in a new market.', body: 'We help creators adapt existing content, build local platform presence, produce new formats and develop partnerships in new markets.', items: ['Content localization', 'Platform presence', 'Account management', 'Production', 'Partnerships & talent'], cta: 'Explore creator services'}, brand: {kicker: 'For brands', title: 'Enter the culture, not just the market.', body: 'We help brands adapt positioning, campaigns and content to local audiences instead of simply transferring existing marketing into another language.', items: ['Localized positioning', 'Campaigns', 'Creator partnerships', 'European & Chinese production', 'Market-entry support'], cta: 'Explore brand services'}},
    services: {label: 'What we do', title: 'One partner across the full journey.', intro: 'Five connected disciplines. Used individually or built into one cross-market operation.', items: [['Market Entry', 'Strategy, positioning and market selection.'], ['Localization', 'Language, culture, storytelling and platform adaptation.'], ['Platform Management', 'Account setup, publishing, optimization and reporting.'], ['Production', 'Social-first video, campaigns and local productions.'], ['Talent & Partnerships', 'Creator representation, brand partnerships and cross-market connections.']]},
    markets: {label: 'Europe ↔ China', title: 'Built for movement in both directions.', europeChina: {direction: 'Europe → China', title: 'Enter new platforms with local fluency.', body: ''}, chinaEurope: {direction: 'China → Europe', title: 'Adapt the story. Keep the identity.', body: ''}, expansion: 'Built between Europe and China. Designed to travel further.'},
    work: {label: 'Selected work', title: 'The proof belongs in the work.', body: 'We are building our first cross-market cases. Real work, real results — no invented success stories.', placeholders: ['Case study coming soon', 'Cross-market production', 'Creator localization'], status: 'Upcoming / placeholder', schema: ['Media', 'Case description', 'Metrics']},
    about: {label: 'Founder-led', title: 'Strategy and craft, in the same room.', intro: 'NATIVE is built by two complementary operators who connect commercial thinking with hands-on creative execution.', people: [{name: 'Daniel', focus: 'Strategy · Business Development · Partnerships · Cross-Market Strategy'}, {name: 'Timm', focus: 'Creative Direction · Production · Video · Content Execution'}]},
    final: {eyebrow: 'Where next?', title: 'New market. Same identity. Local relevance.', cta: 'Start a conversation'},
  },
  de: {
    label: 'Cross-cultural Media · Lokalisierung · Produktion', claim: 'Mach deine Marke im neuen Markt zu Hause.', intro: 'NATIVE unterstützt Creator und Marken beim Eintritt in neue Märkte – mit Strategie, Lokalisierung, Produktion, Plattformmanagement und Partnerschaften, ohne dabei die eigene Identität zu verlieren.', creatorCta: 'Ich bin Creator', brandCta: 'Ich bin eine Marke', marketNote: 'Europa ↔ China · gemacht für weitere Märkte',
    why: {label: 'Warum NATIVE', title: 'Content reist. Relevanz nicht von selbst.', body: 'Erfolgreicher Content lässt sich nicht einfach übersetzen und erneut veröffentlichen. Sprache, Plattformkultur, Storytelling, Schnitt und Erwartungen der Zielgruppe verändern sich von Markt zu Markt.', details: ['Sprache & Ton', 'Plattformkultur', 'Story & Schnitt', 'Creator & Zielgruppen']},
    audiences: {label: 'Zwei Perspektiven. Ein lokaler Anspruch.', creator: {kicker: 'Für Creator', title: 'Deine Stimme – auch in einem neuen Markt verstanden.', body: 'Wir helfen Creatorn dabei, bestehende Inhalte anzupassen, lokale Plattformen aufzubauen, neue Formate zu entwickeln und Partnerschaften im Zielmarkt zu erschließen.', items: ['Content-Lokalisierung', 'Plattformpräsenz', 'Account Management', 'Produktion', 'Partnerschaften & Talent'], cta: 'Creator Services ansehen'}, brand: {kicker: 'Für Marken', title: 'Teil der Kultur werden – nicht nur des Marktes.', body: 'Wir helfen Marken dabei, Positionierung, Kampagnen und Content an lokale Zielgruppen anzupassen – statt bestehendes Marketing einfach in eine andere Sprache zu übertragen.', items: ['Lokale Positionierung', 'Kampagnen', 'Creator-Partnerschaften', 'Produktion in Europa & China', 'Market-Entry Support'], cta: 'Marken Services ansehen'}},
    services: {label: 'Was wir tun', title: 'Ein Partner über den gesamten Prozess.', intro: 'Fünf verbundene Disziplinen – einzeln einsetzbar oder als gemeinsame Cross-Market Operation.', items: [['Market Entry', 'Strategie, Positionierung und Markteintritt.'], ['Localization', 'Sprache, Kultur, Storytelling und Plattformanpassung.'], ['Platform Management', 'Accountaufbau, Publishing, Optimierung und Reporting.'], ['Production', 'Social-first Video, Kampagnen und lokale Produktionen.'], ['Talent & Partnerships', 'Creator-Management, Markenkooperationen und internationale Partnerschaften.']]},
    markets: {label: 'Europa ↔ China', title: 'Für Bewegung in beide Richtungen.', europeChina: {direction: 'Europa → China', title: 'Neue Plattformen mit lokalem Verständnis erschließen.', body: ''}, chinaEurope: {direction: 'China → Europa', title: 'Die Story anpassen. Die Identität bewahren.', body: ''}, expansion: 'Zwischen Europa und China aufgebaut. Für weitere Märkte gedacht.'},
    work: {label: 'Selected Work', title: 'Die Arbeit spricht für sich.', body: 'Unsere ersten Cross-Market-Cases entstehen gerade. Echte Projekte, echte Ergebnisse – keine erfundenen Erfolgsgeschichten.', placeholders: ['Case Study folgt', 'Cross-Market Produktion', 'Creator-Lokalisierung'], status: 'Demnächst / Platzhalter', schema: ['Media', 'Case-Beschreibung', 'Kennzahlen']},
    about: {label: 'Founder-led', title: 'Strategie und Umsetzung an einem Tisch.', intro: 'NATIVE wird von zwei komplementären Machern aufgebaut, die kommerzielles Denken mit kreativer Umsetzung verbinden.', people: [{name: 'Daniel', focus: 'Strategie · Business Development · Partnerschaften · Cross-Market Strategy'}, {name: 'Timm', focus: 'Creative Direction · Produktion · Video · Content Execution'}]},
    final: {eyebrow: 'Wohin als Nächstes?', title: 'Neuer Markt. Gleiche Identität. Lokale Relevanz.', cta: 'Gespräch starten'},
  },
  zh: {
    label: '跨文化媒体 · 本地化 · 内容制作', claim: '让品牌真正融入当地市场。', intro: 'NATIVE 帮助品牌与创作者进入新的市场，从策略、本地化、内容制作到平台运营与商业合作，让内容适应当地文化，同时保留原有的品牌身份。', creatorCta: '我是创作者', brandCta: '我是品牌方', marketNote: '欧洲 ↔ 中国 · 模式可拓展至更多市场',
    why: {label: '为什么选择 NATIVE', title: '内容可以跨越市场，但真正的共鸣不会自动跟随。', body: '优秀的内容不能只靠翻译和重新发布。语言、平台文化、叙事方式、剪辑节奏以及受众习惯都会随着市场发生变化。', details: ['语言与语气', '平台文化', '叙事与剪辑', '创作者与受众']},
    audiences: {label: '双向视角，同一本地标准。', creator: {kicker: '创作者', title: '让你的内容，在新市场真正被理解。', body: '我们帮助创作者优化现有内容、建立本地平台账号、开发新的内容形式，并拓展当地品牌合作与商业机会.', items: ['内容本地化', '平台建设', '账号运营', '内容制作', '合作与艺人管理'], cta: '了解创作者服务'}, brand: {kicker: '品牌', title: '进入文化，而不只是进入市场。', body: '我们帮助品牌根据当地受众重新调整定位、内容与传播方式，而不是简单地把原有营销翻译成另一种语言。', items: ['本地化定位', '整合营销活动', '创作者合作', '欧洲与中国制作', '市场进入支持'], cta: '了解品牌服务'}},
    services: {label: '我们的工作', title: '一个伙伴，陪你走完整个市场拓展过程。', intro: '五项相互连接的专业能力，可独立合作，也可组合成完整的跨市场运营体系。', items: [['Market Entry', '市场进入策略与定位。'], ['Localization', '语言、文化、叙事与平台本地化。'], ['Platform Management', '账号搭建、发布、优化与数据报告。'], ['Production', '社交媒体视频、品牌活动与本地内容制作。'], ['Talent & Partnerships', '创作者管理、品牌合作与跨市场资源对接。']]},
    markets: {label: '欧洲 ↔ 中国', title: '为双向市场拓展而生。', europeChina: {direction: '欧洲 → 中国', title: '以真正本地化的方式进入新的平台与市场。', body: ''}, chinaEurope: {direction: '中国 → 欧洲', title: '调整表达方式，同时保留品牌本身的身份。', body: ''}, expansion: '从欧洲与中国之间出发，为更多市场而设计。'},
    work: {label: '精选案例', title: '作品本身，就是最好的证明。', body: '我们正在打造第一批跨市场案例。真实项目，真实结果，不用虚构的成功故事。', placeholders: ['案例即将上线', '跨市场制作', '创作者本地化'], status: '即将上线 / 占位内容', schema: ['影像', '案例说明', '数据指标']},
    about: {label: '创始人主导', title: '策略与创意执行，紧密结合。', intro: 'NATIVE 由两位能力互补的创始人共同建立，把商业思维与一线创意执行连接起来。', people: [{name: 'Daniel', focus: '市场策略 · 商务拓展 · 合作伙伴关系 · 跨市场战略'}, {name: 'Timm', focus: '创意指导 · 内容制作 · 视频 · 执行'}]},
    final: {eyebrow: '下一站？', title: '新的市场。保持原有身份，真正融入本地。', cta: '联系我们'},
  },
};
