export const locales = ['de','en','zh'] as const;
export type Locale = typeof locales[number];
export const defaultLocale:Locale='en';
export function isLocale(value:string):value is Locale{return locales.includes(value as Locale)}

export const copy = {
  de:{
    nav:{creators:'Für Creator',brands:'Für Marken',services:'Leistungen',about:'Über uns',contact:'Kontakt'},
    home:{eyebrow:'Cross-cultural media · localization · production',title:'Make your brand feel local.',lead:'NATIVE hilft Creatorn und Marken, in neuen Märkten so aufzutreten, dass ihr Content nicht übersetzt wirkt – sondern dort zu Hause ist.',creator:'Ich bin Creator',brand:'Ich bin eine Marke',problemTitle:'Content reist. Relevanz nicht automatisch.',problemLead:'Ein guter Post in Berlin ist nicht automatisch ein guter Post in Shanghai. Wir verbinden Strategie, kulturelle Lokalisierung, Plattform-Know-how und Produktion.',servicesTitle:'Von Market Entry bis Management.',servicesLead:'NATIVE begleitet den gesamten Weg – vom ersten Marktcheck bis zur langfristigen lokalen Präsenz.',marketsTitle:'Europe ↔ China. And beyond.',marketsLead:'Unser Startfokus verbindet europäische und chinesische Creator- und Markenwelten. Die Methodik ist bewusst länderübergreifend gedacht.'},
    serviceCards:[['Market Entry','Marktstrategie, Plattformwahl, Positionierung und Launchplanung.'],['Localization','Sprache, Hook, Schnitt, Caption und kulturelle Codes lokal adaptieren.'],['Platform Management','Accounts betreiben, publizieren, analysieren und kontinuierlich optimieren.'],['Production','Social-first Video, Commercials, Creator- und Event-Produktionen.'],['Talent & Partnerships','Creator vertreten, lokale Kontakte aufbauen und Kooperationen entwickeln.'],['Consulting','Cross-border Strategie für Marken, Creator, Agenturen und Managements.']],
    creators:{title:'Dein Content. Neue Märkte.',lead:'Wir helfen Creatorn, bestehende Reichweite in neue Kulturräume zu übersetzen – strategisch, kreativ und operativ.',body:['Nicht jeder bestehende Post muss neu produziert werden. Wir analysieren, was bereits funktioniert, was lokal angepasst werden sollte und welche Inhalte im Zielmarkt neu gedacht werden müssen.','NATIVE kann von Account Setup und Localization bis zur laufenden Betreuung und regionalen Talent Representation übernehmen.']},
    brands:{title:'Global denken. Lokal wirken.',lead:'Wir helfen Marken, in fremden Märkten nicht wie Gäste auszusehen.',body:['Für chinesische Unternehmen in Europa und europäische Marken in China verbinden wir Marktverständnis mit lokaler Kreativproduktion.','Das kann von einer einzelnen Kampagne bis zur langfristigen Content- und Plattformbetreuung reichen.']},
    services:{title:'One partner. Across cultures.',lead:'Unsere Leistungen sind modular – aber bewusst miteinander verzahnt.',body:['Market Entry & Strategy','Localization & Cultural Adaptation','Platform Management','Content & Video Production','Talent Management & Partnerships','Cross-border Consulting']},
    about:{title:'Built between cultures.',lead:'NATIVE verbindet Business-Verständnis, Content-Produktion und internationale Markterfahrung.',body:['Daniel Nonn – Co-Founder / Strategy & Partnerships','Timm – Co-Founder / Creative & Production','Unser Anspruch: keine Übersetzungsagentur, keine klassische Social-Media-Agentur, sondern eine lokale Schnittstelle zwischen Marke, Creator, Plattform und Kultur.']},
    contact:{title:'Where do you want to feel local?',lead:'Creator, Brand, Agentur oder potenzieller Partner? Lass uns über den Markt sprechen, den du als Nächstes erreichen willst.',cta:'Projekt anfragen'},
    footer:'Cross-cultural media, localization & production.'
  },
  en:{
    nav:{creators:'For Creators',brands:'For Brands',services:'Services',about:'About',contact:'Contact'},
    home:{eyebrow:'Cross-cultural media · localization · production',title:'Make your brand feel local.',lead:'NATIVE helps creators and brands enter new markets without looking translated — but genuinely at home.',creator:"I'm a Creator",brand:"I'm a Brand",problemTitle:'Content travels. Relevance doesn’t automatically.',problemLead:'A strong post in Berlin is not automatically a strong post in Shanghai. We combine strategy, cultural localization, platform expertise and production.',servicesTitle:'From market entry to management.',servicesLead:'NATIVE covers the full journey — from the first market assessment to a long-term local presence.',marketsTitle:'Europe ↔ China. And beyond.',marketsLead:'We start by connecting European and Chinese creator and brand ecosystems. The model is built to expand across markets.'},
    serviceCards:[['Market Entry','Market strategy, platform selection, positioning and launch planning.'],['Localization','Local adaptation of language, hooks, edits, captions and cultural codes.'],['Platform Management','Operate, publish, analyze and continuously optimize accounts.'],['Production','Social-first video, commercials, creator and event productions.'],['Talent & Partnerships','Represent creators, build local relationships and develop partnerships.'],['Consulting','Cross-border strategy for brands, creators, agencies and management teams.']],
    creators:{title:'Your content. New markets.',lead:'We help creators translate existing momentum into new cultural markets — strategically, creatively and operationally.',body:['Not every successful post needs to be recreated. We identify what travels, what needs local adaptation and what should be reimagined for the target market.','NATIVE can handle everything from account setup and localization to ongoing platform operations and regional talent representation.']},
    brands:{title:'Think global. Feel local.',lead:'We help brands enter foreign markets without looking foreign.',body:['For Chinese companies in Europe and European brands in China, we combine market understanding with local creative production.','Engagements can range from a single campaign to long-term content and platform management.']},
    services:{title:'One partner. Across cultures.',lead:'Our services are modular, but designed to work together.',body:['Market Entry & Strategy','Localization & Cultural Adaptation','Platform Management','Content & Video Production','Talent Management & Partnerships','Cross-border Consulting']},
    about:{title:'Built between cultures.',lead:'NATIVE combines business understanding, content production and international market experience.',body:['Daniel Nonn – Co-Founder / Strategy & Partnerships','Timm – Co-Founder / Creative & Production','Our ambition: not a translation agency, not a conventional social agency, but a local interface between brand, creator, platform and culture.']},
    contact:{title:'Where do you want to feel local?',lead:'Creator, brand, agency or potential partner? Let’s talk about the market you want to reach next.',cta:'Start a project'},
    footer:'Cross-cultural media, localization & production.'
  },
  zh:{
    nav:{creators:'创作者',brands:'品牌',services:'服务',about:'关于我们',contact:'联系我们'},
    home:{eyebrow:'跨文化媒体 · 本地化 · 内容制作',title:'让你的品牌真正融入当地。',lead:'NATIVE 帮助创作者与品牌进入新市场，让内容不只是“翻译过来”，而是真正符合当地文化与平台语境。',creator:'我是创作者',brand:'我是品牌',problemTitle:'内容可以跨境，相关性不会自动跨境。',problemLead:'在柏林表现出色的内容，不一定会在上海同样有效。我们将策略、文化本地化、平台经验与内容制作结合起来。',servicesTitle:'从市场进入到长期管理。',servicesLead:'NATIVE 覆盖完整链路——从市场评估到长期本地运营。',marketsTitle:'欧洲 ↔ 中国，以及更多市场。',marketsLead:'我们首先连接欧洲与中国的创作者及品牌生态，同时从一开始就为更多国家和地区预留扩展空间。'},
    serviceCards:[['市场进入','市场策略、平台选择、定位与上线规划。'],['内容本地化','对语言、开场、剪辑、文案及文化表达进行本地适配。'],['平台运营','账号运营、发布、数据分析与持续优化。'],['内容制作','社交媒体视频、商业广告、创作者及活动内容制作。'],['艺人管理与合作','代表创作者拓展当地资源、商务合作与品牌机会。'],['跨境咨询','为品牌、创作者、机构和经纪公司提供跨境策略。']],
    creators:{title:'你的内容，进入新的市场。',lead:'我们帮助创作者把已有的影响力带入新的文化市场，并在策略、创意和运营上完成本地化。',body:['并不是每一条成功内容都需要重新拍摄。我们会判断哪些内容可以直接跨市场传播，哪些需要本地调整，哪些应该为目标市场重新构思。','NATIVE 可负责账号搭建、内容本地化、日常运营，进一步还可提供区域性艺人管理与商务合作支持。']},
    brands:{title:'全球思考，本地表达。',lead:'我们帮助品牌进入海外市场，同时避免“外来品牌感”。',body:['面向进入欧洲的中国企业以及进入中国的欧洲品牌，我们把市场理解与本地创意制作结合起来。','合作可以是一场单独的营销活动，也可以延伸到长期内容与平台运营。']},
    services:{title:'一个伙伴，连接不同文化。',lead:'我们的服务可以独立选择，也可以组合成完整的跨境增长体系。',body:['市场进入与策略','内容本地化与文化适配','平台运营','内容与视频制作','艺人管理与商务合作','跨境咨询']},
    about:{title:'生于文化之间。',lead:'NATIVE 将商业理解、内容制作能力与国际市场经验连接起来。',body:['Daniel Nonn – 联合创始人 / 战略与合作','Timm – 联合创始人 / 创意与制作','我们的目标不是做传统翻译公司，也不是普通社交媒体代理商，而是成为品牌、创作者、平台与本地文化之间的连接层。']},
    contact:{title:'你想在哪个市场真正“本地化”？',lead:'无论你是创作者、品牌、机构还是潜在合作伙伴，都可以和我们聊聊你下一步希望进入的市场。',cta:'发起项目'},
    footer:'跨文化媒体、本地化与内容制作。'
  }
} as const;
