import type {Locale} from './i18n';
export type ServiceBlock={eyebrow:string;title:string;body:string;lead:string;items:string[];lead2?:string;items2?:string[];closing:string;creator?:string;brand?:string};
type ServicesCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;creators:string;brands:string};together:ServiceBlock;services:ServiceBlock[];models:{title:string;body:string;items:Array<[string,string]>;closing:string};markets:{title:string;body:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};examples:{title:string;items:Array<{label:string;title:string;lead:string;services:string[]}>;line:string};final:{title:string;body:string;cta:string}};
export const servicesCopy:Record<Locale,ServicesCopy>={
en:{
seo:{title:'Services | NATIVE',description:'Connected market-entry, localization, platform management, production, talent and partnership services for creators and brands.'},
hero:{eyebrow:'SERVICES',title:'Strategy, localization and execution — connected.',body:'NATIVE combines the services required to make creators and brands work in new markets. From the first market decision to local production, platform management and partnerships, the individual pieces are designed to work together.',primary:'Start a conversation',creators:'For Creators',brands:'For Brands'},
together:{eyebrow:'HOW SERVICES WORK TOGETHER',title:'Not every project needs everything.',body:'Some clients need only a market-entry strategy. Others need full localization, account management, production and local partnerships.',lead:'NATIVE can work as:',items:['a strategic advisor','a localization partner','a platform operator','a production partner','a creator and partnership partner','or a combination of these roles'],closing:'The scope should follow the market challenge — not a fixed agency package.'},
services:[
{eyebrow:'01 / MARKET ENTRY',title:'Start with the right market decision.',body:'Before content is translated, accounts are opened or campaigns are produced, the market needs to make sense.',lead:'NATIVE helps answer:',items:['Is the market relevant for the creator or brand?','Which audience should be prioritized?','Which platforms matter?','Which products, topics or formats should lead?','What can be reused?','What needs to be localized?','What should be produced locally?','Should the market be tested first or entered at scale?'],lead2:'Possible deliverables:',items2:['market assessment','competitor and category review','audience definition','platform selection','positioning','launch strategy','content priorities','market-entry roadmap'],closing:''},
{eyebrow:'02 / LOCALIZATION',title:'Translate the context, not only the language.',body:'Localization is at the center of NATIVE. The goal is not to make content sound translated. The goal is to make it feel as though the creator or brand understands the market.',lead:'Localization can involve:',items:['language','tone of voice','hooks','captions','storytelling','editing','pacing','cultural references','visual codes','platform conventions','creator selection','campaign concepts','product messaging'],closing:'Depending on the project, NATIVE can adapt existing assets or develop new local versions.',creator:'For creators: The identity stays recognizable while the content adapts to local audience behavior.',brand:'For brands: The brand remains consistent while communication becomes locally relevant.'},
{eyebrow:'03 / PLATFORM MANAGEMENT',title:'A local presence needs ongoing operation.',body:'Launching an account is only the beginning.',lead:'NATIVE can support the operational side of local platform presence, including:',items:['account setup','localized profile creation','publishing','titles and captions','upload planning','content calendars','platform optimization','performance monitoring','reporting','content recommendations','coordination with local partners','ongoing strategic refinement'],closing:'The exact scope depends on platform, market and client needs. NATIVE can manage an entire local presence or work alongside an internal team.'},
{eyebrow:'04 / PRODUCTION',title:'When adaptation is not enough, create locally.',body:'Some content can travel through smart localization. Other content should be created specifically for the target audience.',lead:'NATIVE develops and produces:',items:['social-first video','short-form content','product films','brand films','creator campaigns','interviews','event coverage','travel content','launch content','UGC-style productions','campaign photography','localized advertising assets'],lead2:'Production can include:',items2:['concept development','creative direction','scripting','casting','locations','filming','editing','subtitles','voiceover','localization','final platform versions'],closing:'The objective is not simply to produce more content. It is to produce the right content for the market.'},
{eyebrow:'05 / TALENT & PARTNERSHIPS',title:'Local relevance can become commercial opportunity.',body:'Once creators or brands build relevance in a new market, NATIVE can help turn that presence into meaningful relationships and opportunities.',lead:'For creators, this can include:',items:['local brand introductions','campaign opportunities','creator collaborations','events','media opportunities','commercial negotiations','local representation','market-specific talent management'],lead2:'For brands, this can include:',items2:['creator sourcing','local hosts and talent','campaign partnerships','collaboration concepts','outreach','coordination','briefing','production','long-term creator relationships'],closing:'NATIVE can work alongside existing management teams, agencies and internal brand teams. The goal is not simply access to contacts. It is finding the right relationships for the market.'}] ,
models:{title:'One service or the full journey.',body:'NATIVE does not require every client to buy a full-service package.',items:[['STRATEGY PROJECT','A defined market-entry or localization project with a clear deliverable.'],['LOCALIZATION PARTNER','Ongoing adaptation of existing content and campaigns.'],['MONTHLY PLATFORM MANAGEMENT','Ongoing publishing, optimization and reporting.'],['PRODUCTION PROJECT','A specific local production, campaign or content package.'],['FULL MARKET SUPPORT','Strategy, localization, platform management, production and partnerships combined.'],['TALENT / PARTNERSHIP REPRESENTATION','Market-specific commercial support and representation.']],closing:'The final scope is tailored to the client, market and objective.'},
markets:{title:'Built between Europe and China. Designed to travel further.',body:'Our initial operating focus connects two markets with very different platforms, communication cultures and audience expectations.',fromEurope:'Europe → China',fromEuropeBody:'Market entry, localization, Chinese platform management, production and partnerships.',fromChina:'China → Europe',fromChinaBody:'European positioning, localization, content production, creator campaigns and local market execution.',line:'The service model is built around cultural adaptation and can expand wherever clients need to communicate across markets.'},
examples:{title:'Different challenges. Different combinations.',items:[{label:'EXAMPLE 01',title:'European Creator → China',lead:'Possible combination:',services:['Market Entry','Localization','Platform Management','Production','Talent & Partnerships']},{label:'EXAMPLE 02',title:'Chinese Brand → Europe',lead:'Possible combination:',services:['Market Entry','Localization','Production','Creator Partnerships']},{label:'EXAMPLE 03',title:'International Brand Campaign',lead:'Possible combination:',services:['Localization','Production','Local Talent','Campaign Execution']}],line:'The combination follows the challenge — not a prebuilt package.'},
final:{title:'Start with the challenge. Build the right combination.',body:'Tell us where you are today, which market you want to reach and what is already in place. We can define the next step from there.',cta:'Start a conversation'}},
de:{
seo:{title:'Leistungen | NATIVE',description:'Vernetzte Leistungen für Markteintritt, Lokalisierung, Plattformmanagement, Produktion, Talent und Partnerschaften.'},
hero:{eyebrow:'LEISTUNGEN',title:'Strategie, Lokalisierung und Umsetzung – miteinander verbunden.',body:'NATIVE verbindet die Leistungen, die Creator und Marken für neue Märkte benötigen. Von der ersten Marktentscheidung über Lokalisierung und Produktion bis zu Plattformmanagement und Partnerschaften greifen die einzelnen Bausteine ineinander.',primary:'Gespräch starten',creators:'Für Creator',brands:'Für Marken'},
together:{eyebrow:'ZUSAMMENSPIEL',title:'Nicht jedes Projekt braucht alles.',body:'Manche Kunden benötigen zunächst nur eine Markteintrittsstrategie. Andere brauchen Lokalisierung, Plattformmanagement, Produktion und lokale Partnerschaften aus einer Hand.',lead:'NATIVE kann arbeiten als:',items:['strategischer Berater','Localization-Partner','Plattformbetreiber','Produktionspartner','Creator- und Partnership-Partner','oder als Kombination mehrerer Rollen'],closing:'Der Umfang richtet sich nach der Herausforderung im Markt – nicht nach einem starren Agenturpaket.'},
services:[
{eyebrow:'01 / MARKET ENTRY',title:'Der richtige Markteintritt beginnt mit der richtigen Entscheidung.',body:'Bevor Content übersetzt, Accounts eröffnet oder Kampagnen produziert werden, muss der Markt überhaupt sinnvoll sein.',lead:'NATIVE hilft bei Fragen wie:',items:['Ist der Markt für Creator oder Marke relevant?','Welche Zielgruppe sollte priorisiert werden?','Welche Plattformen sind wichtig?','Welche Produkte, Themen oder Formate sollten im Mittelpunkt stehen?','Was kann weiterverwendet werden?','Was muss lokalisiert werden?','Was sollte lokal produziert werden?','Sollte zunächst getestet oder direkt größer gestartet werden?'],lead2:'Mögliche Leistungen:',items2:['Marktanalyse','Wettbewerbs- und Kategorieanalyse','Zielgruppendefinition','Plattformauswahl','Positionierung','Launch-Strategie','Content-Priorisierung','Market-Entry-Roadmap'],closing:''},
{eyebrow:'02 / LOCALIZATION',title:'Nicht nur die Sprache übersetzen. Den Kontext übertragen.',body:'Lokalisierung steht im Zentrum von NATIVE. Das Ziel ist nicht, dass Content übersetzt klingt. Er soll wirken, als würde Creator oder Marke den jeweiligen Markt wirklich verstehen.',lead:'Lokalisierung kann betreffen:',items:['Sprache','Tonalität','Hooks','Captions','Storytelling','Schnitt','Tempo','kulturelle Referenzen','Bildsprache','Plattformkonventionen','Creator-Auswahl','Kampagnenideen','Produktkommunikation'],closing:'Je nach Projekt passt NATIVE bestehende Assets an oder entwickelt neue lokale Versionen.',creator:'Für Creator: Die eigene Identität bleibt erkennbar, während sich der Content an das Verhalten der lokalen Zielgruppe anpasst.',brand:'Für Marken: Die Markenidentität bleibt konsistent, während die Kommunikation lokal relevant wird.'},
{eyebrow:'03 / PLATFORM MANAGEMENT',title:'Eine lokale Präsenz braucht laufende Betreuung.',body:'Ein Account-Launch ist nur der Anfang.',lead:'NATIVE kann die operative Seite einer lokalen Plattformpräsenz unterstützen, zum Beispiel durch:',items:['Accountaufbau','lokalisierte Profile','Publishing','Titel und Captions','Upload-Planung','Content-Kalender','Plattformoptimierung','Performance-Monitoring','Reporting','Content-Empfehlungen','Koordination lokaler Partner','laufende strategische Weiterentwicklung'],closing:'Der genaue Umfang richtet sich nach Plattform, Markt und Kunde. NATIVE kann die gesamte lokale Präsenz betreuen oder mit einem bestehenden internen Team zusammenarbeiten.'},
{eyebrow:'04 / PRODUCTION',title:'Wenn Anpassung nicht reicht, entsteht Content neu vor Ort.',body:'Manche Inhalte lassen sich durch gute Lokalisierung übertragen. Andere sollten gezielt für die jeweilige Zielgruppe entstehen.',lead:'NATIVE entwickelt und produziert:',items:['Social-first Video','Short-Form Content','Produktfilme','Brand-Filme','Creator-Kampagnen','Interviews','Event Coverage','Travel Content','Launch-Content','UGC-orientierte Produktionen','Kampagnenfotografie','lokalisierte Advertising Assets'],lead2:'Produktion kann umfassen:',items2:['Konzeption','Creative Direction','Skripting','Casting','Locations','Dreh','Editing','Untertitel','Voiceover','Lokalisierung','finale Plattformversionen'],closing:'Das Ziel ist nicht einfach mehr Content. Es ist der richtige Content für den jeweiligen Markt.'},
{eyebrow:'05 / TALENT & PARTNERSHIPS',title:'Aus lokaler Relevanz können kommerzielle Chancen entstehen.',body:'Wenn Creator oder Marken in einem neuen Markt Relevanz aufbauen, kann NATIVE dabei helfen, daraus sinnvolle Beziehungen und Geschäftsmöglichkeiten zu entwickeln.',lead:'Für Creator kann das umfassen:',items:['Kontakte zu lokalen Marken','Kampagnenmöglichkeiten','Creator-Kooperationen','Events','Medienmöglichkeiten','kommerzielle Verhandlungen','lokale Repräsentation','marktspezifisches Talent Management'],lead2:'Für Marken kann das umfassen:',items2:['Creator-Sourcing','lokale Hosts und Talents','Kampagnenpartnerschaften','Kooperationskonzepte','Ansprache','Koordination','Briefing','Produktion','langfristige Creator-Beziehungen'],closing:'NATIVE kann mit bestehenden Managements, Agenturen und internen Brand-Teams zusammenarbeiten. Das Ziel ist nicht einfach Zugang zu Kontakten, sondern die richtigen Beziehungen für den jeweiligen Markt.'}],
models:{title:'Eine Leistung oder der gesamte Prozess.',body:'Bei NATIVE muss nicht jeder Kunde ein Full-Service-Paket buchen.',items:[['STRATEGIEPROJEKT','Ein klar definiertes Market-Entry- oder Localization-Projekt mit konkretem Ergebnis.'],['LOCALIZATION PARTNER','Laufende Anpassung bestehender Inhalte und Kampagnen.'],['MONATLICHES PLATFORM MANAGEMENT','Laufendes Publishing, Optimierung und Reporting.'],['PRODUKTIONSPROJEKT','Eine konkrete lokale Produktion, Kampagne oder ein Content-Paket.'],['FULL MARKET SUPPORT','Strategie, Lokalisierung, Plattformmanagement, Produktion und Partnerschaften kombiniert.'],['TALENT / PARTNERSHIP REPRESENTATION','Marktspezifische kommerzielle Betreuung und Repräsentation.']],closing:'Der finale Umfang richtet sich nach Kunde, Markt und Ziel.'},
markets:{title:'Zwischen Europa und China aufgebaut. Für weitere Märkte gedacht.',body:'Unser erster operativer Fokus verbindet zwei Märkte mit sehr unterschiedlichen Plattformen, Kommunikationskulturen und Zielgruppenerwartungen.',fromEurope:'Europa → China',fromEuropeBody:'Markteintritt, Lokalisierung, chinesisches Plattformmanagement, Produktion und Partnerschaften.',fromChina:'China → Europa',fromChinaBody:'Europäische Positionierung, Lokalisierung, Content-Produktion, Creator-Kampagnen und lokale Marktumsetzung.',line:'Das Leistungsmodell basiert auf kultureller Anpassung und kann überall dort erweitert werden, wo Kunden marktübergreifend kommunizieren müssen.'},
examples:{title:'Unterschiedliche Herausforderungen. Unterschiedliche Kombinationen.',items:[{label:'BEISPIEL 01',title:'Europäischer Creator → China',lead:'Mögliche Kombination:',services:['Market Entry','Localization','Platform Management','Production','Talent & Partnerships']},{label:'BEISPIEL 02',title:'Chinesische Marke → Europa',lead:'Mögliche Kombination:',services:['Market Entry','Localization','Production','Creator Partnerships']},{label:'BEISPIEL 03',title:'Internationale Brand-Kampagne',lead:'Mögliche Kombination:',services:['Localization','Production','Local Talent','Campaign Execution']}],line:'Die Kombination richtet sich nach der Herausforderung – nicht nach einem vorgefertigten Paket.'},
final:{title:'Starte mit der Herausforderung. Daraus entsteht die richtige Lösung.',body:'Sag uns, wo du heute stehst, welchen Markt du erreichen möchtest und was bereits vorhanden ist. Daraus können wir gemeinsam den nächsten sinnvollen Schritt definieren.',cta:'Gespräch starten'}},
zh:{
seo:{title:'服务 | NATIVE',description:'为创作者与品牌提供相互连接的市场进入、本地化、平台运营、内容制作与合作资源服务。'},
hero:{eyebrow:'服务',title:'从策略到本地化，再到执行，完整衔接。',body:'NATIVE 将创作者与品牌进入新市场所需要的关键能力整合在一起。从市场判断、本地化与内容制作，到平台运营与合作资源，各个环节彼此连接。',primary:'联系我们',creators:'面向创作者',brands:'面向品牌'},
together:{eyebrow:'服务协作',title:'不是每一个项目，都需要所有服务。',body:'有些客户只需要市场进入策略，有些则需要完整的本地化、平台运营、内容制作与当地合作资源。',lead:'NATIVE 可以作为：',items:['市场策略顾问','本地化合作伙伴','平台运营伙伴','内容制作伙伴','创作者与合作资源伙伴','或多个角色的组合'],closing:'服务范围应该根据真实的市场挑战来决定，而不是套用固定的代理商套餐。'},
services:[
{eyebrow:'01 / 市场进入',title:'正确的市场进入，始于正确的判断。',body:'在翻译内容、搭建账号或制作活动之前，首先需要确认这个市场本身是否值得进入。',lead:'NATIVE 帮助回答：',items:['这个市场是否适合品牌或创作者？','哪类受众应该优先？','哪些平台最重要？','哪些产品、主题或内容形式应该率先进入？','哪些现有资产可以继续利用？','哪些内容必须本地化？','哪些内容应该在当地重新制作？','应该先进行测试，还是直接规模化进入？'],lead2:'可能的服务包括：',items2:['市场评估','竞争与品类分析','受众定义','平台选择','定位','上线策略','内容优先级','市场进入路线图'],closing:''},
{eyebrow:'02 / 本地化',title:'不只是翻译语言，而是转换整个传播语境。',body:'本地化是 NATIVE 的核心能力之一。目标不是让内容看起来像翻译过来的，而是让品牌或创作者显得真正理解当地市场。',lead:'本地化可能包括：',items:['语言','语气','开场','文案','叙事方式','剪辑','节奏','文化语境','视觉表达','平台习惯','创作者选择','活动创意','产品信息'],closing:'根据项目情况，NATIVE 可以调整现有素材，也可以开发新的本地版本。',creator:'对于创作者：保留个人风格，同时让内容适应当地受众的观看习惯。',brand:'对于品牌：保持品牌一致性，同时让传播方式真正符合本地市场。'},
{eyebrow:'03 / 平台运营',title:'真正的本地平台影响力，需要持续运营。',body:'账号上线只是开始。',lead:'NATIVE 可以支持当地平台运营中的执行工作，包括：',items:['账号搭建','本地化账号资料','内容发布','标题与文案','发布计划','内容日历','平台优化','数据监测','数据报告','内容建议','当地合作伙伴协调','持续的策略优化'],closing:'具体服务范围会根据平台、市场与客户需求进行调整。 NATIVE 可以完整运营当地平台，也可以与客户现有团队协作。'},
{eyebrow:'04 / 内容制作',title:'当本地化还不够，就为当地市场重新创作。',body:'有些内容可以通过合理的本地化进入新的市场，有些则应该直接为目标受众重新制作。',lead:'NATIVE 可以开发并制作：',items:['社交媒体视频','短视频内容','产品影片','品牌影片','创作者合作内容','采访','活动内容','旅行内容','新品发布内容','UGC 风格内容','品牌活动摄影','本地化广告素材'],lead2:'制作可能包括：',items2:['创意策划','创意指导','脚本','选角','场地','拍摄','剪辑','字幕','配音','本地化','最终平台版本'],closing:'目标不是简单地制作更多内容，而是为市场制作真正合适的内容。'},
{eyebrow:'05 / 创作者管理与合作',title:'真正的本地影响力，可以进一步转化为商业机会。',body:'当创作者或品牌在新的市场建立起真正的相关性后，NATIVE 可以帮助把这种影响力发展为有价值的合作关系与商业机会。',lead:'对于创作者，可以包括：',items:['当地品牌资源','商业活动机会','创作者合作','活动机会','媒体机会','商务谈判','当地代表','特定市场的艺人管理'],lead2:'对于品牌，可以包括：',items2:['创作者筛选','当地主持人与人才','品牌活动合作','合作创意','商务沟通','协调','Briefing','内容制作','长期创作者关系'],closing:'NATIVE 可以与现有管理团队、代理商与品牌内部团队协作。目标不只是获得联系人，而是找到真正适合市场的合作关系。'}],
models:{title:'可以是一项服务，也可以是完整的市场支持。',body:'NATIVE 不要求每一位客户都购买完整服务。',items:[['策略项目','针对市场进入或本地化制定明确的项目方案与交付成果。'],['长期本地化合作','持续调整现有内容与品牌活动。'],['月度平台运营','持续发布、优化与数据报告。'],['内容制作项目','针对当地市场完成一次具体的拍摄、品牌活动或内容项目。'],['完整市场支持','将策略、本地化、平台运营、内容制作与合作资源整合。'],['艺人 / 合作资源管理','针对特定市场提供商业支持与代表服务。']],closing:'最终服务范围会根据客户、市场与目标进行定制。'},
markets:{title:'从欧洲与中国之间出发，为更多市场而设计。',body:'我们的初始业务重点，是连接两个在平台、传播文化与受众期待上差异明显的市场。',fromEurope:'欧洲 → 中国',fromEuropeBody:'市场进入、本地化、中国平台运营、内容制作与合作资源。',fromChina:'中国 → 欧洲',fromChinaBody:'欧洲市场定位、本地化、内容制作、创作者合作与当地市场执行。',line:'NATIVE 的服务模式建立在跨文化适配之上，因此可以根据客户需求扩展到更多市场。'},
examples:{title:'不同的问题，需要不同的服务组合。',items:[{label:'示例 01',title:'欧洲创作者 → 中国',lead:'可能的组合：',services:['Market Entry','Localization','Platform Management','Production','Talent & Partnerships']},{label:'示例 02',title:'中国品牌 → 欧洲',lead:'可能的组合：',services:['Market Entry','Localization','Production','Creator Partnerships']},{label:'示例 03',title:'国际品牌活动',lead:'可能的组合：',services:['Localization','Production','Local Talent','Campaign Execution']}],line:'服务组合取决于真实的市场挑战，而不是预设的固定套餐。'},
final:{title:'从真实的问题开始，找到最合适的服务组合。',body:'告诉我们你现在的情况、希望进入的市场以及已经具备的资源，我们可以从这里一起定义下一步。',cta:'联系我们'}}};
