import type {Locale} from './i18n';
export type ServiceBlock={eyebrow:string;title:string;body:string;lead:string;items:string[];lead2?:string;items2?:string[];closing:string;creator?:string;brand?:string};
type ServicesCopy={seo:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;creators:string;brands:string};together:ServiceBlock;services:ServiceBlock[];models:{title:string;body:string;items:Array<[string,string]>;closing:string};markets:{title:string;body:string;fromEurope:string;fromEuropeBody:string;fromChina:string;fromChinaBody:string;line:string};examples:{title:string;items:Array<{label:string;title:string;lead:string;services:string[]}>;line:string};final:{title:string;body:string;cta:string}};
export const servicesCopy:Record<Locale,ServicesCopy>={
en:{
seo:{title:'Services | NATIVE',description:'Connected market-entry, localization, platform management, production, talent and partnership services for creators and brands.'},
hero:{eyebrow:'SERVICES',title:'Strategy, localization and execution — built to work together.',body:'NATIVE brings together the areas creators and brands need when entering new markets. Depending on the project, they can work independently, in combination or as one connected process from first market check to local execution.',primary:'Start a conversation',creators:'For Creators',brands:'For Brands'},
together:{eyebrow:'HOW SERVICES WORK TOGETHER',title:'Not every project needs everything.',body:'Some clients need a clear market assessment first. Others need localization, platform management, production and partnerships working together.',lead:'Depending on the project, NATIVE can act as:',items:['a strategic partner','a localization partner','a platform management partner','a production partner','a creator and partnerships partner','or a combination of several roles'],closing:'The scope should follow what the market actually requires, not a fixed agency package.'},
services:[
{eyebrow:'01 / MARKET ENTRY',title:'The right entry starts with a clear view of the market.',body:'Before accounts are opened, content is adapted or campaigns are produced, it needs to be clear whether the market makes sense and what the right way in looks like.',lead:'That can include questions such as:',items:['Is the market relevant for the creator or brand?','Which audience should come first?','Which platforms actually matter?','Which products, topics or formats should lead?','What can be reused?','What needs localization?','What should be produced locally?','Should the market be tested first or entered at a larger scale?'],lead2:'Possible services:',items2:['market assessment','competitor and category analysis','audience definition','platform selection','positioning','launch strategy','content prioritization','market-entry roadmap'],closing:''},
{eyebrow:'02 / LOCALIZATION',title:'Do not just translate the language. Adapt the whole context.',body:'Localization sits at the center of NATIVE.\n\nContent should not feel translated. It should feel as though the creator or brand genuinely understands the market.',lead:'Depending on the project, that can involve:',items:['language','tone','hooks','captions','storytelling','editing','pacing','cultural references','visual language','platform logic','creator selection','campaign ideas','product messaging'],closing:'NATIVE can adapt existing assets or develop new local versions when adaptation alone is not enough.',creator:'For creators: The identity stays recognizable while the content adapts to local viewing habits and platforms.',brand:'For brands: The brand identity stays consistent while the communication becomes more natural and relevant locally.'},
{eyebrow:'03 / PLATFORM MANAGEMENT',title:'A local presence needs ongoing development.',body:'Launching the account is only the beginning.\n\nNATIVE can manage the operational side of local platforms or support existing teams.',lead:'Possible services:',items:['account setup','localized profiles','publishing','titles and captions','upload planning','content calendars','platform optimization','performance monitoring','reporting','content recommendations','coordination with local partners','ongoing strategic refinement'],closing:'The exact scope depends on the platform, market and project.'},
{eyebrow:'04 / PRODUCTION',title:'When adaptation is not enough, create locally.',body:'Some content can travel through smart localization. Other content should be developed specifically for the audience in that market.',lead:'NATIVE can develop and produce:',items:['social-first video','short-form content','product films','brand films','creator campaigns','interviews','event content','travel content','launch content','UGC-style productions','campaign photography','localized advertising assets'],lead2:'Production can include:',items2:['concept development','creative direction','scripting','casting','locations','filming','editing','subtitles','voiceover','localization','final platform versions'],closing:'The goal is not to produce more content. It is to produce the right content for the market.'},
{eyebrow:'05 / TALENT & PARTNERSHIPS',title:'Local relevance can lead to real business opportunities.',body:'When creators or brands become visible and relevant in a new market, new opportunities for partnerships and commercial collaboration can follow.',lead:'For creators, that can include:',items:['local brand introductions','campaign opportunities','creator collaborations','events','media opportunities','commercial negotiations','local representation','market-specific talent management'],lead2:'For brands, that can include:',items2:['creator sourcing','local hosts and talent','campaign partnerships','collaboration concepts','outreach and coordination','briefing','production','long-term creator relationships'],closing:'NATIVE can work alongside existing management teams, agencies and internal teams.\n\nThe goal is not simply to make introductions. It is to build the right relationships in the relevant market.'}] ,
models:{title:'One service or the full process.',body:'Not every client needs full service.\n\nDepending on the project, NATIVE can support one specific area or connect several services into one process.',items:[['STRATEGY PROJECT','A clearly defined market-entry or localization project with a specific outcome.'],['LOCALIZATION PARTNER','Ongoing adaptation of existing content and campaigns.'],['PLATFORM MANAGEMENT','Ongoing publishing, optimization and reporting.'],['PRODUCTION PROJECT','A specific local production, campaign or content package.'],['FULL MARKET SUPPORT','Strategy, localization, platform management, production and partnerships combined.'],['TALENT / PARTNERSHIP REPRESENTATION','Market-specific commercial support and representation.']],closing:'The final scope depends on the client, market and objective.'},
markets:{title:'Between Europe and China. Built to go further.',body:'Our first operational focus connects two markets that differ significantly in platforms, communication culture and audience expectations.',fromEurope:'Europe → China',fromEuropeBody:'Market Entry, Localization, Chinese Platform Management, Production and Partnerships.',fromChina:'China → Europe',fromChinaBody:'European positioning, Localization, Content Production, Creator Campaigns and local market execution.',line:'The approach can extend wherever communication needs to work across cultural and market boundaries.'},
examples:{title:'Different challenges need different combinations.',items:[{label:'EXAMPLE 01',title:'European Creator → China',lead:'Possible combination:',services:['Market Entry','Localization','Platform Management','Production','Talent & Partnerships']},{label:'EXAMPLE 02',title:'Chinese Brand → Europe',lead:'Possible combination:',services:['Market Entry','Localization','Production','Creator Partnerships']},{label:'EXAMPLE 03',title:'International Brand Campaign',lead:'Possible combination:',services:['Localization','Production','Local Talent','Campaign Execution']}],line:'The combination follows the challenge, not a prebuilt package.'},
final:{title:'Understand the challenge first. Then build the right solution.',body:'Tell us where you are today, which market you want to reach and what is already in place. From there, we can define the next step.',cta:'Start a conversation'}},
de:{
seo:{title:'Leistungen | NATIVE',description:'Vernetzte Leistungen für Markteintritt, Lokalisierung, Plattformmanagement, Produktion, Talent und Partnerschaften.'},
hero:{eyebrow:'LEISTUNGEN',title:'Strategie, Lokalisierung und Umsetzung – sinnvoll verbunden.',body:'NATIVE verbindet die Bereiche, die Creator und Marken für neue Märkte brauchen. Je nach Projekt einzeln, kombiniert oder als durchgängige Begleitung vom ersten Marktcheck bis zur Umsetzung vor Ort.',primary:'Gespräch starten',creators:'Für Creator',brands:'Für Marken'},
together:{eyebrow:'ZUSAMMENSPIEL',title:'Nicht jedes Projekt braucht alles.',body:'Manche Kunden brauchen zunächst nur eine klare Markteinschätzung. Andere möchten Lokalisierung, Plattformmanagement, Produktion und Partnerschaften aus einer Hand.',lead:'NATIVE kann je nach Bedarf unterschiedliche Rollen übernehmen:',items:['strategischer Partner','Localization-Partner','Plattformmanagement','Produktionspartner','Creator- und Partnership-Partner','oder mehrere dieser Bereiche kombiniert'],closing:'Entscheidend ist nicht ein festes Agenturpaket, sondern das, was im jeweiligen Markt tatsächlich gebraucht wird.'},
services:[
{eyebrow:'01 / MARKET ENTRY',title:'Der richtige Einstieg beginnt mit einem klaren Blick auf den Markt.',body:'Bevor Accounts eröffnet, Content angepasst oder Kampagnen produziert werden, muss klar sein, ob und wie der Markt überhaupt sinnvoll erschlossen werden kann.',lead:'Dabei geht es zum Beispiel um Fragen wie:',items:['Ist der Markt für Creator oder Marke relevant?','Welche Zielgruppe sollte zuerst angesprochen werden?','Welche Plattformen spielen wirklich eine Rolle?','Welche Produkte, Themen oder Formate sollten im Mittelpunkt stehen?','Was kann weitergenutzt werden?','Was muss lokalisiert werden?','Was sollte vor Ort neu produziert werden?','Ist ein Test sinnvoll oder ein direkter größerer Einstieg?'],lead2:'Mögliche Leistungen:',items2:['Marktanalyse','Wettbewerbs- und Kategorieanalyse','Zielgruppendefinition','Plattformauswahl','Positionierung','Launch-Strategie','Content-Priorisierung','Market-Entry-Roadmap'],closing:''},
{eyebrow:'02 / LOCALIZATION',title:'Nicht nur Sprache übersetzen. Den gesamten Kontext mitdenken.',body:'Lokalisierung steht im Zentrum von NATIVE.\n\nContent soll nicht übersetzt wirken, sondern so, als würde Creator oder Marke den jeweiligen Markt wirklich verstehen.',lead:'Je nach Projekt kann das betreffen:',items:['Sprache','Tonalität','Hooks','Captions','Storytelling','Schnitt','Tempo','kulturelle Referenzen','Bildsprache','Plattformlogik','Creator-Auswahl','Kampagnenideen','Produktkommunikation'],closing:'NATIVE passt bestehende Inhalte an oder entwickelt neue lokale Versionen, wenn eine reine Anpassung nicht ausreicht.',creator:'Für Creator: Die eigene Handschrift bleibt erkennbar, während sich der Content an lokale Sehgewohnheiten und Plattformen anpasst.',brand:'Für Marken: Die Markenidentität bleibt bestehen, während die Kommunikation vor Ort natürlicher und relevanter wird.'},
{eyebrow:'03 / PLATFORM MANAGEMENT',title:'Eine lokale Präsenz muss laufend weiterentwickelt werden.',body:'Mit dem Account-Launch beginnt die eigentliche Arbeit erst.\n\nNATIVE kann die operative Betreuung lokaler Plattformen übernehmen oder bestehende Teams dabei unterstützen.',lead:'Mögliche Leistungen:',items:['Accountaufbau','lokalisierte Profile','Publishing','Titel und Captions','Upload-Planung','Content-Kalender','Plattformoptimierung','Performance-Monitoring','Reporting','Content-Empfehlungen','Koordination lokaler Partner','laufende strategische Weiterentwicklung'],closing:'Der genaue Umfang richtet sich nach Plattform, Markt und Projekt.'},
{eyebrow:'04 / PRODUCTION',title:'Wenn Anpassung nicht reicht, entsteht Content neu vor Ort.',body:'Manche Inhalte lassen sich sinnvoll lokalisieren. Andere sollten direkt für die Zielgruppe im jeweiligen Markt entwickelt werden.',lead:'NATIVE entwickelt und produziert zum Beispiel:',items:['Social-first Video','Short-Form Content','Produktfilme','Brand-Filme','Creator-Kampagnen','Interviews','Event Content','Travel Content','Launch Content','UGC-orientierte Produktionen','Kampagnenfotografie','lokalisierte Advertising Assets'],lead2:'Produktion kann umfassen:',items2:['Konzeption','Creative Direction','Skripting','Casting','Locations','Dreh','Editing','Untertitel','Voiceover','Lokalisierung','finale Plattformversionen'],closing:'Das Ziel ist nicht, möglichst viel Content zu produzieren, sondern den richtigen Content für den jeweiligen Markt.'},
{eyebrow:'05 / TALENT & PARTNERSHIPS',title:'Aus lokaler Relevanz können echte Geschäftsmöglichkeiten entstehen.',body:'Wenn Creator oder Marken in einem neuen Markt sichtbar und relevant werden, entstehen neue Möglichkeiten für Partnerschaften und kommerzielle Zusammenarbeit.',lead:'Für Creator kann das zum Beispiel bedeuten:',items:['Kontakte zu lokalen Marken','Kampagnenmöglichkeiten','Creator-Kooperationen','Events','Medienmöglichkeiten','kommerzielle Verhandlungen','lokale Repräsentation','marktspezifisches Talent Management'],lead2:'Für Marken kann das bedeuten:',items2:['Creator-Sourcing','lokale Hosts und Talents','Kampagnenpartnerschaften','Kooperationskonzepte','Ansprache und Koordination','Briefing','Produktion','langfristige Creator-Beziehungen'],closing:'NATIVE kann dabei mit bestehenden Managements, Agenturen und internen Teams zusammenarbeiten.\n\nEs geht nicht einfach darum, Kontakte herzustellen, sondern die richtigen Beziehungen im jeweiligen Markt aufzubauen.'}],
models:{title:'Eine Leistung oder der gesamte Prozess.',body:'Nicht jeder Kunde braucht Full Service.\n\nJe nach Projekt kann NATIVE punktuell unterstützen oder mehrere Bereiche miteinander verbinden.',items:[['STRATEGIEPROJEKT','Ein klar definiertes Market-Entry- oder Localization-Projekt mit konkretem Ergebnis.'],['LOCALIZATION PARTNER','Laufende Anpassung bestehender Inhalte und Kampagnen.'],['PLATFORM MANAGEMENT','Laufendes Publishing, Optimierung und Reporting.'],['PRODUKTIONSPROJEKT','Eine konkrete lokale Produktion, Kampagne oder ein Content-Paket.'],['FULL MARKET SUPPORT','Strategie, Lokalisierung, Plattformmanagement, Produktion und Partnerschaften kombiniert.'],['TALENT / PARTNERSHIP REPRESENTATION','Marktspezifische kommerzielle Betreuung und Repräsentation.']],closing:'Der Umfang richtet sich immer nach Kunde, Markt und Ziel.'},
markets:{title:'Zwischen Europa und China. Von hier aus weiter gedacht.',body:'Unser erster operativer Fokus verbindet zwei Märkte, die sich bei Plattformen, Kommunikationskultur und Zielgruppenerwartungen deutlich unterscheiden.',fromEurope:'Europa → China',fromEuropeBody:'Market Entry, Localization, chinesisches Platform Management, Production und Partnerships.',fromChina:'China → Europa',fromChinaBody:'Europäische Positionierung, Localization, Content Production, Creator-Kampagnen und lokale Marktumsetzung.',line:'Der Ansatz lässt sich überall dort weiterdenken, wo Kommunikation über kulturelle und marktbezogene Grenzen hinweg funktionieren muss.'},
examples:{title:'Unterschiedliche Herausforderungen brauchen unterschiedliche Lösungen.',items:[{label:'BEISPIEL 01',title:'Europäischer Creator → China',lead:'Mögliche Kombination:',services:['Market Entry','Localization','Platform Management','Production','Talent & Partnerships']},{label:'BEISPIEL 02',title:'Chinesische Marke → Europa',lead:'Mögliche Kombination:',services:['Market Entry','Localization','Production','Creator Partnerships']},{label:'BEISPIEL 03',title:'Internationale Brand-Kampagne',lead:'Mögliche Kombination:',services:['Localization','Production','Local Talent','Campaign Execution']}],line:'Welche Leistungen zusammenkommen, richtet sich nach der Aufgabe – nicht nach einem vorgefertigten Paket.'},
final:{title:'Erst die Herausforderung verstehen. Dann die richtige Lösung bauen.',body:'Sag uns, wo du heute stehst, welchen Markt du erreichen willst und was bereits vorhanden ist. Daraus lässt sich der nächste sinnvolle Schritt ableiten.',cta:'Gespräch starten'}},
zh:{
seo:{title:'服务 | NATIVE',description:'为创作者与品牌提供相互连接的市场进入、本地化、平台运营、内容制作与合作资源服务。'},
hero:{eyebrow:'服务',title:'从策略、本地化到执行，真正连在一起。',body:'NATIVE 把创作者与品牌进入新市场所需要的关键能力整合在一起。根据项目不同，可以单独合作，也可以组合成从前期判断到当地执行的一整套流程。',primary:'联系我们',creators:'面向创作者',brands:'面向品牌'},
together:{eyebrow:'服务协作',title:'不是每一个项目，都需要全部服务。',body:'有些客户需要的只是清晰的市场判断，有些则需要本地化、平台运营、内容制作与合作资源一起推进。',lead:'根据项目需要，NATIVE 可以成为：',items:['市场策略伙伴','Localization Partner','Platform Management Partner','Production Partner','Creator & Partnerships Partner','或多个角色的组合'],closing:'重点不是套用固定的代理商套餐，而是解决这个市场真正需要解决的问题。'},
services:[
{eyebrow:'01 / MARKET ENTRY',title:'真正合适的进入方式，始于对市场的清晰判断。',body:'在搭建账号、调整内容或制作品牌活动之前，首先需要确认这个市场值不值得进入，以及最合适的进入方式是什么。',lead:'我们会一起判断：',items:['这个市场是否适合品牌或创作者？','哪类受众应该优先？','哪些平台真正重要？','哪些产品、主题或内容形式应该率先进入？','哪些现有资源可以继续利用？','哪些内容需要本地化？','哪些内容应该在当地重新制作？','应该先测试，还是直接以更大的规模进入？'],lead2:'可能包括：',items2:['市场评估','竞争与品类分析','受众定义','平台选择','定位','上线策略','内容优先级','Market Entry Roadmap'],closing:''},
{eyebrow:'02 / LOCALIZATION',title:'不只是翻译语言，而是调整整个传播语境。',body:'本地化是 NATIVE 的核心能力之一。\n\n内容不应该让人感觉“这是翻译过来的”，而应该让当地受众觉得：这个品牌或创作者真的理解这里。',lead:'根据项目不同，本地化可能涉及：',items:['语言','语气','开场','文案','叙事方式','剪辑','节奏','文化语境','视觉表达','平台逻辑','创作者选择','品牌活动创意','产品信息'],closing:'NATIVE 可以调整已有内容，也可以在单纯适配不够时，为当地市场重新开发版本。',creator:'对于创作者：保留个人风格，同时让内容适应当地的观看习惯与平台逻辑。',brand:'对于品牌：保留品牌身份，同时让沟通方式在当地更自然、更有相关性。'},
{eyebrow:'03 / PLATFORM MANAGEMENT',title:'真正的本地平台影响力，需要持续运营和调整。',body:'账号上线只是开始。\n\nNATIVE 可以负责当地平台的日常运营，也可以与客户现有团队一起推进。',lead:'可能包括：',items:['账号搭建','本地化账号资料','内容发布','标题与文案','发布计划','内容日历','平台优化','数据监测','数据报告','内容建议','当地合作伙伴协调','持续策略优化'],closing:'具体范围会根据平台、市场和项目来确定。'},
{eyebrow:'04 / PRODUCTION',title:'当适配还不够，就为当地市场重新创作。',body:'有些内容可以通过合理的本地化继续使用，有些则应该直接为当地受众重新开发。',lead:'NATIVE 可以制作：',items:['Social-first 视频','短视频内容','产品影片','品牌影片','创作者合作内容','采访','活动内容','旅行内容','新品发布内容','UGC 风格内容','品牌活动摄影','本地化广告素材'],lead2:'制作可以包括：',items2:['创意策划','Creative Direction','脚本','选角','场地','拍摄','剪辑','字幕','配音','本地化','最终平台版本'],closing:'目标不是做更多内容，而是为这个市场做对的内容。'},
{eyebrow:'05 / TALENT & PARTNERSHIPS',title:'真正的本地相关性，可以进一步变成商业机会。',body:'当创作者或品牌在新的市场建立起影响力后，合作与商业机会也会随之出现。',lead:'对于创作者，可以包括：',items:['当地品牌资源','商业活动机会','创作者合作','活动','媒体机会','商务谈判','当地市场代表','特定市场的艺人管理'],lead2:'对于品牌，可以包括：',items2:['创作者筛选','当地主持人与人才','品牌活动合作','合作创意','商务沟通与协调','Briefing','内容制作','长期创作者关系'],closing:'NATIVE 可以与现有管理团队、代理商与品牌内部团队一起工作。\n\n重点不只是“介绍联系人”，而是建立真正适合这个市场的关系。'}],
models:{title:'可以是一项服务，也可以是完整流程。',body:'不是每一个客户都需要 Full Service。\n\n根据项目需要，NATIVE 可以只负责其中一个环节，也可以把多个能力连接起来。',items:[['STRATEGY PROJECT','围绕 Market Entry 或 Localization 的明确项目，并设定清晰交付结果。'],['LOCALIZATION PARTNER','持续调整已有内容与品牌活动。'],['PLATFORM MANAGEMENT','持续发布、优化与数据报告。'],['PRODUCTION PROJECT','针对当地市场的一次具体制作、品牌活动或内容项目。'],['FULL MARKET SUPPORT','策略、本地化、平台运营、内容制作与合作资源整合。'],['TALENT / PARTNERSHIP REPRESENTATION','针对特定市场提供商业支持与代表服务。']],closing:'最终范围根据客户、市场与目标决定。'},
markets:{title:'连接欧洲与中国，也为更多市场留出空间。',body:'我们的第一个业务重点，是连接两个在平台、传播文化与受众期待上差异明显的市场。',fromEurope:'欧洲 → 中国',fromEuropeBody:'Market Entry、Localization、中国平台运营、Production 与 Partnerships。',fromChina:'中国 → 欧洲',fromChinaBody:'欧洲市场定位、Localization、Content Production、Creator Campaigns 与当地市场执行。',line:'只要沟通需要跨越文化与市场边界，这套方法就可以继续延伸。'},
examples:{title:'不同的问题，需要不同的组合。',items:[{label:'示例 01',title:'欧洲创作者 → 中国',lead:'可能的组合：',services:['Market Entry','Localization','Platform Management','Production','Talent & Partnerships']},{label:'示例 02',title:'中国品牌 → 欧洲',lead:'可能的组合：',services:['Market Entry','Localization','Production','Creator Partnerships']},{label:'示例 03',title:'国际品牌活动',lead:'可能的组合：',services:['Localization','Production','Local Talent','Campaign Execution']}],line:'服务怎么组合，取决于真实的问题，而不是预设套餐。'},
final:{title:'先理解问题，再决定最合适的解决方式。',body:'告诉我们你现在在哪里、想进入哪个市场，以及已经有哪些资源。接下来，我们一起定义最合适的下一步。',cta:'联系我们'}}};
