import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {creatorsCopy} from '@/lib/creators';
import {isLocale} from '@/lib/i18n';

type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale}=await params;if(!isLocale(locale))return {};const {seo}=creatorsCopy[locale];return {title:seo.title,description:seo.description,alternates:{canonical:`/${locale}/creators`,languages:{de:'/de/creators',en:'/en/creators','zh-CN':'/zh/creators','x-default':'/en/creators'}}};}
function Mark({number,label}:{number:string;label:string}){return <div className="creator-mark"><span>{number}</span><span>{label}</span></div>}
function EditorialList({items,closingCount=1}:{items:string[];closingCount?:number}){return <><ul className="creator-list">{items.slice(0,-closingCount).map(x=><li key={x}>{x}</li>)}</ul>{items.slice(-closingCount).map(x=><p className="creator-closing" key={x}>{x}</p>)}</>}

export default async function CreatorsPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();const c=creatorsCopy[locale];return <main className="creators-page" lang={locale}>
<section className="creator-hero shell"><Mark number="01" label={c.hero.eyebrow}/><div className="creator-hero-copy"><h1>{c.hero.title}</h1><div className="creator-hero-support"><p>{c.hero.body}</p><div className="creator-actions"><Link className="creator-button creator-button-solid" href={`/${locale}/contact`}>{c.hero.primary}<span>↗</span></Link><a className="creator-button creator-button-line" href="#creator-services">{c.hero.secondary}<span>↓</span></a></div></div></div><div className="creator-media-placeholder"><span>FUTURE SHOWREEL</span><strong><i aria-hidden="true">▶</i><span>Creator footage · Cross-market productions</span></strong><span>VIDEO CONTAINER — 16:9</span></div></section>
<section className="creator-problem creator-section shell"><Mark number="02" label="CONTEXT"/><div className="creator-problem-grid"><h2>{c.problem.title}</h2><div><p>{c.problem.body}</p><strong>{c.problem.closing}</strong></div></div></section>
<section id="creator-services" className="creator-pillars creator-section"><div className="shell"><Mark number="03" label="CAPABILITIES"/><h2>{c.pillars.title}</h2></div><div className="creator-pillar-list">{c.pillars.items.map(([title,body],i)=><article className="creator-pillar shell" key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p><span aria-hidden="true">↗</span></article>)}</div></section>
<section className="creator-content creator-section shell"><Mark number="04" label="CONTENT APPROACH"/><div className="creator-content-grid">{[c.content.existing,c.content.fresh].map((b,i)=><article key={b.title} className="creator-content-column"><span className="creator-column-index">{i?'CREATE':'ADAPT'}</span><h2>{b.title}</h2><p>{b.body}</p><p className="creator-list-lead">{b.lead}</p><EditorialList items={b.items}/></article>)}</div></section>
<section className="creator-journey creator-section"><div className="shell"><Mark number="05" label="CREATOR JOURNEY"/><h2>{c.journey.title}</h2><div className="creator-journey-list">{c.journey.items.map(([title,body],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
<Detail number="06" label="PLATFORM MANAGEMENT" block={c.platform}/>
<section className="creator-production creator-section"><div className="shell"><Mark number="07" label="PRODUCTION"/><DetailBody block={c.production}/><div className="creator-production-frame"><span>LOCAL PRODUCTION</span><span>SPACE FOR FUTURE FILM / PHOTOGRAPHY</span></div></div></section>
<Detail number="08" label="TALENT & PARTNERSHIPS" block={c.talent} closingCount={2}/>
<section className="creator-markets creator-section"><div className="shell"><Mark number="09" label="EUROPE ↔ CHINA"/><div className="creator-market-intro"><h2>{c.markets.title}</h2><p>{c.markets.body}</p></div><div className="creator-market-track" aria-hidden="true"><span>EUROPE</span><i>→</i><i>←</i><span>CHINA</span></div><div className="creator-market-directions"><article><span>01</span><h3>{c.markets.fromEurope}</h3><p>{c.markets.fromEuropeBody}</p></article><article><span>02</span><h3>{c.markets.fromChina}</h3><p>{c.markets.fromChinaBody}</p></article></div><p className="creator-market-line">{c.markets.line}</p></div></section>
<section className="creator-case creator-section shell"><Mark number="10" label={c.case.eyebrow}/><div className="creator-case-grid"><div><h2>{c.case.title}</h2><p>{c.case.body}</p></div><div className="creator-case-frame"><span>COMING SOON</span><strong>{c.case.label}</strong><span>FUTURE VIDEO · PHOTOGRAPHY · RESULTS</span></div></div></section>
<section className="creator-final creator-section"><div className="shell"><Mark number="11" label="LET’S TALK"/><div className="creator-final-grid"><h2>{c.final.title}</h2><div><p>{c.final.body}</p><Link className="creator-button creator-button-light" href={`/${locale}/contact`}>{c.final.cta}<span>↗</span></Link></div></div></div></section>
</main>}

type DetailBlock={title:string;body:string;lead?:string;items:string[]};
function DetailBody({block,closingCount=1}:{block:DetailBlock;closingCount?:number}){return <div className="creator-detail-grid"><div><h2>{block.title}</h2><p>{block.body}</p></div><div><p className="creator-list-lead">{block.lead}</p><EditorialList items={block.items} closingCount={closingCount}/></div></div>}
function Detail({number,label,block,closingCount=1}:{number:string;label:string;block:DetailBlock;closingCount?:number}){return <section className="creator-detail creator-section shell"><Mark number={number} label={label}/><DetailBody block={block} closingCount={closingCount}/></section>}
