import type {Metadata} from 'next';import Link from 'next/link';import {notFound} from 'next/navigation';import {aboutCopy} from '@/lib/about';import {isLocale} from '@/lib/i18n';
type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale}=await params;if(!isLocale(locale))return {};const {seo}=aboutCopy[locale];return {title:seo.title,description:seo.description,alternates:{canonical:`/${locale}/about`,languages:{de:'/de/about',en:'/en/about','zh-CN':'/zh/about','x-default':'/en/about'}}};}
function Mark({number,label}:{number:string;label:string}){return <div className="creator-mark"><span>{number}</span><span>{label}</span></div>}
function List({items}:{items:string[]}){return <ul className="creator-list">{items.map(x=><li key={x}>{x}</li>)}</ul>}
export default async function About({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();const c=aboutCopy[locale];return <main className="about-page" lang={locale}>
<section className="creator-hero shell"><Mark number="01" label={c.hero.eyebrow}/><div className="creator-hero-copy"><h1>{c.hero.title}</h1><div className="creator-hero-support"><p>{c.hero.body}</p><div className="creator-actions"><Link className="creator-button creator-button-solid" href={`/${locale}/contact`}>{c.hero.primary}<span>↗</span></Link><Link className="creator-button creator-button-line" href={`/${locale}/services`}>{c.hero.secondary}<span>↗</span></Link></div></div></div><div className="about-hero-line"><span>CROSS-CULTURAL STRATEGY</span><span>LOCALIZATION</span><span>PRODUCTION</span></div></section>
<section className="about-why creator-section shell"><Mark number="02" label="WHY NATIVE EXISTS"/><div className="creator-detail-grid"><div><h2>{c.why.title}</h2><p>{c.why.body}</p></div><div><p className="creator-list-lead">{c.why.lead}</p><List items={c.why.items}/><p className="creator-closing">{c.why.closing}</p><p className="creator-closing">{c.why.closing2}</p></div></div></section>
<section className="about-principle creator-section"><div className="shell"><Mark number="03" label={c.principle.eyebrow}/><h2>{c.principle.title}</h2><div className="about-principle-body"><div>{c.principle.paras.map(x=><p key={x}>{x}</p>)}</div><div><p className="creator-list-lead">{c.principle.lead}</p><List items={c.principle.items}/></div></div><div className="about-principle-closing">{c.principle.closing.map(x=><p key={x}>{x}</p>)}</div></div></section>
<section className="about-disciplines creator-section shell"><Mark number="04" label="TWO DISCIPLINES, ONE COMPANY"/><h2>{c.disciplines.title}</h2><div className="about-discipline-grid">{[c.disciplines.left,c.disciplines.right].map((x,i)=><article key={x.title}><span>{i?'02':'01'}</span><h3>{x.title}</h3><p>{x.body}</p><p className="creator-list-lead">{x.lead}</p><List items={x.items}/></article>)}</div><p className="about-support-line">{c.disciplines.line}</p></section>
<section className="about-founders creator-section"><div className="shell"><Mark number="05" label={c.founders.eyebrow}/><h2>{c.founders.title}</h2><div className="about-founder-grid">{c.founders.people.map((p,i)=><article key={p.name}><div className="about-portrait"><span>FUTURE PORTRAIT / VIDEO</span><strong>{String(i+1).padStart(2,'0')}</strong></div><div className="about-person"><span>{p.role}</span><h3>{p.name}</h3><p>{p.body}</p><p>{p.body2}</p><p className="creator-list-lead">{p.lead}</p><List items={p.items}/></div></article>)}</div><p className="about-support-line">{c.founders.line}</p></div></section>
<section className="about-network creator-section shell"><Mark number="06" label={c.network.eyebrow}/><div className="creator-detail-grid"><h2>{c.network.title}</h2><div className="about-network-copy">{c.network.paras.map(x=><p key={x}>{x}</p>)}</div></div><p className="about-network-statement">{c.network.statement}</p></section>
<section className="about-knowledge creator-section"><div className="shell"><Mark number="07" label="LOCAL KNOWLEDGE MATTERS"/><div className="creator-detail-grid"><div><h2>{c.knowledge.title}</h2>{c.knowledge.paras.map(x=><p key={x}>{x}</p>)}</div><div><p className="creator-list-lead">{c.knowledge.lead}</p><List items={c.knowledge.items}/><p className="about-knowledge-closing">{c.knowledge.closing}</p></div></div></div></section>
<section className="creator-markets creator-section"><div className="shell"><Mark number="08" label="EUROPE ↔ CHINA"/><div className="creator-market-intro"><div><h2>{c.markets.title}</h2>{c.markets.paras.map(x=><p key={x}>{x}</p>)}</div><p>{c.markets.lead}</p></div><div className="creator-market-track"><span>EUROPE</span><i>→</i><i>←</i><span>CHINA</span></div><div className="creator-market-directions"><article><span>01</span><h3>{c.markets.fromEurope}</h3><p>{c.markets.fromEuropeBody}</p></article><article><span>02</span><h3>{c.markets.fromChina}</h3><p>{c.markets.fromChinaBody}</p></article></div><p className="creator-market-line">{c.markets.line}</p></div></section>
<section className="about-direction creator-section"><div className="shell"><Mark number="09" label={c.direction.eyebrow}/><div className="creator-detail-grid"><h2>{c.direction.title}</h2><div>{c.direction.paras.map(x=><p key={x}>{x}</p>)}{c.direction.closing.map(x=><p className="creator-closing" key={x}>{x}</p>)}</div></div></div></section>
<section className="creator-final creator-section"><div className="shell"><Mark number="10" label="LET’S TALK"/><div className="creator-final-grid"><h2>{c.final.title}</h2><div><p>{c.final.body}</p><Link className="creator-button creator-button-light" href={`/${locale}/contact`}>{c.final.cta}<span>↗</span></Link></div></div></div></section>
</main>}
