import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {servicesCopy,type ServiceBlock} from '@/lib/services';
import {isLocale} from '@/lib/i18n';
type Props={params:Promise<{locale:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale}=await params;if(!isLocale(locale))return {};const {seo}=servicesCopy[locale];return {title:seo.title,description:seo.description,alternates:{canonical:`/${locale}/services`,languages:{de:'/de/services',en:'/en/services','zh-CN':'/zh/services','x-default':'/en/services'}}};}
function Mark({number,label}:{number:string;label:string}){return <div className="creator-mark"><span>{number}</span><span>{label}</span></div>}
function List({title,items}:{title:string;items:string[]}){return <div className="services-list-block"><p className="creator-list-lead">{title}</p><ul className="creator-list">{items.map(x=><li key={x}>{x}</li>)}</ul></div>}
function ServiceSection({block,index}:{block:ServiceBlock;index:number}){const dark=index===1||index===3;const split=block.items2?.length;return <section className={`services-core creator-section ${dark?'services-core-dark':''}`}><div className="shell"><Mark number={String(index+3).padStart(2,'0')} label={block.eyebrow}/><div className="services-core-heading"><h2>{block.title}</h2><p>{block.body}</p></div><div className={`services-core-lists ${split?'is-split':''}`}><List title={block.lead} items={block.items}/>{split&&<List title={block.lead2!} items={block.items2!}/>}</div>{(block.closing||block.creator||block.brand)&&<div className="services-core-notes">{block.closing&&<p>{block.closing}</p>}{block.creator&&<p>{block.creator}</p>}{block.brand&&<p>{block.brand}</p>}</div>}</div></section>}
export default async function ServicesPage({params}:Props){const {locale}=await params;if(!isLocale(locale))notFound();const c=servicesCopy[locale];return <main className="services-page" lang={locale}>
<section className="creator-hero services-hero shell"><Mark number="01" label={c.hero.eyebrow}/><div className="creator-hero-copy"><h1>{c.hero.title}</h1><div className="creator-hero-support"><p>{c.hero.body}</p><div className="creator-actions"><Link className="creator-button creator-button-solid" href={`/${locale}/contact`}>{c.hero.primary}<span>↗</span></Link><Link className="creator-button creator-button-line" href={`/${locale}/creators`}>{c.hero.creators}<span>↗</span></Link><Link className="creator-button creator-button-line" href={`/${locale}/brands`}>{c.hero.brands}<span>↗</span></Link></div></div></div><div className="services-hero-index">{['01 MARKET ENTRY','02 LOCALIZATION','03 PLATFORM MANAGEMENT','04 PRODUCTION','05 TALENT & PARTNERSHIPS'].map(x=><span key={x}>{x}</span>)}</div></section>
<section className="services-together creator-section shell"><Mark number="02" label={c.together.eyebrow}/><div className="creator-detail-grid"><div><h2>{c.together.title}</h2><p>{c.together.body}</p></div><div><List title={c.together.lead} items={c.together.items}/><p className="creator-closing">{c.together.closing}</p></div></div></section>
{c.services.map((s,i)=><ServiceSection key={s.eyebrow} block={s} index={i}/>) }
<section className="services-models creator-section"><div className="shell"><Mark number="08" label="FLEXIBLE ENGAGEMENT MODELS"/><div className="services-models-heading"><h2>{c.models.title}</h2><p>{c.models.body}</p></div><div className="services-model-list">{c.models.items.map(([title,body],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="services-model-closing">{c.models.closing}</p></div></section>
<section className="creator-markets creator-section"><div className="shell"><Mark number="09" label="EUROPE ↔ CHINA"/><div className="creator-market-intro"><h2>{c.markets.title}</h2><p>{c.markets.body}</p></div><div className="creator-market-track"><span>EUROPE</span><i>→</i><i>←</i><span>CHINA</span></div><div className="creator-market-directions"><article><span>01</span><h3>{c.markets.fromEurope}</h3><p>{c.markets.fromEuropeBody}</p></article><article><span>02</span><h3>{c.markets.fromChina}</h3><p>{c.markets.fromChinaBody}</p></article></div><p className="creator-market-line">{c.markets.line}</p></div></section>
<section className="services-examples creator-section"><div className="shell"><Mark number="10" label="SERVICE COMBINATIONS"/><h2>{c.examples.title}</h2><div className="services-example-grid">{c.examples.items.map(x=><article key={x.label}><span>{x.label}</span><h3>{x.title}</h3><p>{x.lead}</p><ul>{x.services.map(s=><li key={s}>{s}</li>)}</ul></article>)}</div><p className="services-examples-line">{c.examples.line}</p></div></section>
<section className="creator-final creator-section"><div className="shell"><Mark number="11" label="LET’S TALK"/><div className="creator-final-grid"><h2>{c.final.title}</h2><div><p>{c.final.body}</p><Link className="creator-button creator-button-light" href={`/${locale}/contact`}>{c.final.cta}<span>↗</span></Link></div></div></div></section>
</main>}
