'use client';
import {useState} from 'react';
import type {ContactCopy} from '@/lib/contact';

export type ContactSubmissionPayload={inquiryType:string;name:string;company:string;email:string;website:string;role:string;currentMarket:string;targetMarket:string;platforms:string[];projectTypes:string[];budget:string;timeline:string;description:string};
export type ContactSubmissionHandler=(payload:ContactSubmissionPayload)=>Promise<void>;
const initial:ContactSubmissionPayload={inquiryType:'',name:'',company:'',email:'',website:'',role:'',currentMarket:'',targetMarket:'',platforms:[],projectTypes:[],budget:'',timeline:'',description:''};

export function ContactForm({copy,onSubmit}:{copy:ContactCopy;onSubmit?:ContactSubmissionHandler}){
 const [data,setData]=useState(initial),[step,setStep]=useState(1),[errors,setErrors]=useState<Record<string,string>>({});
 const set=(key:keyof ContactSubmissionPayload,value:string|string[])=>setData(d=>({...d,[key]:value}));
 const toggle=(key:'platforms'|'projectTypes',value:string)=>set(key,data[key].includes(value)?data[key].filter(x=>x!==value):[...data[key],value]);
 const validate=(target=step)=>{const next:Record<string,string>={};if(!data.inquiryType)next.inquiryType=copy.errors.inquiry;if(target===1){if(!data.name.trim())next.name=copy.errors.required;if(!data.email.trim())next.email=copy.errors.required;else if(!/^\S+@\S+\.\S+$/.test(data.email))next.email=copy.errors.email}if(target===3&&!data.description.trim())next.description=copy.errors.required;setErrors(next);return !Object.keys(next).length};
 const advance=()=>{if(validate())setStep(s=>Math.min(3,s+1));else requestAnimationFrame(()=>document.querySelector<HTMLElement>('[aria-invalid="true"], #inquiry-error')?.focus())};
 const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();if(!validate(3)||!onSubmit)return;await onSubmit(data)};
 return <>
  <section className="contact-inquiry creator-section shell" aria-labelledby="inquiry-title"><div className="creator-mark"><span>02</span><span>INQUIRY TYPE</span></div><h2 id="inquiry-title">{copy.question}</h2><div className="inquiry-options" role="radiogroup" aria-describedby={errors.inquiryType?'inquiry-error':undefined}>{copy.inquiries.map((x,i)=><button type="button" role="radio" aria-checked={data.inquiryType===x.value} className={data.inquiryType===x.value?'inquiry-option selected':'inquiry-option'} onClick={()=>{set('inquiryType',x.value);setErrors(e=>({...e,inquiryType:''}))}} key={x.value}><span>{String(i+1).padStart(2,'0')}</span><strong>{x.title}</strong><p>{x.body}</p><i aria-hidden="true">{data.inquiryType===x.value?'●':'○'}</i></button>)}</div>{errors.inquiryType&&<p className="form-error" id="inquiry-error" role="alert" tabIndex={-1}>{errors.inquiryType}</p>}</section>
  <section className="contact-form-section creator-section"><div className="shell"><div className="creator-mark"><span>03</span><span>CONTACT FORM</span></div><div className="form-progress" aria-label="Form progress">{copy.steps.map((x,i)=><button type="button" key={x} className={step===i+1?'active':''} onClick={()=>i+1<step&&setStep(i+1)} disabled={i+1>step}><span>0{i+1}</span>{x}</button>)}</div>
  <form className="contact-form" onSubmit={handleSubmit} noValidate>
   {step===1&&<fieldset><legend>{copy.steps[0]}</legend><div className="form-grid"><Field id="name" label={copy.fields.name} required tag={copy.required} value={data.name} error={errors.name} onChange={v=>set('name',v)}/><Field id="company" label={copy.fields.company} tag={copy.optional} value={data.company} onChange={v=>set('company',v)}/><Field id="email" label={copy.fields.email} type="email" inputMode="email" required tag={copy.required} value={data.email} error={errors.email} onChange={v=>set('email',v)}/><Field id="website" label={copy.fields.website} tag={copy.optional} value={data.website} onChange={v=>set('website',v)}/><Field id="role" label={copy.fields.role} tag={copy.optional} value={data.role} onChange={v=>set('role',v)}/></div></fieldset>}
   {step===2&&<fieldset><legend>{copy.steps[1]}</legend><div className="form-grid"><Field id="current" label={copy.fields.current} tag={copy.optional} value={data.currentMarket} onChange={v=>set('currentMarket',v)}/><Field id="target" label={copy.fields.target} tag={copy.optional} value={data.targetMarket} onChange={v=>set('targetMarket',v)}/></div><ChoiceGroup label={copy.fields.platforms} values={copy.platformOptions} selected={data.platforms} onToggle={v=>toggle('platforms',v)}/></fieldset>}
   {step===3&&<fieldset><legend>{copy.steps[2]}</legend><ChoiceGroup label={copy.fields.project} values={copy.projectOptions} selected={data.projectTypes} onToggle={v=>toggle('projectTypes',v)}/><div className="form-grid form-grid-selects"><Select id="budget" label={copy.fields.budget} tag={copy.optional} value={data.budget} options={copy.budgetOptions} onChange={v=>set('budget',v)}/><Select id="timeline" label={copy.fields.timeline} tag={copy.optional} value={data.timeline} options={copy.timelineOptions} onChange={v=>set('timeline',v)}/></div><label className="form-field form-textarea" htmlFor="description"><span>{copy.fields.description}<small>{copy.required}</small></span><textarea id="description" value={data.description} onChange={e=>{set('description',e.target.value);if(e.target.value.trim())setErrors(x=>({...x,description:''}))}} onBlur={()=>{if(!data.description.trim())setErrors(x=>({...x,description:copy.errors.required}))}} placeholder={copy.fields.placeholder} aria-invalid={!!errors.description} aria-describedby={errors.description?'description-error':undefined}/>{errors.description&&<em id="description-error" className="form-error" role="alert">{errors.description}</em>}</label><div className="file-placeholder" aria-disabled="true"><span>＋</span><strong>{copy.fields.file}</strong><small>{copy.optional} · Future integration</small></div></fieldset>}
   <div className="form-actions">{step>1&&<button type="button" className="creator-button creator-button-line" onClick={()=>setStep(s=>s-1)}>← {copy.back}</button>}{step<3?<button type="button" className="creator-button creator-button-solid" onClick={advance}>{copy.next}<span>→</span></button>:<button type="submit" className="creator-button creator-button-solid" disabled={!onSubmit}>{copy.send}<span>↗</span></button>}</div>{step===3&&<><p className="form-privacy">{copy.privacy}</p>{!onSubmit&&<p className="form-dev-note" role="status">{copy.devNote}</p>}</>}
  </form></div></section>
 </>;
}

function Field({id,label,tag,value,onChange,type='text',inputMode,required=false,error}:{id:string;label:string;tag:string;value:string;onChange:(v:string)=>void;type?:string;inputMode?:'email';required?:boolean;error?:string}){return <label className="form-field" htmlFor={id}><span>{label}<small>{tag}</small></span><input id={id} name={id} type={type} inputMode={inputMode} autoComplete={id==='name'?'name':id==='email'?'email':id==='company'?'organization':id==='website'?'url':undefined} value={value} required={required} onChange={e=>onChange(e.currentTarget.value)} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined}/>{error&&<em id={`${id}-error`} className="form-error" role="alert">{error}</em>}</label>}
function Select({id,label,tag,value,options,onChange}:{id:string;label:string;tag:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="form-field" htmlFor={id}><span>{label}<small>{tag}</small></span><select id={id} value={value} onChange={e=>onChange(e.target.value)}><option value="">—</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function ChoiceGroup({label,values,selected,onToggle}:{label:string;values:string[];selected:string[];onToggle:(v:string)=>void}){return <fieldset className="choice-group"><legend>{label}</legend><div>{values.map(x=><label key={x}><input type="checkbox" checked={selected.includes(x)} onChange={()=>onToggle(x)}/><span>{x}</span></label>)}</div></fieldset>}
